### ISSUE TITLE
Rewards for unit testing

### ISSUE THREAD

**Issue by kunaimaster** [amark/gun#1018]
hi!
please can anybody explain how much actual is info from here: https://gun.eco/docs/Bounty ?
considering link above points to PDF file containing an info about the deadline, which is outdated for more than a year: https://era.eco/2019/grant.pdf
that's why i'm asking: i am fanatic Node.js dark side ninja, who changes the world every day, to ensure decentralizing it will save our freedom in future, and i got the noticement abt $2k bounty for tests written in my lovely JS.
is this still actual? how much time is needed for Mark to check out my tests and pay $250 if first one will suit him enough?
is there possibility for me to recieve reward in litecoins without of any uncovering finance operations if my test is ok?
how long to wait i have to between test[s] code uploading, and rewarding decision, regarding uploaded test, being done?

due to if rewards are still actual, i'll begin to implement whole needed tests from third block of text i linked to.

**Comment by amark** [comment]
The bounty/grants/etc. are currently closed. :( Sorry.
