### ISSUE TITLE
Examples page is without <head> tag

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#102]
Most notably, there is no title for the page, character encoding hasn't been declared, and there is no responsive meta tag.

- Issues brought to you in collaboration with _Sean_

**Comment by amark** [comment]
Thanks! Would you be interested in making a pull request changing these specific things? Would love to have you as a contributor in that regard!

**Comment by PsychoLlama** [comment]
Happy to help! Is there anything else you'd like to see in the future?

**Comment by amark** [comment]
Are you preferring HTML/CSS stuff or JS?

Thanks! Was this your first?

**Comment by PsychoLlama** [comment]
I can do all three, and tend towards both JS and CSS work. And yep, this was my first :)

**Comment by amark** [comment]
Woohoo!!! I'd put in a bunch of emoticons right here to celebrate but I don't know how to do that. @metasean we should figure out some sort of badge system!

If you like frontend design and stuff, we're in need of beautiful example apps (even if they are basic). Like http://todos.loqali.com/ by @jveres is gorgeous, and on Friday I should be able to show you a cool little game I made with gun (but it is ugly) so games especially would make for fun demos.

However, if you don't really like or not super good with design, and more interested in technical things... there are lots of issues around integrating with SQL parsers or MongoDB query stuff.

**Comment by PsychoLlama** [comment]
Hey, this sounds fun! I'm good at making things look pretty, but completely original designs are super hard, and I avoid photoshop altogether. The technical things excite me more than design, though. Sean and I have been talking about ways I could help (WebRTC and building up the chat app). It would be awesome to speak more with you Friday and get a feel for what you're looking for...

**Comment by amark** [comment]
Sweet! A lot of people have been referencing @feross 's https://github.com/feross/simple-peer module as a starting point. I've never touched WebRTC before though, so I leave it to you to figure out what is easiest. My other guess is that gun's websocket module can be used to signal the peer ids to bootstrap the connection into WebRTC or whatever. But again, you probably figure out more than I can.

**Comment by PsychoLlama** [comment]
That repo looks pretty awesome! I've also found the W3 spec, and some HTML5Rocks tutorials. It can't be that hard, right? Haha, humor.
I'll check into it, see what I figure out, and we'll follow up Friday... Sound good?

**Comment by amark** [comment]
@PsychoLlama to be honest, I do think you are right. I think a lot of people are "scared" to look at the raw source, like the W3 spec and stuff like that - because they aren't "experts" or something. But you are right, nothing is hard if you put your mind to the task - it is just fun and intricate. And I really think we need more people with that type of mindset and philosophy. It is definitely the one we are trying to encourage people on with regards to databases, anybody can understand these things and become the expert themselves.

:) sounds awesome, talk to you then. Hopefully I'll figure out my current bug on the game I'm working on.
