### ISSUE TITLE
Are there examples specifically for NodeJs?

### ISSUE THREAD

**Issue by GildedHonour** [amark/gun#1030]
The examples in `examples` are for js in the browser. Are there examples specifically for NodeJs?

If I want to use it as distributed database in network of, say, 10 nodes/servers, where everyone should be able to connect to everyone else and read-write, how will I implement it? 

Not 10 browsers, but 10 machines/servers

**Comment by capitalistdog** [comment]
Shockwallet uses a nodejs daemon with gun, but is using `SEA` so it's pub-sub instead of shared read/write. Could just as well not use SEA though.

Have a look at https://github.com/shocknet/api or the test for our that use case https://github.com/amark/gun/blob/master/test/panic/shocknet.js

**Comment by amark** [comment]
@GildedHonour thanks @capitalistdog 👍 

API works same as browser, so just in NodeJS list the other NodeJS peers. If on same Local Area Network, they'll automatically UDP multicast discover each other, no need to list peers.

http://chat.gun.eco has more people to reply faster. :) Closing.
