### ISSUE TITLE
Usage from other programming languages?

### ISSUE THREAD

**Issue by GiraffeKey** [amark/gun#1032]
I think being able to use the protocol from other languages is important as many people do not like JavaScript and WASM-based scripting langs will likely take the lead in the future once they are further developed. Also, webview is a better alternative to Electron for desktop software.

Is it currently possible to create alternative clients to the JavaScript implementation or would it require rewriting the entire code base?

**Comment by amark** [comment]
@GiraffeKey ah, just replied to you in other thread.

:) base port can be done in a few hours :) I rebuilt GUN on stage in 30min here: https://gun.eco/docs/Porting-GUN so yes! See #577 where I just replied to you - you should join the rust port!

**Comment by GiraffeKey** [comment]
Nice, Rust is exactly the language I was hoping to be able to use.

**Comment by amark** [comment]
@GiraffeKey 👍  yeah I think these are the only 2 languages we'd need, all else could come from these 2. Gonna close, since more of a Q than bug. :)
