### ISSUE TITLE
Is there any way to integrate Gun with Koa

### ISSUE THREAD

**Issue by krishnakairi** [amark/gun#1040]
I want to start koa js app and gun on same port.

**Comment by YangHanlin** [comment]
You may want to consider [koa-connect](https://github.com/vkurchatkin/koa-connect) to convert `Gun.serve` (which is valid Express middleware, as is demostrated in the [Express example](https://github.com/amark/gun/blob/master/examples/express.js)) to Koa middleware therefore to use it with Koa.

Our team have recently successfully integrated Gun with Egg.js, another Web framework derived from Koa.

**Comment by jabis** [comment]
If you have no other websocket (connection:"upgrade") -handlers in your koa app you should be good to go with @YangHanlin 's advice - serve the necessary files and pass the websocket handling to gun's handler - other option is to reverse proxy the `/gun` path to of your app to the separate gun server instance

**Comment by iwater** [comment]
`
const app = new Koa();
const web = app.listen(80);
Gun({web});
`

**Comment by amark** [comment]
👏 👏 👏 👏 👏 
Seems like this got answered. You all ROCK! Gonna close. :)
