### ISSUE TITLE
Enhancement Request: Give a message when visitors are redirected to HTTPS by SEA module

### ISSUE THREAD

**Issue by YangHanlin** [amark/gun#1041]
Our team is working on a P2P file transfer tool used in LANs based on Gun, and we have been tracking a weird issue in which visitors to the web frontend are automatically redirected to HTTPS unless they are visiting `localhost`. But the servers are accessed using IP addresses rather than domain names, so HTTPS deployment is almost impossible and users are experiencing errors.

We finally found the cause of the issue is that we have mistakenly `import`ed the SEA module (but have not really used it). When SEA is being imported, it will automatically redirect visitors to HTTPS (see referenced source below).

https://github.com/amark/gun/blob/cb3f8600d9b78285c76265b5f95f7110b177cdba/sea.js#L33-L42

We understand that SEA won't work with plain HTTP, but mistakenly importing this module to our project has taken us much time to debug. Had this module give a message about this redirect, we would be much faster to locate and resolve the issue.

In my college, there are several other teams working on different systems based on Gun, which may also be affected by this issue. **So we are requesting Gun to give a message when automatically redirecting visitors to HTTPS.** For example, we would suggest adding a line in the lines above:

```javascript
console.warn('WebCrypto used by GUN SEA implementation does not work without HTTPS. Will automatically redirect.');
```

We'd also be happy to propose a PR for that.

**Comment by amark** [comment]
@YangHanlin ah, well explained! You've seen my usual response about browsers requiring `https` for WebCrypto - but you weren't even using SEA and somehow it got injected. I'm sorry about that.

Yes, please, I'll accept such a PR! Question tho: Won't people not be able to see the log because it'll get cleared on redirect? (We can't delay the redirect or else that'd add latency to loading pages)

**Comment by amark** [comment]
getting security/encryption working on LANs with dynamic IPs has been a huuuuge pain in the butt because of browsers `https` policy, it is super super frustrating. We're hoping browsers will eventually change their stance for at least sub-networks.

**Comment by YangHanlin** [comment]
@amark Thanks for your reply!

> Question tho: Won't people not be able to see the log because it'll get cleared on redirect?

Personally I think it is not a problem. When we were tracking our weird redirect issue, we enabled the `Preserve Logs` option in devtools to look for possible information about the redirect; I think other developers may also do so when they are resolving similar issues.

**Comment by amark** [comment]
@YangHanlin 👍 . Will pull, just let me know when you can! :) Thanks again.

**Comment by YangHanlin** [comment]
@amark I have just proposed a PR #1055 to resolve this issue. Please review it when you have time. Thanks!
