### ISSUE TITLE
How to .put on root and immediately get its UUID?

### ISSUE THREAD

**Issue by rafi16jan** [amark/gun#1057]
Hi, as the title describes I was trying to get the resulting UUID of a put. After googling I can't seem to find the official way to do it but I do found that you can directly get the node if you .get it.

Fortunately I found that if you put callback as a second argument on put you can actually access .on.graph and it will show the UUID as the sole key, so I test the validity of thar UUID with this one liner:

```javascript
Gun().put({name: 'James'}, (arg1, arg2) => arg1 && arg1.ok && arg2 && Gun().get(Object.keys(arg2.on.graph)[0]).once(console.log))
```
And it prints James' node.

Is this .on.graph a private/public API? Will it change sometimes in the future? Are there better ways to get the UUID?

**Comment by rafi16jan** [comment]
Closing as no one answers for a week. Been testing GunDB too and Radisk sucks. Only fully works with text, it cripples when I store numerical value even with well formatted zfilled number.

**Comment by i001962** [comment]
@rafi16jan et al you may have a faster response to question when asking here [chat.gun.eco ](chat.gun.eco )
