### ISSUE TITLE
The todo app examples in the docs are broken

### ISSUE THREAD

**Issue by petko10** [amark/gun#1065]
On Chromium this page [https://gun.eco/docs/Basic-Todo-App-Guide](https://gun.eco/docs/Basic-Todo-App-Guide) currently has non-functional code snippets - when clicking any button in the previews - they reload and show a cramped version of the whole tutorial page.

**Comment by nsreed** [comment]
I only see this behavior in the first snippet, which is expected because there isn't a click handler for the button. The rest of the examples seem to work as expected.

**Comment by petko10** [comment]
Either I hit some niche bug, or there was an update, because I tested again and indeed only the first snippet does that.
