### ISSUE TITLE
radata missing in superpeer mode

### ISSUE THREAD

**Issue by capitalistdog** [amark/gun#1073]
Using the `http.js` example it appears that data is not being saved to disk as`/radata` is not present anywhere, though `stats.radata` is and is constantly written.

I only noticed this after setting up a redundant peer and was looking to compare data sizes. Neither the latest commit nor one from September (running) seem to have it, though I'm sure I've seen at some point in previously in test.

**Comment by amark** [comment]
@capitalistdog which version (?)

**Comment by capitalistdog** [comment]
older peer is 2020.520, new one is 2020.1232

**Comment by capitalistdog** [comment]
> @capitalistdog which version (?)

older peer is 2020.520, new one is 2020.1232

**Comment by capitalistdog** [comment]
@amark I ran the peer without https envs, since we used to run it that way in test.

radata is written as normal without https, so it seems related to the `config` being passed in http.js.

**Comment by amark** [comment]
@capitalistdog thank you for hunting that down, interesting, the only special checks for HTTPS is this config here https://github.com/amark/gun/blob/master/examples/http.js#L14-L18 which don't do any storage changes :/ you have a guess of where it could be getting flipped?

**Comment by capitalistdog** [comment]
Turned out to be a red herring, https was use with systemd which ran it in a different context. Still no idea where radata was going, but it started to store correctly by defining a working directory in the unit file.
