### ISSUE TITLE
Consistient Graph Errors and Callback Failures

### ISSUE THREAD

**Issue by 1MaddieX** [amark/gun#1076]
Across multiple versions of `Gun` I've noticed consistent issues when trying to run save operations. Either the graph corrupts, `Gun` freezes the running function, or a callback doesn't get called at all. I am using this with `Next.js` but I don't think that should cause issues, as it's just an abstraction of `react`. After authenticating a user, I try to place some info on the user's graph, then replicate that across some indexes.

Some of the specific errs that I've seen are:
```
Error: Invalid graph! '~KlGIehHh...' soul not same.

Object { "@": "pmafdmgcnse", err: "Unverified data.", "#": "IwWWmMc03", _: _(), "$": {…} }

sea.js:453
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
```
I've also got some DOM exceptions in the past from `Gun`. The errs that I get seem to change from time-to-time, with some scenarios having a corrupt graph, then a few hours later we have the process freezing error, just to name something specifically.

https://replit.com/@iml1vely/VigorousTwinApache <- A repl.it with the outline of my auth code, might be kinda janky cause I threw it together quick, but it should work.

**Comment by amark** [comment]
@1MaddieX tried looking into this, assuming it is the same demo when I click the replit link, I don't get any errors when I try the connect/done button. Maybe I need to do something else in the demo to trigger it?

If not: What browser / version are you using? Does it happen on replit or only on localhost/file: (?) What happens if you `localStorage.clear()` or use a different alias/user? etc.

**Comment by 1MaddieX** [comment]
it happens on replit, localhost, and .local domains, haven't tried file:// . you should just be able to press the connect button (you can change the alias with the web3Auth() function or clear localStorage and run again) and see the errors in the site's console. I'm running this on gun@2020.514 on the latest version of Firefox. The errors seem to show up when writing to a graph after creating a user, but I haven't tried writing after authenticating a user, only reading.

**Comment by 1MaddieX** [comment]
Closing this, seemed to be an issue with firefox
