### ISSUE TITLE
Gun tries to create a directory for storing files, regardless of the config

### ISSUE THREAD

**Issue by n3v3rd1e** [amark/gun#1084]
My goal is to run gun within the AWS lambda without writing anything to disk, which currently seems to be unachievable.
Gun does not write any files to disk, but creates a folder

```ts
const gun = new Gun({
  peers: ['peerUrl'],
  radisk: false,
  localStorage: false,
  rfs: false // I was recommended to try this option, not sure if it does anything, but there was no difference in this case
})
```

Commenting out [this line](https://github.com/amark/gun/blob/master/lib/rs3.js#L103) makes it stop

**Comment by amark** [comment]
@n3v3rd1e yes thank you, you confirmed that even when rad/etc. turned off, the S3 environment variables overrule that. I'll try to get this PRed within the next week (remind me after Wednesday if I haven't by then), or if you want credit <3 please do -  just prevent that line from being called if `false === opt.rfs` should do the trick & be safe!

**Comment by amark** [comment]
@n3v3rd1e this should have done it? https://github.com/amark/gun/commit/8c8b51371656ff346166e93d57e115676d0aa7c1 try and let me know if it works (latest github main, not npm). Thanks! Closing (reopen if it doesn't work)
