### ISSUE TITLE
The search textfield of the website is broken

### ISSUE THREAD

**Issue by joseDaKing** [amark/gun#1098]
The search textfield of the website is broken, which makes it harder for easily finding stuff

**Comment by noctisatrae** [comment]
I'm sorry but I tried to search `gun.get()` from [the documentation](https://gun.eco/docs/) and end up with the content I searched for. 

However, it's true that this search bar should be improved. You got a limited time for typing what you're searching for and if you exceed the time allowed, you end up with no output. 

It'd be better if the input waited for us to actually hit `enter` key to begin the search. If I can view the code, I'll try to do something.

**Comment by amark** [comment]
@joseDaKing @noctisatrae hey thanks for the report! A few days ago @estebanrfp (which if you're reading this, please twitter DM me now! Trying to make tweaks to homepage but the build system doesn't work lol) improved the search tool!

Can you try the new version & let us know? It is a static website, so there's only so much we can do (without... loading all the docs into your browser cache pre-emptively oye!). Or have any other ideas? Gonna close (tho please re-open on https://github.com/estebanrfp/gun.eco )
