### ISSUE TITLE
User login with Svelte

### ISSUE THREAD

**Issue by ulvido** [amark/gun#1108]
I am trying to make a user login with svelte but browser console gives this error. any ideas?

```javascript
import Gun from "gun/gun";
const gun = Gun(["http://localhost:8080/gun"]);
	
let user = gun.user();
```

![2021-08-08 17-31-08 ekran görüntüsü](https://user-images.githubusercontent.com/27722274/128635571-d5ab8d92-c28a-4914-9e61-c902eecb4529.png)

**Comment by fluidi-beep** [comment]
You cannot pass in an array like that into the Gun constructor. You need to pass in either a string including a single peer relay URL, or an "options" object that contains the key "peer" with the value being an array of peers.
Here is a modified version of your code that should work.
```
import Gun from "gun/gun";
const gun = Gun("http://localhost:8080/gun");
	
let user = gun.user();
```
I usually connect to multiple peers so my constructor looks something like this ```const gun = Gun({ peers: [http://localhost:8765/gun", "https://my-hosted-gun-server.com/gun", "https://gun-us.herokuapp.com/gun"]})```

**Comment by ulvido** [comment]
no luck for the npm packages.

I fixed by downloading `gun.js` and `sea.js` and put them in public/index.html

#### index.html
```html
...
<script defer src='lib/gun.js'></script>
<script defer src='lib/sea.js'></script>
...
```

and init in gun.ts

#### gun.ts
```ts
// for initialize once
export const gun = Gun();
export const user = gun.user().recall({ sessionStorage: true });
```

and use it in App.svelte

#### App.svelte
```javascript
...
import { gun, user } from "./gun";
...
```
but I dont know if any harm would come in future

**Comment by ulvido** [comment]
and maybe this addition would help. `import SEA from "gun/sea";`

closed.


```
   import Gun from "gun/gun";
 + import SEA from "gun/sea";
   const gun = Gun(["http://localhost:8080/gun"]);
	
   let user = gun.user();
```

**Comment by bostondevin** [comment]
I'm having trouble getting this working also - i'm trying to put it into __layout.svelte and having it available everywhere  - any clues?

**Comment by ulvido** [comment]
I am not an expert but if you import the js with `type="module"` it works. vite makes it easier. for testing create a vite project:

```bash
npm init vite
```
follow the project creation process..

```bash
cd your-new-project
```
```bash
npm i
```
```bash
npm i gun
```
import gun like my previous comment

```js
import Gun from "gun/gun";
import SEA from "gun/sea";
const gun = Gun();
	
let user = gun.user();
```
run the dev server
```bash
npm run dev
```
also I suggest to run `npm run build` command and inspect the creted `index.html` and see how the js imported.
