### ISSUE TITLE
How much data can this hold?

### ISSUE THREAD

**Issue by bostondevin** [amark/gun#1109]
Question #1 for me is this: "How much data can this handle?" 

Maybe add it to the FAQ's?

Love it so far - yeah, not so obvious it needed a relay server from the docs, but once I had that - Bingo!

**Comment by i001962** [comment]
You'll have a faster response to questions like this in the discord.

https://chat.gun.eco

Please close this issue if it's resolved.

**Comment by amark** [comment]
@bostondevin 👏  @i001962 thanks for the heads up.

1. GUN itself does not have a limit. (or its theoretical limit is the ASCII limit of radix file chunks in a folder * chunk size) Common storage adapters may have limits:
2. localStorage is limited to 5MB.
3. IndexedDB is limited to (?) 50% of a user disk who approves of upped limit (?)
4. If you're using S3 for backups, it limits each chunk to about 4TB (never gonna want a chunk to be that big in GUN tho)
5. ...

To discuss more, please jump on the chat. Issues here are for bugs, not Qs (sorry)! Closing.
