### ISSUE TITLE
Date based access to content using ACL

### ISSUE THREAD

**Issue by shealan** [amark/gun#1124]
I'm trying to build a system with Gun that shares access to encrypted media files. Giving access on a file to file basis is relatively simple, but I need to somehow give users the ability to access groups of files for a specific date period.

The only way I can think of doing it is to run some kind of scheduled job to run and add/remove users from ACL. I'm hoping for something that can work in a more decentralised manner.

Has anyone managed to achieve anything like this?

**Comment by amark** [comment]
@shealan hey! The community contributed https://gun.eco/docs/SEA.certify has an experimental time-based/TTL/expiry system you could try out. :) I hope this helps? Re-open if need be!

Also: Help! Please, Qs should be asked on http://chat.gun.eco , not in issues. Bugs here. Thanks!

**Comment by shealan** [comment]
Thank you!
