### ISSUE TITLE
Unfriendly number paths

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#113]
Zero is a falsy value, so when `Gun().path(0)` is called it yields undefined. _However_ `Gun().path(1)` is truthy, so a path is returned.
I think gun should allow you to put in numbers natively as a path, instead of requiring you to `String()` it. Either way it's inconsistent behavior :(

**Comment by amark** [comment]
Agreed. Noticed this bug a few days ago and fixed it but I added other tests that aren't passing yet so I haven't pushed. But the fix is already done, just waiting to fix the other stuff as well.

**Comment by PsychoLlama** [comment]
Fabulous! Thanks Mark!

**Comment by amark** [comment]
this is fixed in latest ... or earlier, actually! c3961688bf06ce71022a5ff946961c3ba526b639
