### ISSUE TITLE
conflict resolution

### ISSUE THREAD

**Issue by mikestaub** [amark/gun#1135]
If two users edit the same node field, which update wins? Is the conflict recorded?

See here for an example:

https://github.com/automerge/automerge#conflicting-changes

**Comment by amark** [comment]
1 minute explainer video: https://www.youtube.com/watch?v=neqz5t4FSJI&feature=youtu.be

It chooses the """latest""" within-bounds. This prevents attacks, to learn more: https://gun.eco/distributed/matters.html

You can write a hook to catch the conflict, but by it is not recorded.

Hey, your profile says graphics - do you do WebGL? Can you teach me?

Closing.
