### ISSUE TITLE
How can I prevent bad actors from nullifying all data.

### ISSUE THREAD

**Issue by Aex12** [amark/gun#1136]
I've recently discovered this project. It seems awesome. But I cant see anywhere how can I prevent bad actors from nullifying all data. 

Let's suppose some bad actor wants to destroy my dapp. Is there something I can do to prevent him doing something like this:

```js
const Gun = require('gun/gun');

const gun = new Gun({ peers: [ /* the array of peer servers I use on my dapp /* ] });

gun.get('users').put(null);
gun.put(null);
gun.map().put(null);
```

Am I missing something?

**Comment by okpatil4u** [comment]
+1
This is where I am stuck too.

**Comment by amark** [comment]
@Aex12 @okpatil4u hey :) the big button on the website and the README and docs scream about the 5min interactive tutorial... its covered there, there is no way you can miss it (please let me know how? so I can fix)

https://gun.eco/docs/Todo-Dapp

The User system stops that.

**Comment by okpatil4u** [comment]
Thank you @amark. I tried to stay away from the website, it has flashes enough to cause epilepsy. I have been going through the documentations, it has been helpful.
