### ISSUE TITLE
Mobile iOS

### ISSUE THREAD

**Issue by meoz** [amark/gun#114]
Hi, is there somewhere an implementation/SDK for IOS ?

**Comment by amark** [comment]
hey @meoz ! Somebody was working on a Java port of gun for Android use... but he never finished it.

Currently, to use gun in a native app you have to use a webview and run it as regular javascript. Or if you are already using Ionic/PhoneGap/etc. it works just fine - but I assume this is not what you are looking for.

We're a small team, and would love to have somebody contribute iOS SDKs! I can help with everything needed to understand on how to implement it.

**Comment by amark** [comment]
I know people have used in gun with ionic/react/other-things now in native mobile apps. So porting to swift/Android specifically is probably not going to happen for a while. Gonna close this issue now, if there is demand for it please add a discussion for it here: https://github.com/gundb/feature-requests . Thanks!
