### ISSUE TITLE
Gun for Flutter/Dart?

### ISSUE THREAD

**Issue by Celpear** [amark/gun#1175]
Hello together,
Will there be a Gun.js package for Flutter/Dart in the future?
Currently, I only know of a way to run gun.js isolated as a web page in a HeadlessInAppWebView and query the data via evaluateJavascript. Can you think of a better way to use Gun.js with ios and android?

Thank you very much.

**Comment by BunnyTheLifeguard** [comment]
Haven't tried it yet, but maybe [this](https://pub.dev/packages/js) helps?

**Comment by amark** [comment]
👏  @BunnyTheLifeguard . @Celpear @frudas24 the upcoming Rust version (https://github.com/mmalmi/gun-rs-wasm) should allow you to integrate the binaries with Flutter/Dart and any other language, as a result Rust & JS are/will be the only officially supported versions, but lots of people in the community port GUN in 3 hours ~ 3 days (1 weekend) so maybe you're willing to help https://gun.eco/docs/Porting-GUN ? Elsewise, sorry :( . Closing!
