### ISSUE TITLE
How do I stop gun from writing to .radata file?

### ISSUE THREAD

**Issue by Shigetorum635** [amark/gun#1177]
I just began a project with Nuxt, but the auto-builder apparently detects .radata files and updates based on it. Problem is gun is constantly updating it for some reason, restarting my builder, making it impossible to test the application unless for production.

what can i do? I've tried ignoring the files with .nuxtignore but it does nothing!

![image](https://user-images.githubusercontent.com/48862659/146656257-5e296b41-03ea-4e23-9861-b974c076cb1a.png)
![image](https://user-images.githubusercontent.com/48862659/146656271-271e4548-6682-427f-915b-7daf74098e18.png)

```js
  const gun = require('gun')({
    web: "web",
    peers:['localhost:8080'],
    radisk: false
  })
  ```
  On index.vue

**Comment by rococtz** [comment]
You can try placing the `radata` directory somewhere else:
`var gun = Gun({ file: 'db/data.json' })`

**Comment by amark** [comment]
😆 oh gosh, that must have been annoying. Sorry. Odd `radisk: false` didn't work, 👏  @rococtz idea. I assume this closes this. Reopen if not! Cheers.

**Comment by Shigetorum635** [comment]
Ah! It's alright. I believe it was also because I was running my website in SSR Mode so gun probably thought this was a server. I'll try again soon. Thanks for the amazing work @amark 👏
