### ISSUE TITLE
How to have a gun relay server

### ISSUE THREAD

**Issue by volcareso** [amark/gun#1179]
Hi @amark just wanted know if there is any way we can make a relay server for gun

**Comment by Shigetorum635** [comment]
You can!
 ```js
const gunLib = require("gun")

const server = require('http').createServer().listen(8080);

const gun = gunLib({
    web: server
});
```
You just need to use this code! (It's all available in the documentation at https://gun.eco)

**Comment by Shigetorum635** [comment]
> You can!
> 
> ```js
> const gunLib = require("gun")
> 
> const server = require('http').createServer().listen(8080);
> 
> const gun = gunLib({
>    web: server
> });
> ```
> 
> You just need to use this code! (It's all available in the documentation at https://gun.eco)

There's also an official example
https://github.com/amark/gun/blob/master/examples/http.js

**Comment by volcareso** [comment]
Thanks a lot!!

**Comment by cheng-alvin** [comment]
Thanks legend! That worked for me as well!
