### ISSUE TITLE
[Question] How to make sure that the user does not modify this data 

### ISSUE THREAD

**Issue by Jourdelune** [amark/gun#1183]
Hello, I am new to gun and I would like to know how to do so that a user does not modify data, for example imagine that someone writes a text on a forum, to which the number of views is displayed, how could I do so that people do not modify the code to add or reduce the views?

**Comment by rococtz** [comment]
Short answer is that there are 2 ways:
1) User space - create an app user and use SEA.certify so the user can only edit his own views
2) Content Addressing - nobody can change this ever (which seems more suitable)

Long answer: you can probably write a book about how to do this the right way

**Comment by atordvairn** [comment]
@rococtz SEA.certify is a little confusing

I read the docs like 20 times and only half of code is working

**Comment by Jourdelune** [comment]
okay, thanks you fr your answers!
