### ISSUE TITLE
Sync Dexie table using Gun

### ISSUE THREAD

**Issue by shemeshg** [amark/gun#1190]
Created simple example for how to sync Dexie table to Gun.
It has no security considerations, but it seems to work fine, Hope it helps anyone to get started.

https://shemeshg.github.io/dexie-table-sync-gun/#/

It was surprisingly easy, I'v had no Replication Conflict issues 
(For example, in OrbitDb I had to manage changes for each user separately [Like lamport clock addition to what OrbitDb provides)
I guess Gun uses some kind of AutoMerge.Js to do some magic in the background

**Comment by rococtz** [comment]
@shemeshg This doesn't sound like you have an issue. Would you mind closing this issue and post your message in the chat?

**Comment by shemeshgi** [comment]
Looks like the permissions is off, I have only "Comment" (No "Close Issue" white button to the left of it)
Can you click the "Close Issue" for me.

Thanks
Shemeshg
