### ISSUE TITLE
[Question] Is it possible to use react-native-mmkv with gunjs in react native?

### ISSUE THREAD

**Issue by madhav-madhusoodanan** [amark/gun#1194]
First off, thank you for building this awesome project. I've been using gun in my recent projects for the times I've needed decentralised storage

Okay so I am building a react native app and i am just curious if I could use [react-native-mmkv](https://github.com/mrousavy/react-native-mmkv) for it.

The docs say:
```
Also, you can pass any storage plugin to the Store that implements the AsyncStorage setItem/getItem API.
```
[Edit]: Should I add a getitem()/setItem() manually to the MMKV instance?

Can someone be kind enough to clarify? Thank you in advance

**Comment by amark** [comment]
Not an RN person, but my assumption is (???) `AsyncStorage.getItem(key, cb)` and `.setItem(key, data, cb)` so guessing you'd do something like (pseudo) `myWrapper = {setItem: function(key, data, cb){ mmkv.write(key, data); cb(err, 1) } ...` no?

Please please please add whatever you cook up to the https://github.com/amark/gun/wiki/React-Native docs !

**Comment by amark** [comment]
@3210jr 👏 🔥 👏 🔥 .

Mind submitting this as like a `lib/rmmkv.js` meanwhile? Then update https://github.com/amark/gun/wiki/React-Native please.

@madhav-madhusoodanan closing!
