### ISSUE TITLE
Authentication and authorization with Gun.js the tradicional way?

### ISSUE THREAD

**Issue by edardev** [amark/gun#1197]
How to authenticate and RBAC with Gun.js the tradicional way with Social logins(Google, LinkedIn) or AWS cognito, Auth0, OAuth2.0, or or my own RBAC server, etc?

**Comment by edardev** [comment]
All I want is a decentralize database but I want control over the users and permissions models to restrict user's malicious behaviors.

**Comment by amark** [comment]
Ah! I saw you asked on StackOverflow... I haven't had time much to answer Qs there, but:

https://stackoverflow.com/questions/70921211/authentication-and-authorization-with-gun-js-the-tradicional-way-with-social-log/70962196#70962196

Having "control over users" but wanting to be "decentralized" is not something we plan on supporting, but you could build it yourself if you want. May be hard to find others in the community tho.

**Comment by edardev** [comment]
I am creating an app for a private family farm and the agricultural sector, in fact it is not intended for the general public. I like the idea that the data is distributed within the white list of allowed of peers, clients(employees) , at least for real-time messages feature, so we can save space and bandwidth.

I am not sure if I go should from scratch WebRTC implementation or take advantage of the Graph database provided in the Gun library.

Thank you so much @amark you are helpful, talented, gifted programmer and mathematician. I wish could understand more, working hard over the documentation, hopefully I will figure it out 🙏
