### ISSUE TITLE
Dramatic path performance decrease in last release

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#120]
#### Update: `path` is the culprit.

After troubleshooting some performance issues I was having, I found that `put()` is significantly slower than it was in the last release. On each `put`, the speed for the next operation is slower.
Here are some numbers.

`.path('example').put('string')`
Last version: (0.2.4)
500 puts, `0.423 seconds`
try again, `0.385 seconds`

Current version: (0.2.5)
500 puts, `21.032 seconds`
try again, `61.602 seconds`

That's basically **105 times slower**, increasing with each operation. In Trace, with enough history entries, the game can become unresponsive.

**Comment by amark** [comment]
Yi yi yiiipes! Ouch this is bad. What happens if you do this test without any paths? I want to see if my put code is itself worse or if path is effecting the put.

**Comment by PsychoLlama** [comment]
Hmmm, well it seems as though it actually was the path all along...
If I substitute it with
```javascript
.put({
  example: 'string'
})
```
then the performance is basically 1:1 with 0.2.4
Good catch!

**Comment by amark** [comment]
Good. This is very important! Thank you for the find. Let's go over it tomorrow.

**Comment by PsychoLlama** [comment]
@amark It's a deal!

**Comment by amark** [comment]
looks like it is probably recursion of put using path and path no longer stopping itself with "once" (which is necessary to fix the other bug you found).

**Comment by PsychoLlama** [comment]
Here is the code I used to test the performance:

```javascript
var gun = Gun().get('bug').set();
gun.path('example').put('string to be replaced');

function put(num) {
  var now = new Date().getTime();
  var cb;
  for (var i = 1; i <= num; i++) {
    if (i === num) {
      cb = function () {
        console.log(new Date().getTime() - now);
      }
    }
    gun.put({
      deeply: {
        nested: {
          object: new Date().getTime()
        }
      }
    }, cb);
  }
  return new Date().getTime() - now;
}
```

**Comment by metasean** [comment]
resolved via https://github.com/amark/gun/commit/16511d2e6b7c8db757fc811ca9a6714cab60a5b6 (version 0.3.0)
