### ISSUE TITLE
A big suggestion for the future development of gun.js

### ISSUE THREAD

**Issue by yingshaoxo** [amark/gun#1211]
# Use `ipfs` as the base for everything.

If you look at `orbitdb`, you see that they are using `ipfs` as the base for everything, so it could be a total decentralized solution:

```javascript
  const ipfs = await IPFS.create()
  const orbitdb = await OrbitDB.createInstance(ipfs)
```

https://github.com/orbitdb/orbit-db#module-with-ipfs-instance

____

I say this because `orbit` has a bad part, which is it doesn't have an account system while gun.js has.

**Comment by amark** [comment]
IPFS too slow, and GUN is already p2p and lets you rebuild your own IPFS in a few lines of code: https://gun.eco/docs/Content-Addressing
