### ISSUE TITLE
Putting regex creates a key

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#122]
Gun won't save regular expressions (which is good), but it will create a key when you pass one in.
```javascript
var gun = Gun().get('test').set()
gun.path('regex').put(/expression/)
gun.val()
// => { _: Object, regex: Object } 
```
The regex isn't actually saved, but a key is created referencing a relation. If we look at how Infinity or NaN is handled, the key is never created, as though gun never saw the data (and for invalid values, and that makes sense here). Here's the minimum amount of code to create the issue:

```javascript
Gun().get('test').set(/expression/)
```

**Comment by metasean** [comment]
Fixed with [put regex](https://github.com/amark/gun/blob/59f20c2cbd38bddb38249f09e390f12065c62343/test/common.js#L1100-L1105)
