### ISSUE TITLE
Run without needing user authentication/accounts (no passwords or encryption of data)

### ISSUE THREAD

**Issue by Osiris-Team** [amark/gun#1227]
It looks like GUN requires users to create accounts to be able to share data.
Is there a way of bypassing this? I'm asking because my application doesn't store sensitive data and everyone should be able to access every data, and I don't want to have an extra step for user registration.

I was thinking maybe by using the users IP as username for example and then a random generated string of chars as password, which gets stored in the browser somewhere?
Or is it possible to create one single user that everyone logs in to. That would mean that all data is by default being updated for everyone which isn't great.

**Comment by atordvairn** [comment]
assuming that you need a node everyone can access and write to:

- ```gun.get("public__node").get("key").put("value")```

[public space, user space, frozen space](https://gun.eco/docs/#data) is all well documented 

also, [the chat](https://chat.gun.eco/) is the fastest method to ask questions.

**Comment by Osiris-Team** [comment]
So adding `public___` makes it a public node? Also, the doc ur linking to doesn't show code examples on how to achieve those.
Thanks for the help btw! (the chat is down)

**Comment by atordvairn** [comment]
> So adding public___ makes it a public node?

no no no, basically _any_ node is a public

exept  user controlled nodes are like
``` javascript
gun.user().get("myOwnNode").get("key").put("val")
```

**Comment by atordvairn** [comment]
idk why the chat url is down 
it basically redirects to this one
[https://gitter.im/amark/gun](https://gitter.im/amark/gun)

**Comment by Osiris-Team** [comment]
Ok got it. What about this:

> I was thinking maybe by using the users IP as username for example and then a random generated string of chars as password, which gets stored in the browser somewhere?
Or is it possible to create one single user that everyone logs in to. That would mean that all data is by default being updated for everyone which isn't great.

**Comment by atordvairn** [comment]
> Or is it possible to create one single user that everyone logs in to.

why would you do that. 
what's the use case

**Comment by Osiris-Team** [comment]
the use case is that I dont want to have an extra step for my user to register.

**Comment by atordvairn** [comment]
use [`SEA.pair`](https://gun.eco/docs/SEA#pair) maybe

``` javascript
var user1 = await SEA.pair();
gun.user().auth(user1, ()=>{
  //logged in without creds
})
```

**Comment by Osiris-Team** [comment]
Ok great thx for the help!

**Comment by atordvairn** [comment]
> my application doesn't store sensitive data and everyone should be able to access every data, and I don't want to have an extra step for user registration.

bro why not just store data in public nodes then, you dont need registration to store data into public nodes

if you want to append only data then use frozen storage
