### ISSUE TITLE
Inconsistent invocation of callbacks for bad values

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#123]
When passing in bad values to `.set` or `.put`, sometimes the callbacks are invoked, and sometimes they aren't. For example:
```javascript
Gun().get('test').set(NaN, function () {
  console.log(arguments)
})
// the function is never called
```
But if you pass in Infinity instead, the callback *will* fire, passing in an error object with the message `"Invalid value at [soul]!"`. But it doesn't stop there! There's even inconsistency between `.set` and `.put` (even though `.set` uses `.put` under the hood).
```javascript
Gun().get('test').path('callback madness').set(Infinity, callback)
// invoked, error given. Let's try put this time...
Gun().get('test').path('callback madness').put(Infinity, callback)
// not invoked, no error! What?
```
These errors might be the last string of sanity that beginners have, since gun doesn't throw traditional errors.

**Comment by metasean** [comment]
Fixed per ['put Nan', 'put date', & 'put regex' tests](https://github.com/amark/gun/blob/59f20c2cbd38bddb38249f09e390f12065c62343/test/common.js#L1100-L1105)
