### ISSUE TITLE
"Unverified data." from .certify()

### ISSUE THREAD

**Issue by fitouch** [amark/gun#1250]
`var room = await SEA.pair();
var certificate = await SEA.certify(gun.user().is.pub, {"#": {"*": "chat"}}, room);
gun.user(room.pub).get('chat').get(new Date().getTime()).put('hello world', null, {opt: {cert: certificate }});`

return "Unverified data."

**Comment by zilveer** [comment]
@fitouch why did you close and mark this as completed? 
Was the problem solved?

Regards
