### ISSUE TITLE
Question: Can you use GunJS with indexedDB on the client side ?

### ISSUE THREAD

**Issue by Codzaa** [amark/gun#1283]
For Example:
 For a simple chat app can each user's information/chats/posts be stored in IndexeDB ? 

If so is there an example or detailed explanation I can read.

Thank you.

**Comment by draeder** [comment]
You can use IndexedDB. I do not have a link to an example, however. I'm sure there's something in chat: https://chat.gun.eco, or you could ask there.

**Comment by amark** [comment]
@Codzaa yes https://gun.eco/docs/RAD#install tho warning: since the new version (last year) RAD hasn't been thoroughly testedand it is getting a huge overhaul with Book underneath, so many of these pieces may go thru breaking API changes over the next year.
