### ISSUE TITLE
user.auth() has stopped working

### ISSUE THREAD

**Issue by BrendanDN** [amark/gun#1290]
I can create a user because I can see the user in LocalStorage, but when I try to auth() it dose not sign the user in.

**Comment by yuetloo** [comment]
We also noticed `user.auth()` gives `wrong username or password` error but one user was able to login magically later but other would get stuck at `wrong username or password`.

Sometimes `user.auth()` would give `User is already being created or authenticated!` and users were able to login later (this case is probably expected but we think this is new behavior as we had not seen this behaviour prevously).

Also, would like to understand why does this line of code always return?
https://github.com/amark/gun/blob/master/gun.js#L374
```
   if(state < was){ /*old;*/ if(true || !ctx.miss){ return } } 
```

**Comment by BrendanDN** [comment]
It turns out it was a problem on my side, for some reason using an HTML form broke user.auth() so I just removed the form stages and kept the input.
