### ISSUE TITLE
auth event not triggered

### ISSUE THREAD

**Issue by pwFoo** [amark/gun#1300]
Hi,
I used `gun.on('auth', cb)` to execute code if user is logged in. Updated to current gun.js / sea.js files from repo and event isn't triggered anymore!
Something changed with that event or a bug?

**Comment by amark** [comment]
You sure? I just checked with this basic login app https://github.com/amark/gun/blob/master/examples/basic/post.html and it is triggering. Help show how to replicate? Thanks!
