### ISSUE TITLE
Remove offline gun volunteer relays

### ISSUE THREAD

**Issue by atjn** [amark/gun#1305]
I have been testing my app on the volunteer servers for the past week. Most of them have been permanently down the whole week, and since they seem to be Heroku servers, I'd guess they are never coming back.

### The list of working volunteers:
* https://gun-manhattan.herokuapp.com/gun
* https://relay.129.153.59.37.nip.io/gun
* https://relay.peer.ooo/gun
* https://peer.wallie.io/gun

### The list of offline volunteers
* http://gun-matrix.herokuapp.com/gun
* https://shockblox-gun-server.herokuapp.com/gun
* https://mg-gun-manhattan.herokuapp.com/gun
* https://gunmeetingserver.herokuapp.com/gun
* https://gunjs.herokuapp.com/gun
* https://myriad-gundb-relay-peer.herokuapp.com/gun
* https://gun-armitro.herokuapp.com/
* https://fire-gun.herokuapp.com/gun
* https://gun-sashimi.herokuapp.com/gun
* https://gun-ams1.cl0vr.co:443/gun

I want to remove these from the volunteer list, but since I have not really been involved in managing this list before, I wanted to ask for your feedback first. Is it okay to remove these servers?

Maybe an exception should be made for `https://gun-ams1.cl0vr.co/gun`, since it is not obviously a Heroku deployment?

Tagging most recent list editors: @wayjake @cl0vrfi3ld @draeder

**Comment by cl0vrfi3ld** [comment]
Hey there! I run the `gun-ams1` relay. I haven't checked up on it recently, but I reckon it just ran out of credits. I'll look into it soon. 

As for the rest, I think having some sort of GH action/bot to periodically clean up these entries would be pretty nice. It should post an issue of some sorts warning folks about the deletions, though, just in case anyone needs to double check their deployments.

**Comment by atjn** [comment]
@cl0vrfi3ld haha I wasn't smart enough to connect the URL with your name. A github bot would be really cool, but I don't know if it is wasted time to build one, given that AXE should automate this whole process very soon?

Anyways, while we wait for Github bot / Axe, would it be okay to remove the other URLS?

**Comment by atjn** [comment]
It seems @atom06 took this into their own hands. Then I guess there is no reason to debate it. Be aware that your relay is no longer on the list @cl0vrfi3ld .

**Comment by wayjake** [comment]
Thanks for the communication. Looks good! 

> It seems @atom06 took this into their own hands. Then I guess there is no reason to debate it.

READY FIRE AIM! :D

**Comment by atom06** [comment]
community service

**Comment by wayjake** [comment]
that's better than nothing 😂

**Comment by atom06** [comment]
maybe will look into make a bot @atjn

**Comment by atjn** [comment]
@atom06 if you want to build that, it would be very cool. Just know that [AXE](https://gun.eco/docs/AXE) is being developed right now, and theoretically, it eliminates the need for a volunteers list.

**Comment by atom06** [comment]
when, and until then we need something _"something is better than nothing"_

Plus another side project wont hurt
