### ISSUE TITLE
New issue, there are so many issues

### ISSUE THREAD

**Issue by wayjake** [amark/gun#1307]
Hello hello! 

I've been a Gunner for a [little over a year now](https://github.com/wayjake/Wallie.io/commits/master?after=6389bdf854f77667a506c77e482eb855258d71b6+69&branch=master&qualified_name=refs%2Fheads%2Fmaster). 

I'm in the Gitter, but I'm coming here to see if we can discuss (a) burning question(s) I have. 

1. why is Nostr getting so much love?
2. why did [Notabug.io](http://notabug.io/) die?
3. why are you here?

Some followup points is me trying to figure out some basic questions as **_to how Gun wants to work._** Does it work better as more nodes get connected? Sometimes it seems the consistency needs to "warm up" until it gets to the right state. I'm constantly posting stuff to **_Wallie that eventually drops of my self hosted node_**. Even though I'm writing to permission-less space and provide a shortcut via the UI to delete things, I still think things are getting dropped off prematurely. Though, it doesn't seem like [Iris](https://iris.to/) runs into this issue so I wonder if it's just a me thing. 

For example, _it's 9:30PT January 26th, 2023_ and there's no reason there shouldn't be 2 nodes available under [this namespace (dev.wallie.io)](https://dev.wallie.io/all). Yet eventually it appears the host node (https://peer.wallie.io/gun) will eventually stop dishing this content. 

Cheers to this team! 

<img src="https://media4.giphy.com/media/EoH4Wpu8suiNTLpI6j/giphy-downsized-medium.gif"/>

**Comment by disarticulate** [comment]
I am testing out this package for some distributed goodness.

I've reviewed the webrtc implementation and it appears to neglect data msg size. Check out this work: https://github.com/yjs/y-webrtc/issues/20


There's a long standing issue with silent data passing failures.  I do not see buffering implemented in the webrtc library so if you're relying on that, it'll likely fail when the CRDT updates get to big


Yjs used a simplepeer implementation so it was easy to redo the data buffering.

**Comment by amark** [comment]
Many people suspect go1dfish died 2.5 years ago, he was the anonymous founder of notabug. So its possible his static/dns/etc. billing finally failed.

One of the earliest nostr contributors told me it was inspired by GUN's relays, idk if that is true. Sadly, it has become a target of Jack Dorsey's latest attempts at "doing good" and causing destructive drama/problems to dweb projects (bluesky, tbd, web5, ... dead dead dead). It has no DHT mechanism, which will make it very hard to scale (I had the same problems with gun, so they'll need something like AXE / their own, eventually).

The peer you listed is running `...1238` which has a known bug in AXE that broke multi-property sync accidentally, thus "warm up". Please try upgrading to `1239` and see if that fixes it?

If that does not fix it, please reopen.

**Comment by wayjake** [comment]
> I am testing out this package for some distributed goodness.

awesome! 

> There's a long standing issue with silent data passing failures. I do not see buffering implemented in the webrtc library so if you're relying on that, it'll likely fail when the CRDT updates get to big

i don't see a lot of support for WebRtc yet. It seemed to be mostly a WIP until the plugin system is overhauled. 

> Yjs used a simplepeer implementation so it was easy to redo the data buffering.

So you re-implemented this kind of syncing outside of Gun?

**Comment by wayjake** [comment]
> (bluesky, tbd, web5, ... dead dead dead)

i am really confused where web5 came about? do we have some X-Box/Microsoft naming conventions going on in the defi stratosphere or what???

> The peer you listed is running `...1238` which has a known bug in AXE that broke multi-property sync accidentally, thus "warm up". Please try upgrading to `1239` and see if that fixes it?

Will do, thank you! Bonne journée.

**Comment by disarticulate** [comment]
If you review the issue above, I patched simplepeer to do packet buffering.
It's never been merged but at least two yjs users ran into it.  It's
browser "bug" that's never been fixed.


If id hazard a why in some webrtc uptake, it's stuff like that.  Anyone who
wants to use the data part of webrtc will find that bug if they aren't
chunking their data messages.

**Comment by amark** [comment]
@disarticulate your patch sounds useful, mind sending link to the code that does the buffering? Dechunking should be done here https://github.com/amark/gun/blob/master/lib/webrtc.js#L83 , and we'd need to overload `send` for chunking.

**Comment by disarticulate** [comment]
It's. A monkey patch on peerjs

https://github.com/disarticulate/y-webrtc/blob/master/src/SimplePeerExtended.js

**Comment by wayjake** [comment]
> It's. A monkey patch on peerjs

I am so confused why WebRtc doesn't have a really well done library/wrapper 🧐 

Don't get me wrong peerjs is good it was just a confusing journey looking through a lot the same exact code regurgitating itself in Google search results only to find out there was a better way. Sometimes I think Google does more harm than good 🤷🏼

**Comment by wayjake** [comment]
> and we'd need to overload `send` for chunking.

I think the overloading is what makes plugging in difficultly. i don't think there are any options for the short term but hopefully I can be a part of the process of reconfiguring some things when the time comes. The least I can do is draw maps and diagrams lol.
