### ISSUE TITLE
Subscribe to updates and get only changes is not working

### ISSUE THREAD

**Issue by ViniciusFXavier** [amark/gun#1313]
I have been trying to use the `{ change: true }` option in the [`gun.on(callback, option)`](https://gun.eco/docs/API#-a-name-on-a-gun-on-callback-option-) function to receive only the field that was changed. However, it doesn't seem to be working as expected.

I used the following example code:
```js
var gun = GUN();

gun.get('mark').put({
  name: "Mark",
  email: "mark@gun.eco"
});

gun.get('mark').on((data, key) => {
  console.log("realtime updates:", data);
}, { change: true });

setInterval(() => {
  gun.get('mark').get('live').put(Math.random())
}, 9);
```
Playground: https://jsbin.com/hirerow/2/edit?js,console

![image](https://user-images.githubusercontent.com/40774281/227434019-33ca9553-e38c-40d6-b1fb-a23b67070061.png)

According to the [Gun.js documentation](https://gun.eco/docs/API#-a-name-on-a-gun-on-callback-option-), the `{ change: true }` option should return only the field that was changed. However, in the example above, the real-time updates show the entire object, instead of only the live field that was changed.

I also tried using the `{ change: false }` option, but it had the same behavior as using `{ change: true }`, showing the entire object in the updates.

I believe this is a bug in the `gun.on()` function, as the documentation clearly states that the `{ change: true }` option should work as described.
![image](https://user-images.githubusercontent.com/40774281/227433474-0e32d3a1-60de-4115-8154-9ed8404c5546.png)
Source: https://gun.eco/docs/API#-a-name-on-a-gun-on-callback-option-

**Comment by draeder** [comment]
You are listening to the entire 'mark' graph, but not listening on the 'live' subgraph.

Note: a field is an attribute of an object like
```js
{
  field1:'something',
  field2:'something else'
}
```
which is contained in the graph/subgraph.

Then something like this should work
```js
gun.get('mark').get('live').on((data, key) => {
  console.log("realtime updates:", data.field1);
}, { change: true });
```
if you set `field1` to change on an interval.
