### ISSUE TITLE
Bad ref returned from .path

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#132]
It's easy to imagine a scenario when you'd want to hold a path context in a variable. Here's an example.

``` javascript
var users = Gun().get('examplses').set().path('users').set()
users.set('bob')
users.set('dave')
```

We'd expect the user object to interface exactly like a fresh gun instance. However, when calling `users.val()`, the relation is logged, instead of the node.

**Comment by PsychoLlama** [comment]
Here's a detailed example of this behavior:
```javascript
var users = Gun().get('example').set().path('users')
users.set('bob')
users.set('sam')
/*
users.val()
Prints out the relation and it's property name
It should instead print out the users collection
{ #: "MDereLXy0Z8KzcoTNr0tMUh6" } users

Gun().get('example').val()
Prints out the graph containing the users object
{ _: Object, users: Object }

Gun().get({ '#': usersSoul }).val()
Prints out everything in the users collection
{ _: Object, I1451938109227RLUCz8: "bob", I1451938115037RmhQJu: "sam" }
As we can see, the users were persisted.
*/
```

The main problem is when we get the value, it returns the relation of the parent. Put operations are successful.

**Comment by metasean** [comment]
Changelog?

**Comment by amark** [comment]
revamped in v0.5+ (current release is 0.6), so gonna close it as "fixed" unless it magically pops up again (it did a couple times, but then I fixed it).
