### ISSUE TITLE
[Docs] where is "Gun.chain" documented?

### ISSUE THREAD

**Issue by rozek** [amark/gun#1321]
The docs have a [section](https://gun.eco/docs/Counter) which tries to explain how to implement CRDT on top of Gun. Neglecting the fact that I do not understand the example,

**where is `Gun.chain` documented?**

It seems to be the core of that example, but I can't find it in the reference....

**Comment by draeder** [comment]
Gun chain documentation is located [here](https://gun.eco/docs/Adding-Methods-to-the-Gun-Chain).

**Comment by rozek** [comment]
great! thank you very much!
