### ISSUE TITLE
[Docs] are really difficult to use!

### ISSUE THREAD

**Issue by rozek** [amark/gun#1322]
Well, although I like having docs, I really hate the way the [official docs](https://gun.eco/docs/API) were implemented:

* white on black only (while some people find "dark mode" cool, white on black is much more difficult to read than black on white)
* no scrollbars (really? it's such a pain to always have to use the scroll wheel)
* one large page with animated scrolling (well, animation may be a matter of taste - but after clicking an item in the TOC my browser almost always scrolls to a position which does not show the clicked section and I still have to scroll manually - but, oh, there are no scroll bars and, oh, the display style makes it difficult to find where the desired section starts...)

Is there an alternative document for Gun? or can I configure white mode, add scrollbars, change some styles?

**Comment by rozek** [comment]
not yet, but I will do now - thank you very much for the hint!

**Comment by amark** [comment]
@nvigier-menlo 🔥 ❤️ 

🚀 🚀 yes please help!!!

**Comment by rozek** [comment]
well, I've started jotting my own notes since I'm still on the learning path and should definitely not damage wiki contents by adding stuff that's _wrong_!
