### ISSUE TITLE
[Doc] user example is wrong?

### ISSUE THREAD

**Issue by rozek** [amark/gun#1324]
I just tried to work with Gun users - and failed immediately.

According to the [docs](https://gun.eco/docs/User) I should start with

```
gun = new Gun();
user = gun.user(); 
```

but the second line fails with `gun.user is not a function`. `Gun` seems to be a (constructor) function and its instance `gun` does not have any `user` field - not even in its prototype chain.

So, how do I manage users?

**Comment by rozek** [comment]
what I found out: before calling `gun.user()`

```
<script src="https://cdn.jsdelivr.net/npm/gun/sea.js"></script>
```

is needed in order to load SEA support (which seems to modify the GUN constructor). I found it in another part of the docs, but not in the section mentioned yesterday.

Could you please update the example accordingly?

Thank you very much in advance for your effort!

**Comment by amark** [comment]
all docs are wiki pulled from here https://github.com/amark/gun/wiki please please please help out and improve it! Thank yout hank you thank you
