### ISSUE TITLE
[Doc] how can one write encrypted data?

### ISSUE THREAD

**Issue by rozek** [amark/gun#1327]
Now that I have found out how to write nodes which are bound to a specific user (but remain readable for all) the question arises how to write private data?

The [docs](https://gun.eco/docs/User#user-secret) do not explain this

**Comment by rozek** [comment]
ah, I found the [SEA Quickstart](https://gun.eco/docs/SEA) example which explains a lot

**Comment by amark** [comment]
yay! Feel free to make edits that make it better, please.
