### ISSUE TITLE
[Doc] is the SEA Quickstart example wrong?

### ISSUE THREAD

**Issue by rozek** [amark/gun#1328]
While most of the stuff mentioned in the example works out of the box (very well done!) I cannot send the message from Alice to Bob.

The last line in the example always fails with `{@: 'g4V8uyOMn', err: 'Certificate verification fail.', $: Gun, #: '7ktfz5Xb8', _: ƒ}`

I already tried to log Alice out and Bob in, but without success

**Comment by dj0024javia** [comment]
Alright, I was stuck on this for so long, but try to create SEA.pair() for each user, save it in a variable.
Run the code again with those values and it should work.

**Comment by amark** [comment]
@rozek @dj0024javia is this good now? Gonna assume so. Sorry for late reply (bad at tracking things). Please re-open if not - or better, just tweak the docs slightly (everything is editable via the GitHub wiki).
