### ISSUE TITLE
Why is the source code so bad?

### ISSUE THREAD

**Issue by risen228** [amark/gun#1341]
Maybe it will be better to rewrite everything to TypeScript and use better variable names instead of 1/2-letter and something like `cat`?

**Comment by bmatusiak** [comment]
most of the methods properties and function names are acronyms ( its saves space ) i.e.  ack = acknowledgement  ( we want to drive a civic, not a hummer, on the internet ).
typescript is not JavaScript.
and yes gun has been rewritten.. many many many,..... many.. times. ( you can find a typescript version i bet )

please don't take any offence. not defending. not enforcing.. just stating the arguments here.

**Comment by amark** [comment]
I'm a mathematician, so I prefer 1 letter variables (or as short as possible), it lets me hold more complexity in my head at once. Good / Bad is very relative, so I use performance benchmarks as the true judge of code quality. But feel free to use one of the TypeScript ports - https://gun.eco/docs/Porting-GUN .
