### ISSUE TITLE
Radix tree

### ISSUE THREAD

**Issue by metasean** [amark/gun#136]
Fix edge case ('parent/children', 'children' are searched but 'parent/' is not)

Integrate the fixed radix tree

**Comment by amark** [comment]
It still might be smart to have a radix implementation internal to gun for optimized range queries on large table nodes. So gonna leave this open for further discussion.

**Comment by amark** [comment]
Radix trie implemented! See `lib/radix` (although it might be moved to gun core at some point). It has not yet been integrated, but I'm gonna go ahead and close, because it may or may not be worth including it or not. But this is no longer a bug anymore.
