### ISSUE TITLE
Question: webseed functionality?

### ISSUE THREAD

**Issue by albert-tomanek** [amark/gun#1369]
Hello,
me and my friend are considering writing a web app and using GUN to store our data. Since we'll already be having a central server host our webpage, we were thinking it might also be good if it mirrored part of the data in case other readers' devices went offline (ie. webseed functionality). Does GUN currently support doing this? Are there any good resources you could point us to? Also, is there a way to scrape the whole database onto one computer, so that we can make backups?

Thanks!

**Comment by amark** [comment]
yes it does this. just subscribe to everything, maybe like `gun.get('yourAppRoot').map().on(cb)`
