### ISSUE TITLE
node-webcrypto-oss deprecated

### ISSUE THREAD

**Issue by gotjoshua** [amark/gun#1372]
confused about this `{directory: 'ossl'}`, whats the story with that?
https://github.com/amark/gun/blob/faff9efacabc0063d867ba8b8f92142e4238ff3b/sea/shim.js#L41
(i don't find a constructor anywhere in the inheritance chain that is interested in such an init object.

seems this ossl stuff is anyway rather deprecated
https://github.com/PeculiarVentures/node-webcrypto-ossl?tab=readme-ov-file#deprecated

**Comment by amark** [comment]
Hmm, line above does show we're using @peculiar/webcrypto so maybe this was just leftover for before when we had ossl? It did cause issues so we changed off it as soon as we could.

**Comment by gotjoshua** [comment]
Yeah maybe leftovers of some sort... I guess you are using peculiar for the polyfill to nodejs. However, the names of the variables don't match how they are used, so I got pretty confused when trying to understand what you are actually doing in the encryption department.

Encryption is such a subtle endeavor, it's always helpful to be as explicit and verbose as possible. 

Sorry I didn't grok what you are doing deeply enough to offer a PR, but thought this heads up is the least I can do.

**Comment by amark** [comment]
@gotjoshua no worries, if you want to fix/update the naming, go for it!

Closing.
