### ISSUE TITLE
"gun.user() is not a function" due to SEA not loading properly

### ISSUE THREAD

**Issue by CreaDisc** [amark/gun#1383]
Hi folks,

currently I am trying to use gun for a Lit-based project. Whenever I try to call `gun.user()` it gives me the error:
`TypeError: gun.user is not a function`

Here is the relevant parts of the project:
- gun npm package version:  "0.2020.1240"
- my components are bundled as an IIFE in rollup

this is my bundle entry point:
```js
import Gun, {IGunInstance, IGunUserInstance} from 'gun';
import SEA from 'gun/sea';

// ...
document.addEventListener('DOMContentLoaded', () => {
  loadGun().then(() => {
    //...
  });
}
```

gun auth module:
```js
import {IGunInstance} from 'gun';
import 'gun/sea';

export async function loadGun() {
    // ...
    const gun = Gun();
    await checkAndCreateUser(gun, 'username', 'password');

    console.log('Gun loaded');
}

async function checkAndCreateUser(
  gun: IGunInstance,
  username: string,
  password: string
) {
  return new Promise<void>((resolve, reject) => {
    const user = gun.user();                                     // !!! THIS IS WHERE IT FAILS

    console.log('user assigned');
    user.auth(username, password, (ack: any) => {
      //...
    });
  });
}
```

This is how I included the scripts in my HTML:
```html
<script src="../node_modules/gun/gun.js"></script>
<script src="../node_modules/gun/sea.js"></script>

<script src="../out/bundle.js"></script>
```

What I tried so far:
- rechecking if `window.SEA` is defined every 100ms --> no success

I have seen this issue come up before but none of the solutions worked for me, so here I am.

**Comment by CreaDisc** [comment]
Ok, so I created a github issue but somehow it works now 🥳 Still trying to figure out why. If I import SEA into my bundle at the entry point, everything seems fine. But as soon as I try to import SEA from a Lit component, it breaks.

So this is my Lit component:
```js
@customElement('task-component')
export class TaskComponent extends LitElement {

  private todoRepo: TodoRepo | null;

  constructor() {
    super();
    this.todoRepo = getTodoRepo();
  }

  // ...
}
```

And this is my Todo Repo module:
```js
import * as Gun from 'gun';
// import 'gun/sea';                                 // !!! Including this somehow seems to break SEA
import 'gun/axe';

export function getTodoRepo(): TodoRepo | null {
  if (!window.gun) {
    console.log('gun is undefined');
    return null;
  } else {
    console.log("gun is defined in TODO Repo");
    return TodoRepo.getInstance();
  }
}

// ...
```

**Comment by amark** [comment]
`const gun =` in a different local scope. I have no clue what `gun: IGunInst...` is because every 6 months GUN works perfectly fine with TypeScript and then suddenly TypeScript changes and breaks everything and some kid has to re-implement TypeScript+GUN integrations and rewrite all the tutorials.

Try this:

`window.gun = GUN(); console.log(1, gun);` near top of your code to force it, then `gun.user()` anywhere else.

If it works like that, then things are fine and means scoping issue in your code. If it doesn't work like that, please reopen!

**Comment by gmreburn** [comment]
I had this same issue caused by webpack's tree shaking. To test, I created this:

```ts
// Doesn't work:
import Gun from "gun";
import SEA from "gun/sea";

console.log("Access gun.user()...", gun.user);
# Output: "Access gun.user..." undefined
```

```ts
// Works: import and reference SEA in console.log
import Gun from "gun";
import SEA from "gun/sea";

console.log("Access gun.user()...", SEA.err, gun.user);
# Output: Creating user... undefined function user(pub)
```

If you remove SEA import and/or SEA.err webpack will remove this dependency and you won't have access to gun.user().
