### ISSUE TITLE
Arrow function compatibility for .map, .val, etc.

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#144]
As ES6 is fast approaching and gains wider adoption, arrow functions are becoming more ubiquitous. Since gun uses `.call` and `.apply` to relay a gun instance, arrow functions don't have access to gun itself.

``` javascript
// this === window === true
gun.map((value, key) => {
  // this === window === true
})
```

Most callbacks follow the pattern of `(value, key)`, so we could pass in the gun instance as the third parameter without changing existing behavior, giving the users more expressive power (and syntactic sugar).

``` javascript
gun.map((value, key, gun) => {
  // stuff
})
```

Thoughts?

**Comment by PsychoLlama** [comment]
By adding the third gun instance, as a side effect it would better model the Array.prototype methods, where the array in question is passed as the third argument.

**Comment by amark** [comment]
In the newest version `on` does this, but `val` doesn't for performance reasons. Possible with `map` too now that it actually works like a map function. So gonna close!
