### ISSUE TITLE
Maximum Callstack Exceeded in choking loops

### ISSUE THREAD

**Issue by metasean** [amark/gun#145]
Related to #95, if running gun.path('surveys').map().path('q').put(null) through many iterations (e.g. 10,000) time bogs down the system until it locks up.

**Comment by metasean** [comment]
This is caused by `while` loops, need to update documentation to warn users about potential problems.

**Comment by amark** [comment]
Finally can do 25M+ ops/sec and we have PTSD tests for this! Woohoo, so I'm finally going to close this. The whole last year was basically dedicated to fixing perf problems like this.
