### ISSUE TITLE
Path performace slowdown

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#146]
If we generate a bunch of paths (which `.map` currently does because it doesn't reuse it's paths) we see linear slowdown of execution in the trace demo game.

Note: I notice you've got comments in `.map` saying it's not done yet. Perhaps if we reuse those path references, we'll see better performance? LOC 315

I'll follow up soon with a test demonstrating the slowdown.

**Comment by PsychoLlama** [comment]
```javascript
gun.path([0, 'history']).map(function (entry, index) {
  console.log(entry)
});

var turns = 0;

setInterval(function () {
  gun.path([0, 'history', turns += 1]).put({
    x: 1,
    y: 1,
    axis: 'y',
    direction: 1,
    time: Gun.time.now()
  });
}, 25);
```

**Comment by metasean** [comment]
Partially fixed with https://github.com/amark/gun/blob/master/test/common.js#L2212-L2296

**Comment by amark** [comment]
Last years worth of effort has fixed (with PTSD tests!) the majority of these performance slowdowns in the API. Chains are cached and reused a TON now. So I'm proud to be able to close this issue after so long!
