### ISSUE TITLE
Gun refs nested in placed objects

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#162]
Thanks to gun `v0.3.3`, we can put nodes into gun by it's gun reference:
```javascript
var msg = Gun().put({ text: 'Hello world!' })
Gun().get('messages').set(msg)
```
However, when you nest references within an object, `.put` breaks down:
```javascript
var sender = Gun().put({ name: 'Tom' })
var msg = Gun().put({
  text: 'Hello world!',
  sender: sender // this will fail
})
// however
msg.path('sender').put(sender) // this will succeed
```
Intuitively, it seems like this should work (not just that but it would be amazingly cool).

**Comment by amark** [comment]
Yeah, I intentionally chose not to support that yet at this point. We probably will but I don't want to promise.

**Comment by PsychoLlama** [comment]
Makes sense, it's hard to take back what we add, but we can certainly add cool features later. I'll close this for now...

**Comment by metasean** [comment]
Went ahead and listed it as "Unexpected Behavior" in the API - https://github.com/amark/gun/wiki/API-(v0.3.x)#unexpected-behavior
