### ISSUE TITLE
gun.on(cb,true) fires on updates without change

### ISSUE THREAD

**Issue by thoka** [amark/gun#166]
gun.on(cb,true) fires, if a property is updated with the same value (so only the timestamp gets updated)

Note this in the docs, if this is the desired behaviour.
Think about an option to be notified on value changes only.

**Comment by amark** [comment]
@thoka thanks, yes this intentional, and yeah we should probably add this as a note. @PsychoLlama or @metasean ?

@thoka I pinged you on Wednesday when you said you were available. When next would be best?

**Comment by metasean** [comment]
Note added to documentation - https://github.com/amark/gun/wiki/API-(v0.3.x)#unexpected-behavior-2

**Comment by amark** [comment]
@thoka how are you doing!? Hope you are doing well. Closing this issue as it was resolved a long time ago. :)
