### ISSUE TITLE
Deep async changes not updating

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#167]
When asynchronously updating deeply nested data in gun, the updates won't propagate, and nothing will get the new data (including the underlying data stores).

It's an oddly specific bug, though...
- updates must be at nested at least three layers deep, or gun will notice
- it must be asynchronous, or else gun will get the update

Here's something that could be adapted to a jasmine/mocha test case:

``` javascript
// object nested three layers deep
// must be at least three layers
var obj = { 1: { 1: { data: false } } }

// define gun and place the deep object
gun = Gun().get('deep change').put(obj)

// listen for changes
gun.path('1.1.data').on(function (data) {
  if (data) {
    // gun will never receive the "true" update
  }
})

// asynchronously set data
// synchronous deviations will succeed
setTimeout(function () {
  obj[1][1].data = true
  gun.put(obj)
}, 50)
```

**Comment by amark** [comment]
WOOOHOOO fixed: http://jsbin.com/gijaxeqana/edit?js,console with all the latest 0.5+ (now on 0.6) major improvements. Closing. :D
