### ISSUE TITLE
option to not save and share duplicate data when it's `.put()`

### ISSUE THREAD

**Issue by metasean** [amark/gun#171]
The default behavior for `.put()` is to save and broadcast every single `.put()`.  

There are occasions when the data being sent to `.put()` is identical to the existing data (e.g. GPS coordinates), which results in many, nearly duplicated entries and broadcasts (the only difference is the node's state).  

Therefore, for performance and storage reasons, developer's *may* prefer to *only* save and send *modified* data. 

Such functionality *could* reek havoc on systems where multiple people are saving data and may loose connectivity.  Therefore, for safety of data and conflict resolution, such functionality should be opt in.

**Comment by thoka** [comment]
In addition to true / false a function could be supplied, which would be called with the original and changed values and emits true / false or some measure of the priority of the update.

**Comment by amark** [comment]
Hmmmm, this really sounds like dangerous territory in core. GUN is suppose to guarantee eventual consistency, the integrity of the data. I strongly think that if a developer wants to deduplicate writes they should check for that themselves BEFORE saving data to the database.

If anything though, in the upcoming `v0.4.x` and `v0.5.x` there is a stream interface which allows you to quite nicely tap into outgoing `put`s and cancel them. So this would allow for this type of behavior, but without its dangers being added to core.

**Comment by amark** [comment]
@thoka thanks for your thoughts though.

I'm actually going to close this issue, and label it as a 0.5.x milestone for the ^ behavior (not in core).
