### ISSUE TITLE
Linked lists fail 3 layers deep

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#186]
When creating a linked list (one where each item in a list provides a pointer to the next), you need to populate the entire list using one parent object or anything more than 3 layers deep won't stick. That's pretty sad for a list :disappointed:

**This works:**

``` javascript
var list = gun.put({
    depth: 1,
    next: {
        depth: 2,
        next: {
            depth: 3
        }
    }
});
list.path('next.next').val(function (data) {
    console.log('Data! Yay!', data);
});
```

**This does not:**

``` javascript
var list = gun.put({
    depth: 1,
    next: {
        depth: 2
    }
});
list.path('next').put({
    next: {
        depth: 3
    }
});
list.path('next.next').val(function (data) {
    console.log('Never called :frown:');
});
```

It's an odd behavior, since this only happens when appending items to a list. If you load it all in at once, it works, but "pushing" a new item won't ever resolve. If you save a reference directly to the object, nothing will ever resolve on that, either...

``` javascript
var value = list.path('next.next').put({
    data: true
});
value.not(function () {
    console.log('This never fires');
});
value.val(function () {
    console.log('This never fires');
});
```

Since a linked list is one of the few ways to provide strongly ordered data, I think this is rather important.

**Test case**

``` javascript
describe('Linked lists', function () {
    var list = gun.get('list');

    it('should allow more than 2 items depthwise', function (done) {
        // create a list two layers deep
        list.put({
            depth: 1,
            next: {
                depth: 2
            }
        });

        // append a third item
        list.path('next').put({
            next: {
                depth: 3
            }
        });

        // try to read the third item
        list.path('next.next').val(function () {
            done();
        });
    });
});
```

> Seems loosely related to issue #167.

**Comment by amark** [comment]
Weeeeird and yeah the recent bug by @stefdv also has a problem once you get 3 layers deep #185 .

Dangit. There is definitely a common theme to all of these.

**Comment by PsychoLlama** [comment]
I guess that's a good thing though, fix one and we &ast;hopefully&ast; fix all three...

**Comment by amark** [comment]
WOOOHOOO fixed with all the latest major improvements: http://jsbin.com/dedupawete/edit?js,console . Yayayayay finally. Closing this and the other one.
