### ISSUE TITLE
[docs] mark the end of the tutorial

### ISSUE THREAD

**Issue by aeosynth** [amark/gun#21]
it took me a beat to realize that the website's 'try it now' tutorial just ends at the update step

**Comment by amark** [comment]
Good point! ** adds to todo list ** I also want to make some more detailed
tutorials.

**Comment by amark** [comment]
Just finally fixed this now in 28442aa6510433e22850edd684e56051914cd776, @aeosynth ! I also write a new tutorial, http://gun.js.org/web/think.html, which I would love to get your feedback on it. Closing this issue though.
