### ISSUE TITLE
if i just use electron with gun ,not web server ,the peer how to connect?

### ISSUE THREAD

**Issue by nolotus** [amark/gun#210]
yes ,just client ,the peer how connect?
so ,if just have localstorage ~gun not have discovery mechanism? i  Thought have it~

**Comment by amark** [comment]
How to connect to what? A remote server? Give the constructor the URL? To nothing? No URL, it'll use localStorage. Could you clarify your question?

**Comment by tokyo-jesus** [comment]
You should be able to do straight peer to peer with Electron and Gun, but you would need a discovery mechanism of some kind, a way to handle NAT traversal, and possibly authentication, if you want the connection process to be automatic.

--
Carlos Killpack
Hero Punch
Infinite Automata Network

**Comment by Stefdv** [comment]
i use nw ( former nodewebkit) but i guess it's the same principle...In the nw app, i run the Gun server in the node context, and use the browser part of gun in the frontend. I have a simple version on github.
https://github.com/Stefdv/Gun-Server-CMS-App
