### ISSUE TITLE
Docs pages are not working

### ISSUE THREAD

**Issue by vekexasia** [amark/gun#212]
hi, the documentation pages are not working. 

I'm referring to links such as: http://gun.js.org/docs/key.html

**Comment by amark** [comment]
Thanks, we'll get this fixed.

**Comment by amark** [comment]
This page in the wiki should suffice for now: https://github.com/amark/gun/wiki/API-(v0.3.x)#key

**Comment by amark** [comment]
@vekexasia got it fixed! Closing, thanks for reporting.

I would love to hear about what you are working on though. And anything that we can do to help?
