### ISSUE TITLE
Request :  global event on connection

### ISSUE THREAD

**Issue by Stefdv** [amark/gun#213]
It would be helpfull if there was a event we can hook into when a peer is connected or disconnected .
usecase:
- multiple replication servers
- when a server comes online it updates eg `gun.get('servers').path('serverX').put('on')`
- when any other server get's a 'ws-connection' error it updates. eg `gun.get('servers').path('serverX').put('off')   ( server name/ip can be extracted from the url )
  Now every server has a status update about connected servers.

I made a 'monkey-patch' inside the gun.js file for my specific project.
gun.js:  

```
ws.onerror = function(e){ 
                /* Stefdv */
                //var re;
                gun.get('systems').val(function(s){
                    Object.keys(s).forEach(function(sys){
                        re = new RegExp(sys, 'g');
                        if(e.srcElement.url.match(re)){
                            gun.get('systems').path(sys).put('off')
                        }
                    });
                });
            };
            return true;
        }
```

```
ws.onopen = function(o){ 
                r.back = 2; 
                r.ws(opt, cb) 
                /** Stefdv **/
                //var re;
                gun.get('systems').val(function(s){
                    Object.keys(s).forEach(function(sys){
                        re = new RegExp(sys, 'g');
                        if(opt.base.match(re)){gun.get('systems').path(sys).put('on')}
                  });
                });
            };
```

**Comment by Stefdv** [comment]
might be related to https://github.com/amark/gun/issues/180

**Comment by amark** [comment]
I still believe that what is discussed in https://github.com/amark/gun/issues/180 is the "right way" to deal with it.

I closed that issue, so I'm gonna close this issue too. However I'm still open to discussion on it, so please just reopen this issue if it is important for you. :) You've been so helpful with everything, so I really do appreciate/respect your input.
