### ISSUE TITLE
Unreachable Code Detected

### ISSUE THREAD

**Issue by basarat** [amark/gun#228]
I just did a quick inclusion of gun.js as an input to the TypeScript compiler and it pointed out two unreachable code segments: 

![image](https://cloud.githubusercontent.com/assets/874898/19181629/1855f1b2-8cba-11e6-81e2-81eaec4f8069.png)

They seem intentional but if not, now you know :rose:

**Comment by amark** [comment]
@basarat yeah sorry, the tests are a bit messy right now. That was a mockup for a prototype of a linked-list that I never finished writing.

How are you doing? What are you working on? Anything I can help you with? Would love to learn about you!

**Comment by basarat** [comment]
> What are you working on?

http://alm.tools/ at the moment. Heard your episode on JS Jabber and thought I'd have a look around. 

> Anything I can help you with

All good here. Just looking around for now :rose:

**Comment by amark** [comment]
Hey! That looks awesome! I don't use typescript myself but it definitely makes a lot of things easier!

Cool, thanks for checking it out. I hope you wind up finding it useful. :)

I'm going to close this issue for now and leaving the unreachable code to be cleaned up later. Thanks though!
