### ISSUE TITLE
Numerical keys cause problems

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#229]
Gun gets all huffy if you try to save data to a number, though it should just coerce.

``` js
var Gun = require('gun')

// No special config.
var gun = new Gun()

// This complains and says "No key!"
gun.get(15).put({ data: true })
```

If you try to write to `15` as a number, some stuff is synced, but not the actual data.

Also, a bug that's probably related:

``` js
var Gun = require('gun')
var gun = new Gun()

// Save to string 15
gun.get('15').put({ data: true })

// Just read number 15
gun.get(15)

// Throws: "TypeError: Cannot read property '_' of undefined"
```

**Comment by Stefdv** [comment]
I can say that this is solved in the latest release of Gun :)

**Comment by amark** [comment]
wonderful, closing then.
