### ISSUE TITLE
Array Support 😃

### ISSUE THREAD

**Issue by popkinj** [amark/gun#231]
It's mentioned that [Arrays are not allowed](https://github.com/amark/gun/wiki/API-%28v0.3.x%29#allowed-types). Any chance this will be reconsidered? Most data I use contains arrays.

**Comment by amark** [comment]
@popkinj hey! Yes! Array-like support is planned for the future. The only reason why they "aren't allowed" is because arrays are bad with realtime updates (concurrency). Example: If two people "push" to the end of an array at the same time, what happens?

We already have an array alternative, called `.set` which allows you to add items into a list.

Also, if you know what you are doing, you can use this to convert arrays before saving:

```
function array2object(arr){
  var obj = {};
  Gun.list.map(arr, function(v,f,t){
    if(Gun.list.is(v) || Gun.obj.is(v)){
      obj[f] = array2object(v);
      return;
    }
    obj[f] = v;
  });
  return obj;
```

Will one of these options work for now? Thanks for joining the gun community! What are you working on / building?

**Comment by popkinj** [comment]
Hey Mark. Thanks for the speedy response.
I was excited to hear about your project. It's exactly what I've been looking for.

I'm developing a real time app that monitors dynamic speed signs on the highways. Right now I've got everything wired with NeDB and websockets. Was hoping to replace that whole mess with Gun. Thanks for the example. Think I'll wait for your fancy array support before I pitch anything to the client though. 😊 The challenge is understood.

By the way.... Liked your chat on Javascript Jabber.

**Comment by amark** [comment]
@popkinj thanks and thanks!

Could you explain the mechanics of what you need? Do you need strict ordering? Casual ordering? Is it an unbounded array? Or capped? Or fixed? And then I'm guessing if you are tracking speed signs, the values are just integers?

Thanks!

**Comment by popkinj** [comment]
Hey @amark . Sorry for the late response. 

Hmmm... I probably don't have as good a grasp on array types. 
I naively thought I could take a standard json object and stuff it into the database. The data is somewhat complex with arrays all over the place.

We are constantly received data from trusted sources... That tend to enjoy adjusting the data schema without telling us. ha ha....  I'm guessing we would probably want _casual_ and _unbound_? Assuming this is the standard JSON array type.

Thanks for your interest. :)

**Comment by amark** [comment]
@popkinj no problem. Then it sounds like a `set` is exactly what you want, it is used for the todo list and chat tutorial ( http://gun.js.org/think.html ). The data is is stored by insertion-time, so you can order/sort them on load based on their insertion-time key.

It is as simple as:

```
var gun = Gun();

var myArray = [{hello: 'world'}, {you: 'are'}, {so: 'wonderful'}];
var list = gun.get('list');

myArray.forEach(function(item){
  list.set(gun.put(item));
});

list.map(function(item, key){ // print them back out
  console.log("item", item);
});
```

Bu again, another option which will just let you do the blind approach of just saving data is:

```
var MyBigObjectWithArraysSomewhereInThem = {...};

gun.put( array2object(MyBigObjectWithArraysSomewhereInThem) );

// done!

function array2object(arr){
  var obj = {};
  Gun.list.map(arr, function(v,f,t){
    if(Gun.list.is(v) || Gun.obj.is(v)){
      obj[f] = array2object(v);
      return;
    }
    obj[f] = v;
  });
  return obj;
```

**Comment by popkinj** [comment]
Cool.. thanks Mark.

**Comment by amark** [comment]
Since `set` covers this, and we got a ton of major improvements/fixes pulled into gun, I'm now gonna close this. In the future I would still like to see extensions that create variations to `set` - like loosely ordered by insert time, and strictly ordered by linked list. Those are more advanced and wont' be built into core by default though, so they would be good to add to: https://github.com/gundb/feature-requests .

Hope you are doing well!

**Comment by Keidrych** [comment]
As this is the #1 result when this error appears in Gun output adding an upgraded example to support ES6 friendly data extraction back out of GunDB

```
function array2object(arr) {
	var obj = {}
	Gun.list.map(arr, function(v, f, t) {
		if (Gun.list.is(v) || Gun.obj.is(v)) {
			obj[f] = array2object(v)
			return
		}
		if (isNaN(f)) obj[f] = v
		else obj[f - 1] = v
	})
	if (obj[0]) {
		obj.length = Object.keys(obj)
			.sort()
			.pop()
		obj.length++
	}
	return obj
}
```

Now on extraction easily convert the relevant part back into Array for compatiblity reasons like so:
```
function gunMem() {
	const gun = require('gun')()

	const array = {name: 'harrow', data: ['aleph', 'beta']}
	const base = gun.get('*').get('tst')

	base.put(array2object(array))
	base.put(array2object(array)) // Executed twice to show no duplication in set

	base.load(o => console.log(o))
	base.load(o => console.log(Array.from(o.data)))
}
```

**Comment by KiddoV** [comment]
Any news on this one. I see that `Gun.list.map` is no longer available.
