### ISSUE TITLE
0.5 current head doesn't allow new Gun()

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#234]
0.5 current head doesn't allow new Gun()

Can test by modifying examples - http.js or express.js add 

```
--- var gun = Gun({

+++ var gun = new Gun({
```

**Comment by amark** [comment]
thanks for reporting this! Will get it fixed.

**Comment by amark** [comment]
FINNNNNALLY fixed. :) Closing! Thanks for all your help on these, @d3x0r ! You rock.
