### ISSUE TITLE
Authorization error with S3 ("please use AWS4-HMAC-SHA256.

### ISSUE THREAD

**Issue by monkybrain** [amark/gun#235]
Getting the following error when trying to use gun with S3. Anyone had the same problem? (and solved it? :-) )

```
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```

**Comment by amark** [comment]
Odd. No I haven't seen that before, and I have several deployed gun/S3 apps.

Obviously you can't show us your credentials :P but maybe fill us in with some more details? Like how you are initializing Gun with them? (just replace your actual credentials with gibberish).

And then we'll see what we can do to get this fixed for you. :)

**Comment by amark** [comment]
Latest version of gun has  updated basic S3 drivers. I used them recently and it worked, and I haven't heard back from you about any more information (so I can't debug), so I'm gonna go ahead and close. If you still have a problem please reopen and see if you can get us more info. Thanks!
