### ISSUE TITLE
0.5 on react-native: undefined Gun.HAM 

### ISSUE THREAD

**Issue by remon-georgy** [amark/gun#236]
I'm trying to get Gundb branch 0.5 to run on react-native but I'm getting an error.

First, here is react-native application main component:

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {AppRegistry, Text, View} from 'react-native';
import Gun from 'gun/gun';

class GunStorage extends Component {
  render() {
    var gun = Gun();
    gun.get('greeting').put({ hello: 'world' });
    gun.get('greeting').val(function (val) {
      console.log('greeting:', val)
    })

    return (
      <View>
        <Text>
          Welcome to React Native!
        </Text>
      </View>
    );
  }
}

AppRegistry.registerComponent('GunStorage', () => GunStorage);
```

Application runs fine using **gun#master** branch. It produces this output in `react-native log-android`:

```
10-10 09:38:36.746  3804  3907 I ReactNativeJS: Warning! You have no peers to connect to!
10-10 09:38:36.753  3804  3907 I ReactNativeJS: 'greeting:', { _: { '#': 'greeting', '>': { hello: 1476117516725 }, key: 'pseudo' },
10-10 09:38:36.753  3804  3907 I ReactNativeJS:   hello: 'world' }
```

However, on **gun#0.5** (installed via npm install --save https://github.com/amark/gun.git#0.5) prints this error:

```
10-10 09:46:23.226  4105  4128 E ReactNativeJS: undefined is not an object (evaluating 'Gun.HAM')
```

I haven't traced the issue yet, but my first guess is that it has to do with webpack bundling. It's also worth mentioning that same code runs fine in _nodejs_ environment.

**Comment by amark** [comment]
Thanks for reporting this @remon-georgy !

If you can get me the line number for the Gun.HAM error then I can get this fixed & pushed for you. I know Gun.HAM very well, but I'm not sure if the error is when it is being called or when it is being assigned. And since it is called from many places, I need to know where - so I can fix. :)

Thanks so much!

**Comment by remon-georgy** [comment]
You're the man, @amark !

Erring code is `Gun.HAM.union` function definition, in gun.js line **1056**.

Here is the full stacktrace printed by android emulator:
![screenshot_20161010-094755](https://cloud.githubusercontent.com/assets/1994818/19250752/eb2509e2-8ef0-11e6-8afc-66c0028acde5.png)

**Comment by amark** [comment]
Thanks!

Hmmm, module `./index` requires `./gun` which attaches `./HAM` already, so how on earth can it not be an object?

I'll probably have to ask somebody like @PsychoLlama who is better with React Native to help me find out why. (tip, Jesse: you can unbuild with `npm run unbuild` which will give you `src/`, the error is happening in ./index where it tries to attach `union` to HAM which should already be mounted to Gun via `./gun` requiring `./HAM`. Why no exist??? It should)

**Comment by remon-georgy** [comment]
The fact that same code works in Node.js, makes me suspect webpack. I'll take another look tonight.

**Comment by mpolci** [comment]
I had the same problem with a different library in react-native, not yet resolved. I think the problem is caused by the react-native module loader, its require() implementations seems very different from nodejs, in particular it returns an empty object and loads the module asynchronously.

**Comment by amark** [comment]
@mpolci thanks for the tip to everybody else. I would have never known and assumed we were doing some the wrong! ETA on fix? What are you building?

**Comment by thienpow** [comment]
have anyone tried the hack of rn-nodelify?
https://www.npmjs.com/package/rn-nodeify


npm i rn-nodeify -g
then set the following in package.json (the install params below not necessary true, need to test n find out)
"postinstall": "rn-nodeify --install dgram,stream,buffer,events,assert --hack"
then
npm run postinstall

**Comment by amark** [comment]
@thienpow awesome, did this wind up working then?

**Comment by amark** [comment]
Anybody, can we confirm that they fixed the `require` implementation and that this is working now?

Because this wound up not being a bug with gun itself, I'm going to close for now. Would love to hear a follow up from people though, and feel free to reopen if need be.
