### ISSUE TITLE
GunDb in Ionic2 app: Error: Could not resolve 'bufferutil' 

### ISSUE THREAD

**Issue by rastographics** [amark/gun#239]
Trying to use Gun in an Ionic2 app. 

Installed with npm

`npm install --save gun`

Created a provider:

```
import * as  Gun from 'gun';
@Injectable()
export class GunDb {
public gun:any;
  constructor() {
    this.gun = new Gun({
      file: 'database.json'
    });
    console.log('Hello GunDb Provider');
    console.log(this.gun);
  }
}
```

injected provider into my component:

```
import {GunDb} from '../providers/gun-db';

@Component()
export class MyApp {
   constructor(public gun:GunDb){
   }
}
```

But the cli is not able to build the bundle. This error comes up in console:

`Error: Could not resolve 'bufferutil' from \node_modules\ws\lib\BufferUtil.js`

**Comment by rastographics** [comment]
If i try `npm install bufferutil` I get an error that Python cannot be found. Is Python required in order to use Gun?

**Comment by amark** [comment]
@rastographics weird! So GUN comes with a NodeJS websocket library by default, and that library requires BufferUtil. But BufferUtil should not require python. And in fact it looks like it is in ws/lib/BufferUtil not a separate npm module (?)

It should install perfectly fine, give me a couple of clues:

1. What machine are you on, what OS are you on?
2. Are you in a Dropbox folder? Try installing (if you are okay) with sudo? Or without the save option?

Thanks. Sorry.

**Comment by rastographics** [comment]
1. Windows 10 Pro 64bit

2. It is not in dropbox folder. 
Windows doesn't have concept of sudo. 
I tried without save option, only difference is that it didn't put gun in the package.json.

I noticed in the build log (using rollup), that when I include gun in my project, rollup adds a line to the log: `rollup: Treating 'fs' as external dependency` and that is right before the `Could not resolve 'bufferutil' ` error.

Maybe this is a problem with rollup being able to handle the way the gun modules are loaded? I do not know too much about rollup

**Comment by amark** [comment]
Oh! So this is not an npm install error, it is a bundling problem?

Client side needs to require('gun/gun') not require('gun'). The require('gun') currently (need to fix) assumes it is being run in NodeJS environment... and instead points to index.js which points to lib/server which includes the file.js/data.json adapter and WS/P adapter. Those don't work in the browser.

In the browser though, gun/gun points to gun core, which is already bundled with browser-specific things like localStorage and browser WebSockets.

Hopefully this helps/fixes?

**Comment by amark** [comment]
What are you building!? :)

**Comment by rastographics** [comment]
OK I did this:
`import Gun from 'gun/gun';`

And now it builds correctly and page loads without error!

I'm building an app that is used for classrooms and student teams to track points and scoring for many categories over a span of weeks.
I need realtime, because a projector shows the scores on the wall as the students are filling them in on the mobile devices.
I built a prototype with firebase, but it seems extremely limited the type of queries and sorting you can do. Then I heard about Gun on javascript jabber and i'm giving it a try.

**Comment by amark** [comment]
@rastographics awesome, that sounds really neat! Would love to see it. And make sure to hit us up on the https://gitter.im/amark/gun if you have any questions or need any help. :)
