### ISSUE TITLE
incrby/decrby would really be nice to have in the API, it would extend the use cases tremendously

### ISSUE THREAD

**Issue by jeffbski** [amark/gun#249]
I'm excited about the possibilities of gundb but it would be really handy to have incrby and decrby in the API. There are so many places where you simply want to increment or decrement by 1 or N and this would really simply code. 

Plus normally these types of operations converge really well even under concurrent updates as compared to trying to do a get/put where the value has changed between the time the put fires. With increment and decrement it just isn't an issue, they eventually get to the same number.

There are so many use cases where we are tracking counts or values and without getting into locking you just can't do this properly with a non-transactional get + put. 

I've used this in Redis and it works fantastic for so many situations. It will really increase the places where gundb can be used effectively. 

I realize this strays a little from the current merge functionality of simply converging properties to a value, but it's simply a set of increments and decrements that get merged and if you don't have an operation yet then it is added to the set and applied. 

I'll post links to the redis incrby and decrby operations for completeness. 

http://redis.io/commands/incrby
http://redis.io/commands/decrby

**Comment by amark** [comment]
@jeffbski thanks! We currently have a CRDT counter:

https://github.com/amark/gun/wiki/Snippets-(v0.3.x)#counter

Could you try that out and see how well it works for your scenario?

Very good points! :)

What are you working on?

**Comment by jeffbski** [comment]
counter looks like it would solve that perfectly. I hadn't even seen this wiki page yet so I'll have to go through all that is on there. 

I have a small developer training business so I focus on teaching developers what I believe are the best up and coming technologies. I currently have a home grown event sourcing db for my data which is a combination of leveldb and redis, but I'd love to switch it out for a real-time graph db like gundb. I was originally looking at rethinkdb but since they folded up shop, I'm glad I came across gundb. I also like that gun is truly open like MIT and Apache. I know many enterprise companies that won't touch an AGPL project unless they can buy a reasonable commercial license instead. 

So I'm excited about the possibilities of Gun. I look forward to trying it out for a variety of different things.

**Comment by amark** [comment]
@jeffbski thanks for the kind words! Do you have links to your event sourced db (that is awesome!) ?

Yes, truly open is better <3 . Although we do offer commercial support plans as well (so if you know anybody that would be interested, please let us know. It really helps us out)!

Thanks! And just FYI to check out the 0.5 branch which has all the performance/procedural improvements in it as well as many bug/stability fixes. Just in case you run into any current master/stable (0.3) problems. :)

**Comment by jeffbski** [comment]
My home grown event source db is a little rough, it works but I think it got a little more complicated than I like so I haven't opened it up yet. Eventually I wanted to do a simpler version built on top of Kafka and Redis or now maybe Kafka and Gun is even a better idea. I'll keep this in mind as I dig into Gun and learn how it works.

**Comment by jeffbski** [comment]
And thanks for the tip about 0.5, I'll check that out.

**Comment by jeffbski** [comment]
Yes, I know what you mean, you do need to keep the lights on. I like to give things away for free when I can, but you have to make a living one way or another. Commercial support and training are some good avenues to try along with this. Enterprises love to have a support package for anything running in production. It is just good insurance policy.
