### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by BartNetJS** [amark/gun#257]
Hi, what is your opinion about TypeScript.
TypeScript got a lot of attraction. 
Even Angular 2 is written in TypeScript.
Is it something you also think about for GunDB?

**Comment by JimmyBoh** [comment]
If the GunDB API is as simple as it appears, manually making the definition file for it won't be that difficult. Maybe a full evening to fork (either this repo or DT) make the files and then submit the PR.

I've got some other OSS commitments to work on, but wouldn't mind getting the ball rolling if it can wait a few weeks.

**Comment by BartNetJS** [comment]
you are right, the definition file is not that big work.
But my question was about writing gundb api in TypeScript directly, instead of javascript.

**Comment by amark** [comment]
@JimmyBoh thanks for the offer! Just as a note, the current master/stable 0.3 codebase is getting deprecated, so if you do contribute, definitely base it off of the 0.5 branch. In general though...

I don't even know what a definition file is! So you are definitely my superior in this regard.

@BartNetJS we support even legacy systems, like IE6. This is not necessary for most developers out there, but important for some of our enterprise offerings. As a result, we wouldn't be writing gun core directly in TypeScript. I do think it is important to be compatible and integrate nicely/beautifully with the TypeScript community though! So if things like @JimmyBoh 's suggestion help, I think that would be a great idea.

**Comment by JimmyBoh** [comment]
[Here is a "thorough" explanation](https://github.com/Axinom/x2js/pull/50#issuecomment-255440760) of what how it all works. The best thing is to just watch the two GIFs, they show what it is like without and with a definition file.

**Comment by amark** [comment]
@JimmyBoh man, GIF explainers are life savers. That is cool!

**Comment by JimmyBoh** [comment]
@amark Haha, thanks! Although I found out that the tool I used has a feature to add a "progress bar" at the bottom, so it's easier to tell when it repeats, etc. Next time!

**Comment by BartNetJS** [comment]
@amark TypeScript is transpiling into javasript. 
So from a compatibility standpoint, that is just one of the interesting thinks about TypeScript.
You can write today in TypeScript, it can be transpiled into ecmascript 5 or 6 (or even older).
When ecmascript 7 is out, you take the same bits and transpiled it to ecmascript 7

My experience with typescript is that developers are writing less code, the produced javascript is the best you ever seen.
You can refactor, it is typesave,...

see also https://scotch.io/tutorials/why-you-shouldnt-be-scared-of-typescript

**Comment by amark** [comment]
@BartNetJS TypeScript is cool, certainly. :)

Going to close this issue though. Please reopen if you find a problem with using gun with TypeScript. Or if you or @JimmyBoh write a definition file please submit it to the wiki or docs or wherever you think is best appropriate.

**Comment by stephenlaughton** [comment]
@amark why close this issue without further discussion? Writing the library in Typescript could make it much easier for new contributors to read/understand the code. With respect, your last reply about putting the definition file in the wiki or docs sort of indicates you didn't look into how Typescript works and could be a real asset to the project (much in the same way ES6 transpiled down to ES5 could be).

I think it is a valuable discussion to have as it could directly and positively affect how open and accessible the project is to newcomers. Even if it is decided Typescript isn't a good way to go, I think the discussion was shut down a bit quickly.

**Comment by amark** [comment]
Reopened per @stephenlaughton request. :)

**Comment by amark** [comment]
I'm swamped with supporting people and trying to improve performance and add features, so I don't personally have time to "look into" a lot of things I'd love to learn about. That is why people who already know and have experience with writing definition files are able to help out, this is a community effort and why open source is awesome! I just can't do everything myself (and I don't, thank goodness for Jesse, and Stef doing web component integration, Robert doing security and auth, etc. everybody else), especially with a 1 year old kid and a family.

**Comment by JimmyBoh** [comment]
I absolutely love TypeScript, but I agree with Papa @amark on this one.

Just because a piece of technology _can_ be helpful/productive doesn't just justify it being used on every project. You have to weigh the gain of using it against the loss of switching/implementing it. In some cases it is a no brainer: someone who is a TS pro starting a new solo project is obviously a yes, and equally a team of people with little-to-no TS experience on a 2 year old project is usually a no. 

Luckily for all of us TypeScript provides gains on two facets, one for the developer (GUN contributors) and one for the community (people using GUN). Even if the developers don't want to use TypeScript, there is nothing stopping the community from creating and sharing definition files.

**Comment by stephenlaughton** [comment]
@amark thanks for re-opening and being so receptive! I definitely understand not having the time to check out all the shiny new things, especially in the world of JS. 

@JimmyBoh I agree with you to an extent about the greenfield vs. established project gains of Typescript... but where I disagree is the long-term benefits of migrating over to something like Typescript while a project is relatively young (I think Gun qualifies as young?). The goal of Typescript is overall maintainability of code, and I noticed that Gun is currently in overhaul mode with the 0.0.5 branch and a pending pull request #219 converting the codebase to ES6. I would argue that if ES6 is the direction the project is going in, Typescript isn't that much more work to implement. If the codebase is sticking to ES5, I totally agree Typescript is a stretch at the moment. Right now I feel I don't have time to contribute to the project given the current state of the code. This isn't a knock on code quality, just my own time constraints. A library written in Typescript is a lot easier to jump into, hence my suggestion to keep the discussion open :)

What are the general thoughts on the future of the codebase? Is #219 going anywhere?

**Comment by amark** [comment]
@stephenlaughton gun core is going to stay compatible with both ES5 and ES6 out of the box by default. Use of `npm run unbuild` in 0.5 will allow for Webpack and ES6 features to do their advanced Babel / transpiling as needed. Devel-pa (author of #219) and I talked about this, and he has helped write the rebuild script for 0.5.

Yupe, you are right. Most people don't have time :P we're all super busy - at this point, if nobody has time for it then there isn't really much more to talk about (which was why I closed the thread, I wasn't trying to upset anybody). Maybe when I finish the https://github.com/amark/gun/wiki/Porting-GUN , people can use that as a reference implementation to implement ES6-only or Typescript-only or Coffeescript-only versions, which would be great. But for now, universal compatibility and support is a big goal.

**Comment by amark** [comment]
We finally got 0.5 (now at 0.6 actually) merged into master! Including some nifty tools that help make it integrate better with webpack and others with the `npm run unbuild` command.

I have personally also already used GUN with a TypeScript app too!

Since it has been another quarter year + since the last comments in this thread, I'm gonna go ahead and close it again - especially because as we're nearing our v1.0 production-ready release, I want to use "issues" more for reporting known bugs rather than for chats (although I very much like discussions, so please jump on the gitter channel to continue it!). Thanks :)

**Comment by Jack-Works** [comment]
Hello everyone. I've published `@types/gun`.

**Comment by dezmou** [comment]
> Hello everyone. I've published `@types/gun`.

Could you provide an example to do the equivalent of "new Gun()" ? 
All I am able to import is : 
import { SEA, node } from 'gun';

**Comment by Jack-Works** [comment]
Doesn't import Gun from "gun" or import * as Gun from "gun" work?

**Comment by dezmou** [comment]
import * as Gun from "gun" work thanks

**Comment by negue** [comment]
@Jack-Works thanks for the typings 🎉 , do you plan to do a typed api without having to add AppState class like `new Gun<AppState>();` ? 

just using `any` ends up in same methods complaining about `something is not of type never`

**Comment by Jack-Works** [comment]
> @Jack-Works thanks for the typings 🎉 , do you plan to do a typed api without having to add AppState class like `new Gun<AppState>();` ?
> 
> just using `any` ends up in same methods complaining about `something is not of type never`

Can you give an example? I found that use `Gun()` or `Gun<any>()` is working.

**Comment by flipswitchingmonkey** [comment]
I may just be missing something obvious here but... how am I using these types for simple data storage? As it is now it appears that for every single item that I want to retrieve I'd have to define an interface? Or rather: how would the interface look if I want to store a random amount of items via gun.get('something').put(content) if 'something' is e.g. a counter?

**Comment by Jack-Works** [comment]
```ts
interface State {
   yourapp: {
       [Username: string]: { age : number }
   }
}
```
