### ISSUE TITLE
0.5 require gun/gun.js fails

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#274]
recent changes have caused including gun.js to fail...
```
//var Gun = require( "gun/gun.js" );
var Gun = require( "./node_modules/gun/gun.js" );
var db = Gun().get( "database" );
db.path( "clips" ).map( (val,field)=>{ console.log( field,"=",val ); } );
db.path( "clips" ).put( { 1: { start : 0, duration : 3} } );
```

**Comment by amark** [comment]
Did it report a crash/error? Any line number?

**Comment by d3x0r** [comment]
No, it just returns, does not log startup messages.

**Comment by amark** [comment]
Hmm, I've identified a couple issues, with `new` `opt` and `Gun` and Jesse's edits. IDK if these are the changes, but we're meeting up in a few minutes to fix and push, so hopefully this will be one of them.

**Comment by d3x0r** [comment]
this seems to work better...
