### ISSUE TITLE
0.5: drivers won't load if `new` is used

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#277]
In the v0.5 branch of gun, plugins load themselves by listening to the `opt` event. If it doesn't fire, many plugins won't work properly.

If gun is instantiated with the `new` keyword, the `opt` event doesn't seem to fire:

```js
Gun.on('opt', function () {
  console.log('Fired')
})

// Logs "Fired"
Gun()

// Nothing logs.
new Gun()
```

`new` doesn't work in Node.js or the browser.

**Comment by d3x0r** [comment]
#234  :)

**Comment by PsychoLlama** [comment]
Oops! Sorry, duplicate! I didn't see yours @d3x0r.
