### ISSUE TITLE
0.5 node client does not connect to node server

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#279]
node client does not connect to node server. (esp if 2 separate modules loaded in same project?)
```
var Gun = require( './' );


/* create a server.... */
var http = require('http');

var port = 7734;
var ip = '0.0.0.0';

var hubGun = Gun({file: 'hubdata.json'});

var server = http.createServer(function(req, res){
	console.log( "connect.(never see this, cause websock gets it?)" );
	if(hubGun.wsp.server(req, res)){
        	console.log( "websock request?" );
		return; // filters gun requests!
	}
	stream.end(); // stream
});
hubGun.wsp(server);
hubGun.get( "nothing" ).map().val( function(val,field){
	console.log( "server got a value", field, val );
} );

exports.server = server.listen(port, ip);
/************** End Server *******************/


/* add a client module, that connects to the server, has its own filebackup(or not)*/
var gunOpts = {peers:["ws://localhost:7734/gun"], file:'notnull' };
var gunClient = Gun( gunOpts );

var wakeup = gunClient.get( 'nothing' );
// write something to the server somewhere....
wakeup.path( "asdf" ).put( "notnull" );
wakeup.map().val( function(val,field){
	console.log( "client got his own value", field, val );
} );
```
This is my same example I keep posting...  I've added debug logging to see where the data gets to... (there should be much more logging, for now the 'client got his own value asdf notnull' is the only logging.
I would expect maybe a 'connect' from the server
I would expect the server's ```hubdata.json``` file to get 'asdf=notnull' in it.
And the map should fire on the server indicating 'server got a value'

---

Edit1: I split the files into side0, side1; as separate tasks they do connect, and the server(side0; the top half) does get the data from the client (side1; the bottom few lines of code).

**Comment by amark** [comment]
Starting with this one first :) to get it fixed.

**Comment by amark** [comment]
@d3x0r fixed with https://github.com/amark/gun/commit/111d0f5bdac68720d42719c9e5f6961ce0fd667c . Closing! Reopen if you find anything else wrong. :)
