### ISSUE TITLE
0.5 fails to events on server

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#280]
Node processes....

side0.js is a server.  It stores data in hubdata.json
side1.js is a client; it connects and puts data into the server.  The hubdata.json shows the data.  But neither .map or .on in the side0 server gets events.

side2.js is a different client that's putting stuff in a different tree.  I had originally intended side1 to hear the event from side2, through side0, but it does not.

side0.js
```

var Gun = require( './' );
var http = require('http');

var port = 7734;
var ip = '0.0.0.0';

var gun = Gun({file: 'hubdata.json' });

var server = http.createServer(function(req, res){
	// how does this care about '/gun'?
	console.log( "connect." );
	if(gun.wsp.server(req, res)){
        console.log( "websock request?" );
		return; // filters gun requests!
	}
	stream.end(); // stream
});
gun.wsp(server);
exports.server = server.listen(port, ip);

var db = gun.get( "asdf" );
// these we added later because I didn't get events on the other client either....
// none of these fire.
gun.on( (val,field)=>{ console.log( "new field: ", field, "=", val ); } );
gun.path( "Services" ).map().val( (val,field)=>{ console.log( "service Request: ", field, "=", val ); } );
```

side1.js
```

var Gun = require( './' );
var gunOpts = {peers:["ws://localhost:7734/gun"], file:'notnull' };

var gun = Gun( gunOpts );



var wakeup = gun.get( 'nothing' );


wakeup.map().val( (val,field)=>{ console.log( "new field: ", field, "=", val ); } );
wakeup.path( "Services" ).map().val( (val,field)=>{ console.log( "service Request: ", field, "=", val ); } );

wakeup.path( "asdf" ).put( {property:"notnull"} );
```

side2.js 
```


var Gun = require( './' );

var gunOpts = {peers:["ws://localhost:7734/gun"], file:'notnull.services' };
var gun = Gun( gunOpts );

	var svc = gun.get( 'Services' ).path( "registry" );

	svc.map().val( function(val,field){
		console.log( "received service request", val, field  );
		//this.put( { serviceID: "1234" } );
	}).not( ()=>{ console.log( "nothing yet" ); } )
	// shouldn't have to do a put... just here for later testing... doesn't help.
	svc.put( { serviceName : "Chat" } );

	svc.put( { serviceName : "Firewall" } );
	svc.put( { serviceName : "Otherthing" } );
```

**Comment by amark** [comment]
I tried running these now that #279 is fixed... could you try rerunning them and see if they work? I wasn't sure what logs to look for in what order, which is going to be easy for you but a time suck for me. Let me know if it worked!

**Comment by d3x0r** [comment]
the tests were somewhat broken; but having fixed the tests, they seem to perform correctly now.

-----------
https://github.com/d3x0r/gun/tree/0.4-tests  (having been fixed)

side-test-require.js  uses require to pull side0, side1 and side2... but when run this way, hubdata.json (the file:option passed to the side0 Gun() factory ) never gets written.

I could almost see if because I'm using the same opt structure for 1 and 2, but they open their own files correctly....

**Comment by d3x0r** [comment]
https://github.com/d3x0r/d3x0r-gun-73575
checked out into gun
in d3x0r-gun-73575 run 'node side-test.js' 

which runs side0.js (hub), side1.js (does a get("nothing") )
side2.js does a get( "Services" ) and puts some requests

side1 gets requests from side2 on the mesh he's not even listening to.

0.6.3
