### ISSUE TITLE
How to override put and set function?

### ISSUE THREAD

**Issue by Lightnet** [amark/gun#290]
I wonder how override those function since just thinking of authorized checks. But of course it just simple testing it would nice to see. Just thinking of how server and client are manage in way not get spam or something. As well verify check if they have module install on other peer to peer.

Like client can only read while server read and read but depend on how it coded.

**Comment by amark** [comment]
This is changing in 0.5, but I'm going to answer relative to current master/stable:

In browser we can turn off writes by:

```
var gun = Gun({ 
	wire: {put: function(g,cb){
		cb("You are not allowed to save data!");
	}
});
```

And then on the server we can make sure we do not receive writes by doing:

```
gun.wsp(app, function(req, res, next){
	if('get' === req.method){
		next(req, res);
	}
	if('put' === req.method){
		res({body: {err: "Permission denied!"}});
	}
});
```

I'm not sure how you would determine "spam" but you could theoretically add that logic into the above server callback and reject requests.

Not sure what you mean by verify modules installed on other peers?

Note: In 0.5 we're moving a lot of this into core so that way it will be more unified, so most of this code will be changed/deprecated for something better/easier.

**Comment by amark** [comment]
@hillct oh, could you actually post this question on StackOverflow ( http://stackoverflow.com/questions/tagged/gun ) ? Things like this should be accessible publicly, and would be useful to others. Thanks :)

**Comment by Lightnet** [comment]
Well I am not sure how spam but I wanted to stop data send move over seconds. But disconnect users from  unusual data send or request.

To make sure the server Module API matches when hosting I guess for version check or support it.

**Comment by amark** [comment]
oh sorry I totally confused you, @Lightnet , with @hillct who I tagged in the previous post. GitHub's auto-generated icons looked similar. My bad. I am sorry.

@Lightnet , I did not understand your last comment though. Did my replies answer your question?

**Comment by Lightnet** [comment]
I guess it fine. I should re phase just mind off some time or hard to explain. It something like gundb would like to check peer to peer plugins version in case. Since each gundb is design differently for application used to design to match what the data is using. For example if some one adds game database with someone 3d modeling design database with knowing if the data base is added there. I guess it off topic.

**Comment by amark** [comment]
@Lightnet lets finish this chat on the gitter? I'm still not quite understanding fully, and I wound up forgetting to follow up over github issues (chat is better).

Still would love you to transfer the question you asked over to StackOverflow :) but I'm gonna go ahead and close this issue here.
