### ISSUE TITLE
0.5 invalid data json file

### ISSUE THREAD

**Issue by rsaccon** [amark/gun#301]
I don't know how I got and I could so far not repeat it, but it happened. Suddenly the db seemed to be empty. The data file was invalid. It had an additional `}` a the end. I manually deleted that `}`  and all was fine again.

**Comment by amark** [comment]
@rsaccon yupe, good problem to report. `data.json` file.js module (which is not meant for production use case) uses NodeJS's native `fs.writeFile` command which is **not atomic** meaning if it writes the same file multiple times at the same time it can corrupt the file (that is what I suspect happened).

I can easily fix it so you can pass in a replacement to `fs.writeFile` like https://www.npmjs.com/package/write-file-atomic which is safe. Would you like that? Note: Even using a safer writeFile would not make it okay for production use.

It is why we recommend using a better storage engine than NodeJS' built in file system, like S3 or Level. However, if `fs.writeFile` is skrewing up just during local testing (I'm guessing you are on a not-SSD harddrive?)... then I definitely should wrap the function call with some safety catches.

**Comment by amark** [comment]
I've switched the default disk file.js adapter to throttle writes in 1 second intervals. This should prevent overlapping writes and thus be safe (unless somehow it takes more than 1 second for NodeJS to flush to disk, but I doubt that will happen).

Again, not production ready, but it handled 24K updates nicely. So I'm gonna close this now.
