### ISSUE TITLE
0.5 server 2 server sync . syncing halves data

### ISSUE THREAD

**Issue by Stefdv** [amark/gun#305]
Setup: (0.5 using file.js)
Fire up 2 servers on 2 different machines. 
server 1 has a full database (1,5 Mb) 
server 2 is has no database
open the browser page on the 'empty' computer...syncing starts....but in the end my data.json is half the size ?? (700kb) on both sides.
If i start them both with a full data.json everything is fine.

**Comment by amark** [comment]
Was every data point in the entire graph requested? Cause if not, not all the data will transfer. I'll unfortunately need some more specific/exact examples/seed to reconstruct this - then I'll be able to write a PANIC test around it to verify it never happens again.

**Comment by Stefdv** [comment]
Even if i don't request all data, it seems strange to me that i loose half my data on one side? Besides that..shouldn't the servers sync no mather what? ( Or is that just my interpretation ? ) 
So i should let the server request all data ? Then it would be usefull if we had a `Gun.all()`  option ;)
Maybe i should change the title of this post to that.. We need a `Gun.all()` method ;p

**Comment by amark** [comment]
Ah, I think I remember having this conversation before. By default you want server devices to basically `.all()` each other. That makes sense. We should explore this more later, gonna prioritize other stuff for now though.

**Comment by Stefdv** [comment]
Yeah, not an issue atm. I just 'set()' everything on a 'gun.get('ROOT')' and let every server do a 'val()'
