### ISSUE TITLE
Add option to disable bundled localStorage driver

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#311]
Since gun uses plugins to persist state, the option to swap for other more suited storage drivers is important. You might want to use indexedDB instead, or a different localStorage driver altogether. However, the bundled localStorage driver doesn't appear to have any option for disabling it.

This becomes problematic when paired with something like IndexedDB, because you're creating two full replicas on the same machine, slowing down perf and burning the precious space browsers generously provide.

Proposal: add an option to the gun constructor.
```js
const gun = Gun({
  shouldUseDefaultLocalStoragePluginThingy: 'nope'
})
```

I'm not really tied to the name, but you get the idea.

For context prompting this issue, [here's a thread on gun-level](https://github.com/PsychoLlama/gun-level/issues/23#issuecomment-275283456).

**Comment by amark** [comment]
Absolutely.

**Comment by swhgoon** [comment]
seems done on 0.8 👍

**Comment by amark** [comment]
Yes, wow @shwgoon you are fast!! How'd you notice this?? Thanks for the reminder, closing. 

Just pass localStorage: false and or WebSocket: false in the Gun constructor. Case sensitive matters.

**Comment by PsychoLlama** [comment]
Woohoo!

**Comment by amark** [comment]
@psychollama yes! Although that means gun-level is broken now, but it is the last breaking change. Btw! I figured out how to generalize frugality for updates as well!!

**Comment by PsychoLlama** [comment]
Sweet! That's awesome! Does it have anything to do with the radix trie youtube video you posted earlier?

gun-level [has been broken](https://github.com/PsychoLlama/gun-level/issues/28) for a while. I don't know what caused it, but it's due for some fixes anyway. In that sense, breaking changes from gun aren't a problem :wink:

**Comment by amark** [comment]
Yes! 50K+ acknowledged disk writes a second on sequential keys, 15K writes/sec on random keys. I've updated the default ids to use collision resistant UUIDs as well! This will let you scale out cheaply for most data which will be append-only, while still being able to optimize cost for updates as a ratio of how many active concurrent users you have. :D

**Comment by amark** [comment]
@PsychoLlama :( sowwy, do you want me to explain the new updates? Or would you rather I just patch gun-level myself when I find time?

**Comment by PsychoLlama** [comment]
Awesome @amark! I'm glad Frugality's working for you. I'll take a look at gun-level sometime soon and get that fixed up... maybe I'll hit you up on Gitter and we can discuss the API changes?

**Comment by amark** [comment]
@psychollama, sounds great! Just let me know. You are up late!

**Comment by PsychoLlama** [comment]
Ha! In my defense, so are you 😜

**Comment by amark** [comment]
But I'm the night owl :P

**Comment by PsychoLlama** [comment]
Excuses 😆

**Comment by amark** [comment]
:P

**Comment by swhgoon** [comment]
@amark I subscribed to `https://github.com/amark/gun/commits/master.atom`
