### ISSUE TITLE
.map() combined with a put(null) throws Uncaught TypeError: Cannot read property '#' of null

### ISSUE THREAD

**Issue by leemuro** [amark/gun#320]
It seems to me that a simple setup like this:

`var list = gun.get('myList');`
`list.map(function(value, id) { console.log(id + ":" + value); });`
`list.path('message').put('hello world'); // outputs "message: hello world"`
`list.path('message').put(null)' // throws Uncaught TypeError: Cannot read property '#' of null`

I'm not sure if i'm doing something I shouldn't here.  I'm just trying to follow the recommended way of deleting data.

Is there a better way to do this? Is this intended behavior?

**Comment by amark** [comment]
No no! This definitely looks like a bug. I can probably get this fixed tonight or tomorrow. I'll keep you posted. Thanks so much for reporting it!

@leemuro what are you working on, in the meantime?

**Comment by amark** [comment]
fixed! Publishing to NPM as soon as travis finishes. :)

**Comment by leemuro** [comment]
Wow that was crazy fast! Thanks for looking into it! I'm really enjoying gun so far.

**Comment by amark** [comment]
:) it was just missing a simple typecheck - that is why it is so important for people like you to not hesitate and just post/ask! Really helps fix random edge cases. :)

NPM is now published as `0.6.3` and should work for ya. Great! I'm glad to hear. Definitely join the gitter channel, cause I'd love to hear about what you build!
