### ISSUE TITLE
How to prevent sharing protected data with the client?

### ISSUE THREAD

**Issue by styfle** [amark/gun#323]
In the relational database world, you usually have a REST endpoint for each table in your database and you can grant access to the endpoint depending on who is trying to access it via auth token, etc.

With GunDB, it appears the entire database is accessible between the client and the server.

### Client code
```js
var alice = gun.get('person/alice').put({name: 'alice', age: 22});
```

### Server code
```js
var admin = gun.get('admin/secret').put({name: 'alice', secret: 'ABC123'});
```

1. What is to prevent someone on the client side from trying to read `admin/secret`?
2. Another scenario I thought of is someone just putting garbage data in a set that does not match other objects in the set and could potentially break code on other clients/servers.

**Comment by scottmas** [comment]
You may want to see this thread: https://github.com/amark/gun/issues/321

**Comment by styfle** [comment]
Thanks, this is basically a duplicate of #321 so I'll close.
It sounds like the answer the question is that there is no current way to protect data.

**Comment by amark** [comment]
@styfle not quite, we're encouraging people to do this with encryption - and have made a video series introducing the concept: http://gun.js.org/explainers/data/security.html

Somebody implemented a login prototype here: https://github.com/swifty/gun-p2p-auth

Have we ourselves yet built official apps/documentation showing how to do this? Not quite, but we're in the middle of doing that.

But it can be done already.
