### ISSUE TITLE
data not stored in localStorage when syncing or loading from copied file ( sqlite or json)

### ISSUE THREAD

**Issue by Stefdv** [amark/gun#328]
When i transfer data.sqlite3 or data.json file from one application to the other and start the other app the data will load into memory but never into localStorage.
If i sync from one app to the other, the data.json is created but data is not loaded into localStorage

**Comment by Stefdv** [comment]
Update:
APP_1 :  data is in sqlite file ( NOT in localStorage
APP_2:  using file API ( data.json) No data yet!!

APP_1  peer(APP_2)
APP_2  peer(APP_1)

Data syncs from APP_1 to APP_2   ( not to localStorage )
Data syncs back to APP_1 ( i notice because a sqlite_journal is created ) AND INTO localStorage;

might be related to https://github.com/amark/gun/issues/326


when i have both apps sync to eachother ( one with sqlite, the other with 'data.json')

**Comment by Stefdv** [comment]
Well i was wrong... It does sync to localStorage...It just takes a very long time.
closing this as it might be related to Sqlite

**Comment by amark** [comment]
just really bad perf on SQLite side, that is terrible, and needs to be investigated.
