### ISSUE TITLE
Graph or Document-Based

### ISSUE THREAD

**Issue by alkrauss48** [amark/gun#33]
Hi,

This project looks really neat, and i just have to ask a question. Should this presently be redubbed as a document-based database engine, instead of graph? I see the 'Ahead' that Neo4J cyphers plan to be added, but at the moment I don't see any aspects of a graph database - but enlighten me if I'm missing something, as that's very possible

Great job overall!

**Comment by amark** [comment]
Thanks! The answer is yes: gun already is graph based.

https://github.com/amark/gun/wiki/Partials-and-Circular-References

Goes over how you can do circular references, which is only possible with graphs versus a document.

You are right though, in that there isn't much documentation or support for other "more interesting" graph behavior. I'm working on it.

Would you be interested in writing a Cypher plugin?

**Comment by amark** [comment]
Closing this since I haven't heard back from you :). Feel free to reopen it.

**Comment by alkrauss48** [comment]
Sorry, I meant to get back here. Closing it is best - I don't have much experience with Graph databases myself
