### ISSUE TITLE
Listen video in double speed?

### ISSUE THREAD

**Issue by ShalokShalom** [amark/gun#333]
The Readme suggests to listen this video in 2x

https://www.youtube.com/watch?v=qJNDplwJ8aQ

Are you sure about it? ^^

**Comment by amark** [comment]
Lol, why not? 2X speed is GREAT. Especially for an hour long video... that cuts it down to only a half hour.

Note: The video is pretty outdated in terms of code/API use, definitely make sure to read the docs for the latest: https://github.com/amark/gun/wiki/API

How are you doing? What are you building?

**Comment by ShalokShalom** [comment]
I am simply interested into the project. How understand a single sentence with double speed?

**Comment by amark** [comment]
True, listening to youtube podcasts on 2X takes a while to "get used to". If you cannot understand what is being said, definitely watch it on 1X speed. :)

**Comment by amark** [comment]
sorry about that!

**Comment by ShalokShalom** [comment]
I think 1.25 is somewhat understandable. No reason for a sorry, i simply asked, if you think that this is a serious suggestion. _

**Comment by amark** [comment]
@ShalokShalom sure, feel free to make an edit to the README saying "1.25X" and I'll accept the edit/pull-request.

Gonna close this now, to keep things tidy. Thanks for asking! And do join the chat room ( https://gitter.im/amark/gun ) everybody is super friendly and I'd love to talk more!
