### ISSUE TITLE
GPS Example missing

### ISSUE THREAD

**Issue by styfle** [amark/gun#341]
Try to visit http://gps.gundb.io and you get a 404 File Not Found from Dropbox surprisingly.

![image](https://cloud.githubusercontent.com/assets/229881/24009736/461df86e-0a4c-11e7-8ba0-2b67839aaee8.png)

![image](https://cloud.githubusercontent.com/assets/229881/24009786/64ccd5b4-0a4c-11e7-9ad7-2e6f175093b1.png)

**Comment by amark** [comment]
Thanks. Fixed. :)

Warning: I hooked it up to the example server, which BACKS UP GPS data to S3. I need to launch an in-memory only server so the GPS isn't getting saved (for extra-security-purposes as well as making sure things are cheaper for me). Please don't abuse this demo.
