### ISSUE TITLE
NodeJS v7+ Stock Examples Fail

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#348]
Http.js
   * no data is saved in data.json
   * no data is relayed to other clients, but only updates on refresh of the client ( for json editor example and todo list) chat does not work.

express.js
* no data is saved in data.json
* data is relayed to other clients, but only updates on refresh of the client ( for json editor example and todo list)  chat does not work.

~~http-external-ws.js~~
~~* todo and json editors work, data.json IS saved and changes are transmitted to other clients. (+2 over the two above)~~
~~* chat is not relayed to other clients.~~

**Comment by amark** [comment]
@d3x0r I just tried again 1 second ago... it is working flawlessly over here. You sure???

**Comment by d3x0r** [comment]
this is my current head: 
ab467589c20e0ea5f4f4dd692d9f8baa6f41b235  (that is current head)
git diff shows no diffs

node 7.4.0
Chrome 56.0.2924.87 (64-bit)
 
dont' know what else might be different.

**Comment by d3x0r** [comment]
(written last)oh I see - node 7.0.0 works.

Now from home I've updated and switched to the right head, and it's the same behavior
node v8.0.0-pre

also just did a npm install gun; went into node_modules/gun and npm start; same thing; actually worse - the chat doesn't even send to itself

https://nodejs.org/en/download/current/ (7.7.4) 7.4.0+ seem to not work.

**Comment by amark** [comment]
Per @d3x0r 's update in the chat room: test uWS on 7.1+ .

**Comment by d3x0r** [comment]
probably more related to not being linked to the right runtime api ...
```wsp err:  Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.``` Something like that might get logged.  and then the falllback to normal 'ws' doesn't work.(http.js)

neither of that should have any bearing for http-external-ws.js failling to fire maps on recieving client for chat example.  (a, b, a sends something, b gets it and stores in localstorage, but does not trigger maps)

**Comment by d3x0r** [comment]
okay fixing the missing double parse... http-external-ws now works as expected.

(chat still fails if uws fails to load)

**Comment by d3x0r** [comment]
Related; map fails if lib/file.js is not included

**Comment by amark** [comment]
I reverted back to `ws` for a while now, but still have `uws` that people can opt into (and may in the future make it default, maybe). But that should mean this issue is now resolved. Closing.
