### ISSUE TITLE
Doing a matching by two tags

### ISSUE THREAD

**Issue by linonetwo** [amark/gun#358]
Seems GUN can only matching data by one path, I'm wondering how I can matching data like this:

```javascript

gun.get('tags').path(tag1).intersect().get('tags').path(tag2).map().val((notes, tag) => {
      this.setState(prevState => ({
        results: [...prevState.results, notes]
      }))
    }))
```

In neo4j's cypher this is like:

```cypher
Match (tag1)->(result)<-(tag2) Return result
```

Can I do this graph matching in GUN? If not, will this be a future feature?

**Comment by amark** [comment]
@linonetwo yes, @Stefdv built a tagging extension/library for just this. However, I think he still needs to publish the 0.7 updates, so let me check in with him. (We've been chatting about possibly including it in the main gun repo)

Just to clarify, you want all the items in the UNION of 2 tags, right?

**Comment by linonetwo** [comment]
@amark Sorry for being ambiguous, I actually want intersection, since I'm building an offline cheat sheet for my exam, I need to find note that has two tags at the same time.

**Comment by Stefdv** [comment]
No promises because my current schedule is 'uncertain'  but i'll do my best to update 'guntagger' ASAP  ( like ...give me a week )

**Comment by amark** [comment]
@linonetwo this is now available in @Stefdv 's `npm install gun-tag` module using the `gun.intersect()` method on his tagging chain extensions.  Repo here: https://github.com/Stefdv/gun-tag . (I need to get this module published to the README soon!)

Closing! :)
