### ISSUE TITLE
So could I....

### ISSUE THREAD

**Issue by faddat** [amark/gun#368]
Use gun-level to connect gun to goleveldb?

Thanks, as always, for the inspiring and motivational docs.  I hope I learn to write docs like y'all one day :)

**Comment by amark** [comment]
@faddat sorry for the delay, things have been busy for me.

Thanks for those comments! :) I appreciate it.

I don't have a ton of experience with Level myself, but as long as goleveldb has a "levelDown" adapter, it should plug into gun's level adapter. I think?

**Comment by amark** [comment]
Since this isn't a bug in gun core that people need to be aware of pre-v1.0, I'm gonna close. Please feel free to add these sorts of things to https://github.com/gundb/feature-requests/issues though! Thanks.
