### ISSUE TITLE
gun.map.on bug when refreshing browser "Flickering Text"

### ISSUE THREAD

**Issue by omarzion** [amark/gun#375]
open the console and run `startNonsense(100)` then refresh a couple of times.  sometimes it console logs the final random string but sometimes it gets confused.

this was logged to console after a refresh
```
KOVUGBWSTE
KOVUGBWSTERFJ
KOVUGBWSTE
KOVUGBWSTERFJ
KOVUGBWSTE
```

```
let no = Gun('wss://notes.exceptionallyrecursive.com/gun');
window.onload = () => {
no.get('nonsense').map().on((blah => {console.log(blah)}));
}

function startNonsense(nonsenseCount) {
	let nonsense = '';
	let i = 0;
	
	let timer = () => {
		i++;
		nonsense += String.fromCharCode(Math.floor((Math.random()*24)+65));
		no.get('nonsense').put({ nonsense: nonsense });
		if (i < nonsenseCount) {
			setTimeout(timer, Math.floor(Math.random()*1000));		
		}
	}
	setTimeout(timer, Math.floor(Math.random()*1000));
}
```

**Comment by amark** [comment]
@omarzion apparently I was not following spec with GUN (which would explain why flicker was happening), but I have now fixed that. Please try upgrading to `v0.7.9` and see if this is still an issue? Thanks, let me know!

**Comment by omarzion** [comment]
@amark Sorry it has taken me so long to test this again  I wasn't able to reproduce the issue, v0.7.9 resolved the problem.  I even changed the timer from 1000 to 100 to no avail. great work!

**Comment by amark** [comment]
@omarzion awesome! Thanks for confirming. Closing then :)
