### ISSUE TITLE
Minor Documentation Updates

### ISSUE THREAD

**Issue by shdwjk** [amark/gun#378]
There are several places in the docs that refer to "It takes three parameters:" when the function actually only takes 2 parameters.  gun.get, gun.put

Additionally, the link for "Here is a list of such modules..." on the Gun constructor page is broken (Goes to http://gun.js.org/docs/Modules ).

**Comment by shdwjk** [comment]
On the back docs, the Chain context sentence is incomplete: 

> The context will always be different, returning you to the

**Comment by shdwjk** [comment]
hmm... thinking the docs on gun.js.org are outdated and I should be reading the ones on github instead... =D  Maybe the gun.js.org ones should be removed and should redirect to the github wiki?

**Comment by amark** [comment]
The gun.js.org should live scrape the wiki docs. So yes, any updates to the github wiki should be reflected there.

In the chat room you mentioned you already updated a couple things (super appreciated! We love it when people just jump in and help out). Thank you.

Shall we keep this issue open, or did your own fixes appropriately solve this?

**Comment by shdwjk** [comment]
Totally fine to close, I've fixed everything but the Modules link on the wiki.

**Comment by amark** [comment]
thanks so much!
