### ISSUE TITLE
Wiki footer does not support google analytics

### ISSUE THREAD

**Issue by tbodt** [amark/gun#379]
The result is pretty funny: 

<img width="731" alt="untitled 2" src="https://user-images.githubusercontent.com/5678977/27020041-92fbbf0a-4ef2-11e7-8fd3-521f408afd66.png">

**Comment by amark** [comment]
@tbodt thanks. Do you know of how to get around this? GitHub stats/analytics is extremely basic. Do you know any systems that work with GitHub?

**Comment by tbodt** [comment]
I'd recommend converting the wiki to a github pages site, which you can put google analytics on.

**Comment by karuppiah7890** [comment]
I noticed this too! But I am still looking for some workarounds

**Comment by amark** [comment]
Thanks @tbodt and @karuppiah7890 ! Also, the http://gun.js.org/docs/gun.html are generated from the wiki, just FYI.

**Comment by amark** [comment]
Since this isn't a bug in gun core, I'm gonna close. Would love it if somebody could spend some time and edit/update the wiki (you should have access) to fix this for me. Thanks!
