### ISSUE TITLE
localStorage's ACK not making it back to the callback

### ISSUE THREAD

**Issue by amark** [amark/gun#387]
:( need to be fixed.

**Comment by swhgoon** [comment]
#311

**Comment by amark** [comment]
This is either already fixed in `v0.8.0` or is now already fixed in my upcoming `v0.8.1` to be published. I even added in 0.8.1 that it globally logs the error (pretty much all errors in gun also get globally logged, but apparently the adapter ones aren't, I'll need to check other adapters as well). Gonna consider this closed. Expect it for sure in 0.8.1, but probably already now.
