### ISSUE TITLE
Deploy to Heroku link points to non-existing tree 0.5

### ISSUE THREAD

**Issue by karuppiah7890** [amark/gun#388]
The repo link (for template) is broken for the deploy to heroku button. I think it should point to the master tree. So it should be : 

`https://heroku.com/deploy?template=https://github.com/amark/gun`

**Comment by amark** [comment]
Oh, much thanks! Mind making a quick PR and I'll pull it immediately?

**Comment by karuppiah7890** [comment]
Sure! :)

**Comment by karuppiah7890** [comment]
@amark Done!

**Comment by amark** [comment]
Solved in #389 **because of you**! Thanks for jumping in and helping out :) :).

**Comment by karuppiah7890** [comment]
:smile:
