### ISSUE TITLE
S3 Storage: handling concurrent writes?

### ISSUE THREAD

**Issue by lordofthelake** [amark/gun#396]
Hi, the project looks awesome! 
I was looking for a simple solution for data persistence for my AWS Lambda function and the idea of a "NoDB" sounded very enticing.

I've seen that there is a built-in S3 backend for data storage. I was wondering: since S3 has an eventual consistency model for overwrites, how would Gun handle that in case of two lambda functions trying to write at the same time to the DB? Would some of the writes get lost?

Thanks!

**Comment by amark** [comment]
@lordofthelake sorry for the delayed reply, but super swamped with business stuff.

No, the S3 storage adapter is not currently designed to be used by multiple processes or machines simultaneously. HOWEVER, if both machines are receiving the same data sync/updates, they should converge to the same results because GUN will converge the data to the same results. But the S3 storage adapter does not do anything itself to handle that, and it currently assumes it is the only machine saving data. So do not trust this behavior unless you test it, and/or if/when we handle this if/when in the future.

@lordofthelake what are you working on? Would love to hear more!

**Comment by lordofthelake** [comment]
Ok so it works how I was expecting, no black magic that I had missed :D 
The project, per se, is nothing exceptional, but since a large part of it is about performing batch jobs (generating hundreds of images based on a template), I was exploring the feasibility of implementing it using only Amazon lambda functions (advantage being not having to pre-provision resources, handling well big surges of requests with minimal ops). So, basically, each request/job lives in its own process on some container spawned on-demand by AWS and ends its lifecycle when the job is completed.

Of course the weak spot of all of this is persistent storage. The solutions are typically either using something like DynamoDB, that although has a plethora of shortcomings (both in terms of features and scalability), using a third-party service (e.g. https://fauna.com/), or provisioning your own "traditional" DB somewhere.

So the idea of using Gun with S3 storage would have been interesting for my use case, if multiple processes were allowed to write at the same time. I'm aware that it's a tough nut to crack, because S3 has no locking mechanism (a common workaround is to use a DynamoDB table for locking, but this might be expensive performance-wise). I suspect that this could be worked around somehow by implementing the backend in a way that never writes to the same key (making it more like a log db, where writes keep to be appended to a file) and then periodically reconciling all the writes in a "master" file. But I guess that the complexity of all of this does not justify the typical use case of GUN :)

**Comment by amark** [comment]
@lordofthelake yes, in the current version of the S3 driver (I think you need to use 0.7.9 of gun), as long as each key has a different name, then you'll be good. Future versions batch nodes together though.

I definitely would not recommend using DynamoDB or Fauna, those are overkill for what you are wanting to do. Stupid question: Why not use S3 directly? GUN is well suited for this type of problem, you'd just need to customize an S3 storage adapter, which shouldn't be too hard.
