### ISSUE TITLE
Gun 0.8 huge memory usage

### ISSUE THREAD

**Issue by Stefdv** [amark/gun#405]
[gun-memory-issue.zip](https://github.com/amark/gun/files/1232163/gun-memory-issue.zip)

Importing 3000 nodes with 5 properties each.
Each node gets tagged to 6 tags.

Gun 0.7 takes about 30seconds to write a data.json of approx 4.5Mb
then i install Gun 0.8 and start the script again.

node mem usage will keep increasing untill finally it crashes with a "javascript Heap out of memory" error.
data.json will be 0 bytes.

**Comment by Stefdv** [comment]
Just read back in gitter...You ( @amark ) 
"I hope the difference from 0.7.9 and 0.8.x is purely the file adapter change" well...i'm afraid not i noticed the same behavior with @d3x0r  `gun-file` ( or gun-file is a modified version of file.js ?)

**Comment by sjones6** [comment]
I'm trying to track some memory usage while streaming key:value pairs from Gun-Mongo-Key. I'm not sure if it's related, but there does seem to be something going on with memory management.

Subscribed to this issue so I can see if it resolves anything for me too :)

**Comment by d3x0r** [comment]
@jsones6 are you using 'gun/gun' or 'gun' ?  if the latter, gun/lib/file is probably causing issues.  To isolate to just your adapapter you should require ( "gun/gun" ) and then your own adapater (".") or whatever :)

**Comment by sjones6** [comment]
@d3x0r: yep, using gun/gun so I shouldn't have the file adapter. Just gun core and an adapter

**Comment by Stefdv** [comment]
Closing this issue because https://github.com/amark/gun/pull/885#issuecomment-629623456

**Comment by amark** [comment]
@Stefdv what is the performance on this now? It should be much better over the years. And even better with upcoming CPU scheduler.

Plus, how are you doing??

**Comment by Stefdv** [comment]
Hey Mark, I only use RAD now so to be honest… id on’t know the performance of file.js
I’m doing great, although I have to make a project in VBA for my work ( MS Access ☹ ☹ ) I really don’t like VBA ;P  I’m good at it though 😊
Anyway not much time for Gun right now Although I did try ( and succeeded ) to use Gun and node-adodb to implement Gun. The problem is that I’m bound to an intranet so I can’t run a server ☹

I’m still following Gun on a daily basis but the whole SEA stuff is not really interesting to me

Tx for asking about me 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
