### ISSUE TITLE
Android Gun.JS

### ISSUE THREAD

**Issue by gillesfloret** [amark/gun#413]
Hello,

I would like to build an android application using GUN.JS as database. Any suggestions how to get GUN.JS running on android?

Thanks,
Jonas

**Comment by amark** [comment]
@gillesfloret are you okay with using Phonegap, Ionic, or similar? Those will be the easiest. If not, React Native is the best chance after that, as I know somebody has gotten it working.

(note: this isn't a bug in gun, so if possible it would be super duper appreciated if you could move it to this place https://github.com/gundb/feature-requests/issues . But yes, working examples of Android is definitely needed!!)

Hope you are doing well, would love to hear more about your project. :) Welcome aboard!

**Comment by gillesfloret** [comment]
Moved to https://github.com/gundb/feature-requests/issues/28
