### ISSUE TITLE
val() function returns undefined

### ISSUE THREAD

**Issue by sachinsawant71** [amark/gun#425]
I ran following code, but I get undefined printed 

`<!DOCTYPE html>
<html>
	<head>

		
		<meta charset="utf-8">
		<title>Hello World - GUN</title>
	</head>
	<body>

		
        <script src="https://cdn.rawgit.com/amark/gun/master/gun.js"></script>
        <script src="https://cdn.rawgit.com/amark/gun/master/lib/path.js"></script>

		<script>
            var gun = Gun("http://gungame.herokuapp.com/gun");
            var test = gun.get("sampleCache").put({
                character : {
                    mate : {
                        name : "test1",
                        age : 36
                    }
                }
            });

            test.get("sampleCache").path("character").val(function(value){
                console.log(value);
            });

        </script>
            <h1> This is a sample page</h1>
	</body>
</html>`

**Comment by amark** [comment]
@sachinsawant71 this is bad!! BUT...

I noticed you just closed it? Did you figure out that something was wrong with the example?

Is everything working correctly now?
