### ISSUE TITLE
Deeply nested records fail in set()

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#427]
Started at .... 

https://gitter.im/amark/gun?at=59d250647f323fc375f98e38
which also overflowed into this nonsense question.
https://stackoverflow.com/questions/46527646/only-a-node-can-be-linked-not-undefined

```
var Gun = require( 'gun' ); // although was testing in gun, so I used '..' 
var gun = new Gun();

watcher1 = { _id: 123, otherval:{a:4}} ;  // works
watcher2 = { _id: 124, otherval:{a:{b:4}}} ; // works
watcher3 = { _id: 125, otherval:{a:{b:{c:3}}}}; // fails

let task = gun.get(`watcher`).put(watcher3);

gun.get('tasks').set(task);  // this line fails.....
```

there are 2 extra lines. replacing the put(watcher3) with either 1 or 2 works... but at 4 nested levels it fails.

This fails, because file.js is emitting a put event with 'undefined' as the data... 
it's emitting because it's getting an event from ws.js

workaround:

    npm install gun-file 
   `require( 'gun/gun')`  // even disabling file by default causes same issue.... it's some driver thing
   `require( 'gun-file' );`

Although that then also needs a websock provider... it doesn't have the same error.

----

image is inspector stopped on the line that is 
``` cb.call(gun, {err: Gun.log('Only a node can be linked! Not "' + node + '"!')}) }```
the callstack for file.js is selected to show 'data=undefined'

![image](https://user-images.githubusercontent.com/1909610/31085004-d871ea36-a74a-11e7-9589-d01ca189acd8.png)

**Comment by amark** [comment]
@d3x0r thank you for such a detailed report, this contained useful and important information and was a valuable bug to report. And **thank you an extraordinary ton** for providing a work-around alternative in the meanwhile.

I have created a side-by-side comparison test here:

http://jsbin.com/vuripepizi/edit?html,js,console

That has the OLD gun version that runs first and produces `undefined` as reported with the error saying it cannot be linked.

THEN uncomment out the NEW version of gun (the HTML script tag) and comment out the OLD one.

Run again, and you'll see the CORRECT/EXPECTED output.

Am I missing anything else? I'm considering this **FIXED** in `v0.8.8+`, please reopen if you cannot replicate my fix in the JSBIN or elsewhere.

@d3x0r you are a super star, thanks for so much help and careful attention!

**Comment by sergibondarenko** [comment]
@d3x0r why the question is nonsense?

**Comment by amark** [comment]
@sergibondarenko was my StackOverflow answer helpful? Do things work now? Do you need any other help (I saw that Lorenzo is getting LetsEncrypt certificates to fix the https://github.com/sergibondarenko/gun-test problem).
