### ISSUE TITLE
Support Websocket Origin Check

### ISSUE THREAD

**Issue by buckle2000** [amark/gun#432]
> It is important (from a security perspective) to validate the "Origin" header during the connection establishment process on the server side (against the expected origins) to avoid Cross-Site WebSocket Hijacking attacks, which might be possible when the connection is authenticated with Cookies or HTTP authentication. It is better to use tokens or similar protection mechanisms to authenticate the WebSocket connection when sensitive (private) data is being transferred over the WebSocket.
from https://en.wikipedia.org/wiki/WebSocket

**Comment by d3x0r** [comment]
There's lots of reasons that the gundb might not be associated directly with the server serving the web content.
You can handle this by managing the websock connection yourself, again examples/http-external-ws.js demonstrates this.
