### ISSUE TITLE
How to use Gun as an express route?

### ISSUE THREAD

**Issue by john-doherty** [amark/gun#438]
I'm trying to use gun in an express/node project, however I want to mount the endpoint as `/db`.

I had hoped the following would work but keep getting an error `Route.get() requires callback functions`:

```js
var express = require('express');
var Gun = require('gun');

var app = express();
var port = 8080;

var gun = new Gun({
    file: './data.json'
});

app.get('/db', gun.router);

// start the server
app.listen(port, function () {
    console.log('Web server listening on port ' + port);
});
```

I have looked at the various express examples and even tried to read the Gun source but the lack of documentation/code comments adds an unnecessary layer of obscurity.

**Comment by amark** [comment]
@john-doherty thanks for asking this! And your SO question is better located (GitHub issues is for bugs), I replied here: https://stackoverflow.com/questions/46831742/how-to-use-gun-as-an-express-route/46837158#46837158 (and will therefore close this).

I hope that answer is helpful/informative! If you decide to implement the pseudocode I provide (in the SO answer) we'd love you to turn it into an NPM package that anybody/everybody could enjoy!

Also, in case you haven't seen this, here is the **documentation/code** you should check out (reading the source won't help you very much), here:

 - Interactive tutorial for beginners: http://gun.js.org/think.html
 - API documentation: https://github.com/amark/gun/wiki/API
 - Crash course on GUN: https://github.com/amark/gun/wiki/graphs

Cheers! Feel free to comment if you need any further help. :)
