### ISSUE TITLE
val() doesn't return object unless it's also map()ed

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#446]
Based on @sergibondarenko's question on https://stackoverflow.com/questions/47073902/gun-not-method-does-not-work-with-nested-nodes

node script
```
var Gun = require( "gun" );
require( "gun/lib/not.js" );

var gun = new Gun();
var app = gun.get('app');

//deleteDino('dino/velociraptor');
initDino('dino/velociraptor');

/*
app.get('dino/velociraptor').get('statistics').map().val(function(value,field) {
  console.log('value:', field, '=', value);
});
*/

app.get('dino/velociraptor').get('statistics').val(function(value,field) {
  console.log('value:', field, '=', value);
});

function deleteDino (name) {
    console.log( "delete called." );
  app.get(name).put(null);
}

function initDino (name) {
  app.get(name).not(function () {
    console.log( "not called." );
    app.get(name).put({
    	statistics: {
      	force: 5,
        speed: 17,
        intelligence: 23
      }
    });
  });
}
```

If the above script is run, its output is 'value: statistics = undefined'
If the commented section is uncommented, then the bare val returns 
```
value: statistics = { _:
   { '#': 'j9ig0s5s01atB7qnh5woXLA',
     '>':
      { force: 1509625460366,
        speed: 1509625460366,
        intelligence: 1509625460366 } },
  force: 5,
  speed: 17,
  intelligence: 23 }
value: force = 5
value: speed = 17
value: intelligence = 23
```
( the last three lines are from the map()... )  but the first value: statististics previously showed 'undefined'.

**Comment by d3x0r** [comment]
A separate issue with .not.  In the browser it appears not to fire ever.

**Comment by eallik** [comment]
in the browser, the `val` block works as expected even without the `map` block; also `not` gets called as expected.

**Comment by amark** [comment]
@eallik thank you for reporting that!

@d3x0r looks like this stuff got fixed? Will close soon-ish then. :)

**Comment by amark** [comment]
kk, gonna close. Please re-open if there is still a bug. Thanks!
