### ISSUE TITLE
Question: Is gun "safe" to use on the client?

### ISSUE THREAD

**Issue by alexpriceonline** [amark/gun#447]
I'm playing with `gun` and I'm loving it so far. I guess I want to know if it's _safe_ to us `gun` on the client (especially for `.put()` etc.)?

If I was building a react+redux app and my `gun.put` calls came from thunks for example, is that safe? Or is it better to do CRUD operations on the server and just use the Gun client library for `.on()`?

I'm asking about best practices for prod apps basically! Thanks

**Comment by amark** [comment]
@alexpriceonline thanks, glad to hear! :) :)

And welcome to the community!

What do you mean by "safe"? Yes, you can perform `put`s from the browser. You also could do it server-side behind some CRUD (but then you'd have to manage AJAX calls and stuff yourself, which sucks. GUN handles browser/server communication for you out of the box).

By "safe" do you mean, is there any security or something that prevents spam? You'd need to run SEA (which is in alpha), you can learn more here: https://github.com/amark/gun/wiki/auth . Without SEA, everything is unfiltered, with SEA updates can be verified.

Welcome aboard! What are you building?

Also, helpful tip: The http://gitter.im/amark/gun is best for getting help, and StackOverflow using the "gun" tag is best for asking questions like this, and GitHub issues are reserved for bugs. Could you do me a favor and copy&paste your question into StackOverflow and copy&paste my answer? Then we can continue the conversation there :) and I'm gonna close this as not being a bug here. Thanks!

**Comment by alexpriceonline** [comment]
Thanks @amark! Here's the SO post: https://stackoverflow.com/questions/47111219/is-gun-js-safe-on-the-client I thought it might be best for you to post your answer so I left that out. Looking forward to a continued conversation and sorry for posting in the wrong place!

PS. I've got a few projects I'm looking to rebuild using a modern stack. I'm hoping gun will be what I'm looking for (so far it looks it!). I'll also be happy to contrib if it's the right fit <3

**Comment by amark** [comment]
@alexpriceonline I have like 0 time, it would be super <3 <3 appreciated if you could repost it for me, saves me time to work on gun, fix bugs, and help answer/support people like you. :)
