### ISSUE TITLE
Deeply-nested writes overwrite unrelated data

### ISSUE THREAD

**Issue by axxag** [amark/gun#448]
Given the following nested data structure:

```javascript
{
  "userData": {
    "group123": {
      "clients": {
        "client123": {
          "name": "Test Client",
          "email": "testClient@gmail.com"
        }
      },
      "stores": {
        "stores123": {
          "name": "Test Store",
          "address": "123 happy ln"
        }
      }
    }
  }
}
```

Deep `put()` calls on either `clients` or `stores` blanks out the entire structure. If I flatten the structure by 1, writes resolve normally.

Here's a JSBin highlighting the issue.
http://jsbin.com/qexubizela/edit?js,console

**Comment by amark** [comment]
@agentilela MUCH appreciated for reporting this. I had just fixed a similar bug but somebody had been saying they were still seeing a problem but I was having a hard time replicating. This must be it. Thank you. Will fix.
