### ISSUE TITLE
Heroku Push failed

### ISSUE THREAD

**Issue by itsazzad** [amark/gun#449]
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  >=0.6.6
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >=0.6.6...
       Downloading and installing node 9.0.0...
       Detected package-lock.json: defaulting npm to version 5.x.x
       Bootstrapping npm 5.x.x (replacing 5.5.1)...
       npm 5.5.1 installed
-----> Restoring cache
       Skipping cache restore (not-found)
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       /tmp/build_be5d323d934b546e3d87234e0a170a57/amark-gun-f8f76d9/.heroku/node/bin/node[236]: ../src/node_zlib.cc:430:static void node::{anonymous}::ZCtx::Init(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
       1: node::Abort() [npm]
       2: node::Assert(char const* const (*) [4]) [npm]
       3: 0x1251ea1 [npm]
       4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
       5: 0xb74c3c [npm]
       6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [npm]
       7: 0x1b3779842fd
/app/tmp/buildpacks/19862b8792e84bd8421ded4660b92dfd1c41d92e19ac0b38c90301adc8ae3e0bd512fa01998af18fc2f0d31a157e9c82e8fdceba1a05e5d29adb8dc2bfaf08e1/lib/dependencies.sh: line 85:   236 Aborted                 npm install --unsafe-perm --userconfig $build_dir/.npmrc 2>&1
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by amark** [comment]
@itsazzad thanks for reporting this, it looks like Heroku has started rejecting older NodeJS ranges. This should be easily fixed by upping gun's package.json "node" engine (or perhaps deleting it altogether? I don't understand why it is necessary). I don't have much time currently, do you think you could try making a couple local variations that you experiment with heroku with? And then the "right combo" that you find (which might happen on the first try) you make a PR for? That'd be appreciated!

**Comment by amark** [comment]
I just tried pushing to Heroku and it is all good now. I bumped the package json number. :)

@itsazzad try again? Also, would love to hear what you are working on!

**Comment by itsazzad** [comment]
@amark thanks for the update!
I was just tried to play with this for one of my pet projects to be available in web/android/ios.

**Comment by amark** [comment]
@itsazzad any links? :)

**Comment by Korbraan** [comment]
Just had the same problem. I switched to the LTS version of Node and I do not set the npm version on package.json anymore (so Heroku use the one packaged with Node), seems to work.

**Comment by amark** [comment]
@Korbraan thanks for bringing this up - did your fix work? Mind sending a PR to patch?

I'm guessing Heroku just bumped their NodeJS whitelist again and I'm out of date. Or something else?
