### ISSUE TITLE
Questions about performance & server use case

### ISSUE THREAD

**Issue by selforganized** [amark/gun#452]
I stumbled upon Gun. It looks great. Regarding the benchmark (https://github.com/amark/gun/wiki/100000-ops-sec-in-IE6-on-2GB-Atom-CPU):

- what does an "op" in 80M ops/sec mean? Is it 80M gets/sec? 80M puts/sec? If so that is incredible, is this from a single-threaded program?

- are puts sync'd to disk? Does synchronous write reduce performance significantly?

- can Gun be used as a k/v store on server? I'm looking for a kv store that can handle >100GB of data at >10M rps (mostly gets but also some puts). Is Gun a good fit for this use case? Will there be significant GC pause because of the size of data?

Thanks.

**Comment by amark** [comment]
@selforganized greetings! These are great questions, would you mind reposting them (and my answer here) to StackOverflow instead, so more people will see it?

The performance is currently 20M ops/sec (Chrome canary no longer does 80M ops/sec in the current version). These are cached reads, similar to the same tests that Redis does. Yes, single-threaded. Take these tests with a grain of salt though, they represent a baseline that databases test against, but isn't not a real-world test.

Yes, puts are saved to disk. Whether it is done synchronously or not depends upon the storage adapter. For instance, the localStorage (in the browser) used to be synchronous, but now it has a 1ms throttle to prevent thrashing.

Yes. We tested an experimental storage driver (not currently available) a year ago that handled [100GB+ data a day](https://www.youtube.com/watch?v=x_WqBuEA7s8), successfully. The [new radix storage engine](https://www.youtube.com/watch?v=nTbUCTgLmkY&t=90s) (almost available) has been [tested alright](https://www.youtube.com/watch?v=w0_5rTl7a6M) (across 25M writes), but the current storage adapters have not been tested at that scale (the default adapter definitely won't, however the other adapters might). We can provide support for you/your-company to help you though if you have any hiccups (I'd love to hear more about your system!).

GC is something we've been working on with these larger storage engines, we certainly had pauses but the systems were able to continue for days at a time with constant load (thousands of writes a second). I've been manually doing GC on some of the more recent tests, so I cannot comment fully yet. Wait a bit and we'll have some engineering tests for you to back up our claims. :)

Cheers!

**Comment by selforganized** [comment]
Thanks Mark.

I don't have a stackoverflow account. Please feel free to post my question there. Thanks again.
