### ISSUE TITLE
Method .open(cb) callback doesn't fire when value is undefined

### ISSUE THREAD

**Issue by sergibondarenko** [amark/gun#457]
I think it should return `undefined`, like `.val(cb)` does in such case.
Look below, `alert(v)` is never triggered.

Code 
```
var gun = new Gun();
var park = gun.get('park');

park.get('brontosaur').open(function (v) {
 alert(v);
});
```
jsfiddle https://jsfiddle.net/sergibondarenko/ja9hw8zd/

**Comment by amark** [comment]
merging this issue into https://github.com/amark/gun/issues/770
