### ISSUE TITLE
ACL-like properties

### ISSUE THREAD

**Issue by xelius** [amark/gun#469]
First, Mark & Co - great work with Gun! I've been following the project for some time. 

I really like the core philosophy behind Gun. What usually kept my use cases away, so far, have been lack of auth and ACL features. But that might be changing with the recently added SEA stuff (Yeay!). However, admittedly, I'm not completely up to date w the SEA changes. 

So a couple of questions, pls bear with me:

If I would like ACL features, like restricting read and/or writes for certain data for individual users or groups of users, can current SEA handle that? Or would I have to implement that in my app layer? 
If so, any recommendations on how to go about it, building on current SEA capabilities?
And, lastly, is it on the roadmap for Gun to handle this by itself?

Thanks and keep up the good work.

**Comment by amark** [comment]
@xelius thanks for the nice words :) very much appreciate that.

SEA will be able to handle that, but currently...

SEA can only handle key/value writes on root level accounts that are created. These writes are public-read, but write-restricted to the only the account (nobody can tamper).

My next step up is getting full graph data to be written to accounts.

Then after that, we'll be able to introduce a `data.trust(user)` which will allow for multi-user write (shared objects), but still public-read.

Then after that, we'll try to introduce a new method that abstracts doing private-reads. This can be done already with the SEA utilities though, if you don't want to wait, you can do it now, but I'd need to explain it more, or @mhelander (who has been awesome and contributed most of SEA).

@xelius so "yes" :) but "not yet" :( so hang in there!!! What are you planning on building? Welcome to the community! Glad you have been keeping your eye on it. :)

**Comment by amark** [comment]
@xelius we announced over the weekend that full graph support works no on account data, plus here is a tutorial: https://hackernoon.com/so-you-want-to-build-a-p2p-twitter-with-e2e-encryption-f90505b2ff8 .

Also, I'm going to move (and update the title of) this issue to the issue that has been discussing it for much longer: https://github.com/amark/gun/issues/321 , and close this one, but please continue conversation in the other one!

**Comment by xelius** [comment]
Thanks alot for the quick anseers (and work!). It seems promising. I’ll look at that tutorial for sure, more documentation like that is really appreciated. I’m sure I’ll bother you again though ;)
