### ISSUE TITLE
Trigger server functions?

### ISSUE THREAD

**Issue by sebastianmacias** [amark/gun#470]
I'm evaluating gun for a project and was wondering if there is a way to trigger server only events when data is modified.

For instance if I'm building a commenting application I might want to send an email when a new comment is posted, or in a photo app maybe I might need invoke a lambda function that resizes a picture when photo node is added to a gallery.

Firebase [has](https://firebase.google.com/docs/functions/database-events) onWrite(), onCreate(), onUpdate(), onDelete(), this events.

Is there anything similar in gun.js?

**Comment by amark** [comment]
Greetings @sebastianmacias :) welcome to the community! (How'd you hear about gun?)

Yes, the GUN API works the same way on a NodeJS server as they do in the browser!

So you just do `gun.get('key').on(cb)` to listen to updates. You may enjoy the extended API (see the docs) which has `.open(cb)` and `.load(cb)` which may be better suited to your task. Which is what the Firebase shim uses: https://github.com/amark/gun/wiki/shim.js

Anything else? Closing for now! Cheers! :)

**Comment by sebastianmacias** [comment]
Hi @amark,

I had gun on my "decentralize everything" bookmarks folder for a while. I'm not sure about how I first found out about it, maybe it was a google search for "decentralized offline first databases", maybe it was something completely different.

So far I'm very impressed with the performance. You have done an amazing work on that end.

Things I'm looking forward to: 

* ACL (a must for every project I work on)
* webrtc, orbit-db, ipfs or similar support to make gun.js a first of its kind, truly decentralized, p2p, serverless dream db

I will let you know when I run into anything else.

Cheers!
