### ISSUE TITLE
Can I change or update key of record?

### ISSUE THREAD

**Issue by ohenepee** [amark/gun#492]
For some reason I wish I could do this.

**Comment by amark** [comment]
gun.js.org/think.html shows how. :)

**Comment by ohenepee** [comment]
Actually I mean changing the key itself not the record

**Comment by amark** [comment]
Oh, I understand you now. You should be able to resave the reference under a new key in the table like (on phone so pardon the code)

var ref = gun.get('mark') // reference to old object
gun.get('table').get('newkey').put(ref)

Does that help?

What are you working on building? How'd you hear of gun? :)

**Comment by ohenepee** [comment]
I heard about it from your awesome YouTube JS Performance video. Which was referenced somewhere else (Github/Stackoverflow). I love performance.. so I kinda always search performance-oriented stuff

**Comment by ohenepee** [comment]
I'm building a tree graph app... I think I've got a hand on Gun now... but I have another problem...  its there any way I can create a family tree of this structure?

`parent -> 2 children -> each child will also have 2 children -> on and on with 2 children each`

can be as deep as can be. Is there any way to query such a tree to get all member/persons that are at a certain level deep... say from `parent` to `4th generation`? I've been thinking about how to achieve that with Gun... else I'll have to look for any other Graph db in NodeJS... ( I don't want to move outta the NodeJS ecosystem... so no Neo4J and the likes)

**Comment by amark** [comment]
Glad you like perf.

.open does what you want for all children depth, it is a tiny module, so you can easily modify it to support limited depth. Let me know how it works!
