### ISSUE TITLE
Dockerfile missing npm installation

### ISSUE THREAD

**Issue by relloyd** [amark/gun#493]
It appears as though the Dockerfile is missing installation of `npm`.  For example, apk package `nodejs` does not include `npm` as the time of writing.  This needs changing to get `nodejs-npm` as follows:

Change
`
  && apk add  --no-cache ca-certificates nodejs \
`
to
`
  && apk add  --no-cache ca-certificates nodejs-npm \
`

**Comment by amark** [comment]
@relloyd thank you!! Do you want credit for this? If you submit it as a PR I'll pull. :)

**Comment by relloyd** [comment]
Great, thanks.  PR on its way.
