### ISSUE TITLE
Add .map to Gun Core

### ISSUE THREAD

**Issue by alexlafroscia** [amark/gun#5]
Adding `Gun.Chain.map()` would be really useful in moving toward some sort of "array support".  It would also be handy if this method returns a promise that resolves when iteration is complete.  I ran into a situation where I wanted to call `$scope.$apply()` after iteration was complete, but didn't know how to postpone that call until the `.map()` was complete.

**Comment by amark** [comment]
I'm working on this, including adding `.insert` to core. However I found out about the big bug, so now I'm working on that as well. Thanks for helping, tremendously.

**Comment by amark** [comment]
Thanks.
