### ISSUE TITLE
Docs: starting a gun server

### ISSUE THREAD

**Issue by Leland-Kwong** [amark/gun#500]
When I click the link for [starting a new gun server](https://github.com/amark/gun/wiki/Running-a-GUN-Server-\(v0.3.x), it takes me to the "create a new page" dialog in github? Is there any documentation on how to get a gun server up?

**Comment by robertheessels** [comment]
We working on new documentation for that.

But the old page is still there. You seem to have the last character misssing in that url.
Correct is:
https://github.com/amark/gun/wiki/Running-a-GUN-Server-%28v0.3.x%29

Where did you find that link?

**Comment by Leland-Kwong** [comment]
@robertheessels Thanks, I found the link [here](http://gun.js.org/docs/Next-Steps). Also, the instructions to setup a gun server from scratch doesn't work since `gun.wsp` is `undefined`. Using the **gun-server** npm package works though.

**Comment by Leland-Kwong** [comment]
Actually, I just updated the docs based on the chat example from the latest npm package (0.9.x).

**Comment by robertheessels** [comment]
Thank you for that!

The page is now in the docs menu: http://gun.js.org/docs/How-to-Run-A-GUN-Server

**Comment by Leland-Kwong** [comment]
Sure thing!
