### ISSUE TITLE
Consider moving the console message on `require` to an install hook

### ISSUE THREAD

**Issue by Niggler** [amark/gun#523]
The message in https://github.com/amark/gun/blob/master/src/root.js#L207 will always display in nodejs.  @amark it is obviously your decision whether or not to include this message on require, but note that other projects like Babel insert one-off messages in the installation process.

**Comment by amark** [comment]
If it is only printed once upon installation, most people won't ever notice or see it, and frontend developers would also likely never see it either. So this is going to stay.
