### ISSUE TITLE
How far does the Offline-first feature go ?

### ISSUE THREAD

**Issue by Xsmael** [amark/gun#529]
I would like to know how the data is persisted(saved) on the device, does it survive a reboot ? or a restart of the browser ?

**Comment by amark** [comment]
@Xsmael it depends on the device. In case of the browser, localStorage is used and can survive reboot, reload, etc.

If it is in NodeJS, most storage adapters (the current default file.js, the upcoming default RAD, and others) store to disk (and even some, to S3, IPFS, etc.) which survive reboot and can even migrate between machines (like with Heroku) for the latter adapters.

@Xsmael it would be 100% awesome if you could port this question to StackOverflow tagged as `gun`, and paste my answer in. This would benefit a ton of other people. We try to use GitHub for bug reports, not Qs, so I'm gonna close this. I hope to answer more Qs from you on SO and help out via the chatroom!!! Welcome!! :)

**Comment by Xsmael** [comment]
Done! 

where do i get the chatroom ? I have more quetions, especially concerning the future of GUN 

Thanks again!

**Comment by amark** [comment]
https://gitter.im/amark/gun :D 

And thanks for porting the Q to SO!
