### ISSUE TITLE
Handling connect/disconnect status & get online users

### ISSUE THREAD

**Issue by sbehrends** [amark/gun#531]
Is it possible to execute functions when server is connected/disconnected? Principally to give user information about connection status.

Is it possible to get the amount of users connected?

Thanks!

**Comment by amark** [comment]
Hey @sbehrends ,

`gun.on('hi', peer => console.log(peer))`

and

`gun.on('bye', peer => console.log(peer))`

Should help? Is that what you want?

You can create a presence system with gun, by having users ping their account with a heartbeat of when they were last online. You can then have other peers subscribe to these heartbeats to see if they are online.

If you are okay with building centralized server logic (I encourage people to build P2P/decentralized apps, instead, though), you could do something similar to what is suggested on the Firebase shim page:

https://gun.eco/docs/shim.js

Also, huge helpful request: We use GitHub issues for bugs, but we want good questions like this to be available on StackOverflow tagged `gun`. Could you please copy&paste your Q and my A there, so others could see it? Really helps out. And if you have any further questions, I'll answer it further there. Thanks a ton!!!

**Comment by sbehrends** [comment]
Oh, didn't see this in the docs. Sorry about that 👍 
Thank you very much!
