### ISSUE TITLE
Support for spatial index

### ISSUE THREAD

**Issue by dioptre** [amark/gun#532]
Hey guys,

Just wondering if you could use gun for spatial. Wondering if there are any use-cases?

Thanks
Andrew

**Comment by amark** [comment]
@dioptre hey :) sorry for the delay, been a hectic week.

There has been a decent amount of GPS data done on GUN, however 2D spatial fencing/whatever there isn't any plugin. However, if you know how to convert the coordinates into a key (what I've heard from others... it is a Hilbert Curve of the GPS coordinates, it blew my mind, such a great idea, IDK if that is how it actually works though) then that would work great.

So for now, you'd need to figure it out. But it is something we'd like to support in the future.
