### ISSUE TITLE
Timegraphs initial load very slow

### ISSUE THREAD

**Issue by robertheessels** [amark/gun#544]
The initial load of a timegraph is very slow (5-10 secs) even with only a few items.

This is when connected to a super-peer over the Internet. When not connected to peers it's super fast.

Seems like it does not use the local cache?

**Comment by amark** [comment]
@robertheessels possibly (not sure) related to async/sync bugs, but either way I've improved GUN, SEA, and timegraph. Could you try again and see if this is fixed?

**Comment by amark** [comment]
gonna merge this with https://github.com/amark/gun/issues/638 and consolidate with the generic "timegraph is buggy" title, please follow that newer issue now for this as well.
