### ISSUE TITLE
sea.js bug for boolean set and get error

### ISSUE THREAD

**Issue by Lightnet** [amark/gun#545]
Tired to test which part was bugged which seem sea.js auth is not allowing true and false Boolean type and null. But string bool as string did work. I tired to work with out sea.js and it worked find. Guessing it valid string only in sea.js.

**Comment by amark** [comment]
@Lightnet good catch, I'm guessing this and https://github.com/amark/gun/issues/554 are related. Still needs to be fixed though.

**Comment by amark** [comment]
@Lightnet I believe this is fixed for booleans in latest:

```javascript
;(async function(){
var pair = await SEA.pair();
var sig = await SEA.sign(false, pair);
var val = await SEA.verify(sig, pair);
console.log(val); // false;
}());
```

and

```javascript
;(async function(){
var pair = await SEA.pair();
var sig = await SEA.sign(true, pair);
var val = await SEA.verify(sig, pair);
console.log(val); // true;
}());
```

`null` still causes a crash (currently) but I've fixed it in my latest code and it should be out in the next release `0.9.99993`. So I'm gonna go ahead and close this. :) If you find anything else, please let me know! Thank you for reporting this @Lightnet !!!

How are things going, BTW?
