### ISSUE TITLE
Suggestion: Use minio instead of S3 client

### ISSUE THREAD

**Issue by ericvicenti** [amark/gun#546]
Hey Mark! I'm a big fan of your work here.

I notice you use the AWS library directly for working with S3. Instead of relying on a proprietary service, maybe gun could switch to minio client so that people can self-host, or use another cloud provider, instead of using Amazon's cloud? Minio provides API compatibility, so nothing should break for existing S3 users.

https://www.minio.io/

(I'm not affiliated with Minio. I'm just a follower and I think it would be a perfect compliment to gun)

**Comment by robertheessels** [comment]
+1 for Minio. I plan on using Minio myself and might be able to work on this in the next few months.

**Comment by amark** [comment]
@ericvicenti thank you! :) :) :) Yes, I absolutely agree, the goal of even the S3 adapter is that it can even be swapped out for IPFS or Minio or others!

In Minio's case, it is already S3 API compatible, so all you should have to do is change the configuration settings (something like ?? `AWS_ACCESS_POINT` ?? to point to your minio URL)

If not, it shouldn't be too hard to write a minio-specific adapter with RAD, if you want @fuchidahiro  can help you with docs.

Gonna close though, as this isn't a bug. I'd **love** it if somebody could write a How-To guide for it though (if you will, and you need help, ping me and I'll explain whatever is needed to make it happen!).
