### ISSUE TITLE
Radisk Not Loading Data From Timegraph

### ISSUE THREAD

**Issue by masterex1000** [amark/gun#547]
Recently I came across the issue that, when using radisk, the timegraph extension doesn't load data from the disk. 

```javascript
const Gun = require("gun");

var gun = Gun({localStorage: false})
require("gun/lib/time.js");

var g = gun.get("time");

g.time((data, key, time) => {
	console.log(data);
}, 100);

g.time("data");
```

In order to test all that you need to do is run the script multiple times, I have verified that radisk is writing the time graph nodes to the disk, (ctrl-f <whatever string I put in the time graph> in the db file) The script should print out the last 100 objects added to the db, which it does when not using the radix storage.

**Comment by amark** [comment]
@masterex1000 excellent test case to reproduce against, thank you! Will add this to the important fix list.

**Comment by amark** [comment]
@masterex1000 I was hoping the async/sync fixes would fix this. But I tried... and nope. So it must still be a RAD issue. Me and @fuchidahiro are working on RAD next to get it stable.

**Comment by amark** [comment]
gonna merge this with https://github.com/amark/gun/issues/638 and consolidate with the generic "timegraph is buggy" title, please follow that newer issue now for this as well.
