### ISSUE TITLE
What happen if Gun node server die ?

### ISSUE THREAD

**Issue by jackynguyen93** [amark/gun#548]
First, sorry for my lack of knowledge.
I have some questions: 
1. If I host a node gun server and all clients use this gun server (instead of community server). So what happen if my gun server dies, will all data be lost? or it still in the local of client and will sync back when the server goes live again?
2. Will the server store whole data json or just its encrypt keys ?

**Comment by robertheessels** [comment]
All clients try to cache as much data (that they subscribed to) as possible. In the meantime they just keep working.
When the server comes back online everything is synced again.
If the server has lost it's data, it will receive and restore all data that was still cached in the clients.

**Comment by jadbox** [comment]
@robertheessels by default the Gun server is memory persistence only? Is there an option to use disk?

**Comment by robertheessels** [comment]
It can do normal file storage (for debugging), Radix (for Amazon AWS S3 storage) and several other options build by others.

**Comment by amark** [comment]
@jackynguyen93 @jadbox would love it if you could copy&paste this Q and the A to StackOverflow tagged `gun` :) so others can see this awesome Question and @robertheessels 's answer!

Gonna go ahead and close now, please re-open (or add to StackOverflow - even better!) if you need anything else. :D
