### ISSUE TITLE
SQL-like Parser

### ISSUE THREAD

**Issue by metasean** [amark/gun#55]
Addition of SQL-like query functionality

**Comment by Xe** [comment]
I'd like to take this on if possible.

**Comment by amark** [comment]
@Xe yay! Yes please. We're getting close to the new release that will allow for it.

I got your message on gitter, sorry I haven't replied yet. Was at a meetup when I got it, and now working on getting this new release out... hopefully in the next few weeks.

**Comment by metasean** [comment]
Moved to https://github.com/gundb/gun-extensions/issues/14
