### ISSUE TITLE
Is there a gun database gui ?

### ISSUE THREAD

**Issue by anlexN** [amark/gun#550]
it's a nightware with gui for checking my data.

**Comment by amark** [comment]
@anlexN welcome to the community :) !

There are some playground ones, like:

https://github.com/lmangani/gun-scape

The other one somebody built... looks like they deleted their GitHub account :( so I can't find it.

Do you want to help build one?

**Comment by anlexN** [comment]
i am gun starter, don't master gun. so give me some time. can you train me?

**Comment by amark** [comment]
@anlexN yes!!! :) Sorry for the delay... I've been pinched on time on all sides. If you want to help build a UI system please join the https://gitter.im/amark/gun and ping me and we/others can work towards this!

I am gonna close this though, as it technically isn't a bug (but a feature request). But lets make it!!
