### ISSUE TITLE
Node always being signed after user.auth

### ISSUE THREAD

**Issue by sundaywork** [amark/gun#553]
After user.auth, the put will always add signatures to all fields, even it's not under the "user" node and at the root level.

```
const gun = Gun();
const trans = gun.get("trans");

var d = '{"index":2,"timestamp":1527753636152,"action":"out","amount":"66.6666"}';
var n = JSON.parse(d);
trans.get("AAA").put(n);

var SEA=Gun.SEA;

var user = gun.user();

user.auth(myName, myPass, (ack)=>{
    console.log(`logged in as ${ack.alias} pub key=${ack.pub}`);

    trans.get("BBB").put(n);
    gun.get("_trans").put(n);
});
```
The pictures below showed the difference between plain text node and signed node:
![image](https://user-images.githubusercontent.com/5270094/40975390-e8e9db1c-691e-11e8-9a09-b995e8a39a2b.png)
![image](https://user-images.githubusercontent.com/5270094/40975439-137c5508-691f-11e8-9963-f7bc571acfbb.png)

Expect: data is not signed under normal locations, unless inside the user node. Or a mechanism to allow exit the auth so I can go back to put plaintext data.

**Comment by amark** [comment]
@sundaywork due to multiple people requesting this feature (this wasn't a bug, but intentional), I have switched it that non-user `put`s don't sign. Try it out! Let me know if you have any issues. Elsewise, should be implemented now so I'm gonna close. Please reopen if need be!
