### ISSUE TITLE
Empty string being interpreted as \"\"

### ISSUE THREAD

**Issue by sundaywork** [amark/gun#554]
When putting an object with a field being an empty string, the signature function will take "" as "\"\"". See
![image](https://user-images.githubusercontent.com/5270094/40977053-ff8aee42-6923-11e8-9f4d-647f72392b81.png)
Ref: #553
which in some cases trigger the message of "NO! Mismatched owner on 'data'." Haven't figured out what makes this happen.
![image](https://user-images.githubusercontent.com/5270094/40977183-56071520-6924-11e8-92fb-449d982e88fe.png)

**Comment by amark** [comment]
Related to https://github.com/amark/gun/issues/545 I think, still needs to be fixed though.

**Comment by amark** [comment]
@sundaywork this should be fixed now in latest: (I did a quick test, and it works the way we expect...)

```javascript
;(async function(){
var pair = await SEA.pair();
var sig = await SEA.sign('', pair);
var val = await SEA.verify(sig, pair);
console.log(val); // '';
}());
```
