### ISSUE TITLE
How to Turn Off GUN console log Debug Info (MB rss, MB hT, hU, peers, nodes, etc.)

### ISSUE THREAD

**Issue by irthos** [amark/gun#555]
hey mark, by just requiring gun in node, I get the following stream of meaningless annoyance in the console. Is this normal operation or perhaps my multithreaded networking is inadvertently retriggering?

15.0 MB rss. 10.3 MB hT. 6.8 MB hU.
15.0 MB rss. 10.3 MB hT. 6.8 MB hU.
15.0 MB rss. 10.3 MB hT. 6.8 MB hU.
15.0 MB rss. 10.3 MB hT. 6.8 MB hU.
15.0 MB rss. 10.3 MB hT. 6.8 MB hU.
15.0 MB rss. 10.3 MB hT. 6.8 MB hU.
15.0 MB rss. 10.3 MB hT. 6.8 MB hU.
15.0 MB rss. 10.3 MB hT. 6.8 MB hU.
17.4 MB rss. 8.8 MB hT. 6.0 MB hU.
17.5 MB rss. 8.8 MB hT. 6.0 MB hU.
17.5 MB rss. 8.8 MB hT. 6.0 MB hU.
17.5 MB rss. 8.8 MB hT. 6.0 MB hU.
17.5 MB rss. 8.8 MB hT. 6.0 MB hU.
17.5 MB rss. 8.8 MB hT. 6.0 MB hU.

**Comment by amark** [comment]
```
process.env.GUN_ENV = "false";
var Gun = require('gun');
```

We have temporarily made the `debug` mode turned ON by default. I know it is annoying, it will only be for a couple version releases, then we will turn it OFF by default.

Sorry about that! The above code should turn it off.

**Comment by irthos** [comment]
Cool I sorta figured. Thanks for swift and informative response!

**Comment by amark** [comment]
No problem! :) actually let's keep this open until we turn it off, I think that will be helpful to others? Thanks for closing it though, I appreciate that!

**Comment by xaiki** [comment]
i guess the issue here is that having Gun 'do anything' before it's asked is a bit uncomon (annoying ?) doesn't it make sense to start working on Gun() ?

**Comment by amark** [comment]
@xaiki agreed, again this is just temporary until we have RAD fixed (which latest commit might land the most important updates... still gotta do tests, we'll see) and we have nice concurrency.

**Comment by amark** [comment]
@irthos @xaiki logs are now turned OFF by default in latest GUN versions. Enjoy! :)
