### ISSUE TITLE
Node.js rename file doesn't work if oldPath and newPath are in different partitions

### ISSUE THREAD

**Issue by dfreire** [amark/gun#558]
I am using GUN inside a docker container attached to a storage volume.

When I try to save data I get an error:
`Error: EXDEV: cross-device link not permitted, rename '/data-esi.tmp' -> '/data/!'`

This happens because renaming a file across partitions doesn't work.

`lib/store.js` is using nodejs `rename(...)` method which is causing the problem.

**Comment by amark** [comment]
@dfreire thanks for the report! You had mentioned earlier you have a fix that you can make as a Pull Request?

**Comment by dfreire** [comment]
I'm working on it... just a sec.

**Comment by amark** [comment]
Thanks for the PR! Accepted. Closing.
