### ISSUE TITLE
Gun load balancing and replication

### ISSUE THREAD

**Issue by jadbox** [amark/gun#560]
Is it possible for the servers to rely communication to other servers, so that the client only needs to connect to one server? I'd like to set up a load balance cluster where each server relies its data to the other servers in the cluster.

**Comment by jadbox** [comment]
I've found this issue: https://github.com/amark/gun/pull/267

Although I'm not sure what the proper set up is. A server can be a client of another server... does that mean there needs to be one "master" server that all the client servers point to?

**Comment by amark** [comment]
@jadbox welcome!!!! :) :) :)

I'm not sure if you tried this or not, or just asking? GUN is pretty good out of the box relaying data between peers, even if they aren't connected. Especially in the case where browsers need (unfortunately) a bootstrapping peer.

There is no "Master" in GUN, every peer is a master. Some peers are just stronger/better than others.

Sharding is not needed either.

Try running the examples and you should see that your questions are answered, if you need help running them just ask on https://gitter.im/amark/gun . If you are reporting a bug, please re-open this. If you are just asking questions (that is great!), I'm not exactly sure how to answer them other than "Yes!" :P which isn't very helpful, and why I think the chatroom will be good for you.

**Comment by amark** [comment]
Or maybe I misunderstood what you were asking?
