### ISSUE TITLE
Browser CDN for core gun plugins (path, not, load)

### ISSUE THREAD

**Issue by jadbox** [amark/gun#570]
The Gun docs are a little frustrating as it shows how to import Gun through a cdn via `<script src="https://cdn.jsdelivr.net/npm/gun/gun.js"></script>` but then only provides relative paths to the core Gun plugins: 
`<script src="<script src="/gun/lib/path.js"></script>"></script>`. What the proper way of bringing in those plugins to my project? I'd prefer not to manually copy those plugins into my project. Ideally each of the plugins should be available via a public cdn, perhaps part of a build script?

**Comment by jadbox** [comment]
Discovered the proper path is as follows. I'd recommended updating the docs to use the CDN path for the core plugins.
`<script src="https://cdn.jsdelivr.net/npm/gun/lib/not.js"></script>`

**Comment by amark** [comment]
@jadbox thanks for observing this, could you super-pretty-please click "Edit this Page" in upper right of docs, and add/change this? (the more we can get people like you making these quick/easy edits, the 700% better the wiki docs will become.)

**Comment by jadbox** [comment]
@amark I feel that. I've made the edits to the wiki.
