### ISSUE TITLE
Node.js: non-persistence gun constructor issue

### ISSUE THREAD

**Issue by jadbox** [amark/gun#571]
I'm trying to instance Gun for unit-tests on my library and I do not want it to persist. However, I'm getting some strange resolves depending on the constructor parameters.

Can't fetch values that I just stored:
`new Gun({ localStorage: false, radisk: false, WebSocket: false })`

Still creates `data.json` and persists data:
`new Gun({ localStorage: true, radisk: false, WebSocket: false })`

Still creates `data.json` and persists data:
`new Gun({ localStorage: false, radisk: true, WebSocket: false })`

Does Gun require for Node.js to always create a persistent file, even for tests?

**Comment by amark** [comment]
lS: false, radisk: false should prevent storage on disk. But you are saying it doesn't?

lS true, radisk false, should cause data.json / file.js to be used

lS false, radisk true, should cause RAD to be used (which might create a folder called radata or data.json itself)

GUN's unit tests do require actual storage to happen, yes. What are your unit tests testing?

**Comment by jadbox** [comment]
When I instance Gun in this fashion below, it waits forever on I try to fetch a key. It's like it requires data.json in order to retrieve keys.
```
import * as Gun from 'gun'
const gun = Gun({ localStorage: false, radisk: false })
```

**Comment by jadbox** [comment]
This was a jest config issue, by default Jest was adding a global window object. Once I told Jest to use node env, the issue correct itself.

**Comment by amark** [comment]
Ooooh... global window object in Node?

Yeah... I case detect window (most reliable method I've found over the years so far), but do you think this should be concerning/alarming that a different method needs to be used?

**Comment by CinKon** [comment]
Hi, could you provide an example of how you mocked Gun or got it to work in your tests? All I get is either 

```bash
  TypeError: gun_1.default is not a function
      1 | import Gun from 'gun/gun'
      2 | require('gun/lib/path.js')
      3 | require('gun/lib/then.js')
      4 |
    > 5 | const gun = Gun('http://localhost:9000/gun')
        |             ^
      6 |
      7 | export default gun
```

or `Cannot read property 'chain' of undefined`
