### ISSUE TITLE
Try WASM?

### ISSUE THREAD

**Issue by udtrokia** [amark/gun#577]
.

**Comment by amark** [comment]
@udtrokia good idea, but I don't think JS -> WASM exists yet? We'd need a C/C++/Rust version first.

Gonna close this, as it technically isn't a bug. It is a valid future performance++ idea, but not core. Happy to chat more about it on the gitter. :)

**Comment by GiraffeKey** [comment]
JS -> WASM is pretty much impossible and will never exist.

However, AssemblyScript now exists. It is not JS but rather a stricter subset of Typescript that compiles to WASM. May be worth looking into but would require migrating the entire codebase to fit ASMScript's type safety and strict ruleset.

**Comment by amark** [comment]
@GiraffeKey at that rate, given https://gun.eco/docs/Porting-GUN base wire spec can be done in a few hours, it'd be better to have you/others team up with @ArtemGr who is currently starting a rust port. :)
