### ISSUE TITLE
gun.get(path) returns gun.get(path).once() value from async function

### ISSUE THREAD

**Issue by 509dave16** [amark/gun#578]
@amark 
### Summary
I have been plagued by this issue where return this result of `gun.get(path)` from an async function somehow resolves to what looks to be the put value that is. Not sure why this is happening.

![screen shot 2018-07-12 at 9 51 14 am](https://user-images.githubusercontent.com/2925882/42647550-26509b06-85b9-11e8-816f-6fe88da947d0.png)

### Reproduction of bug
Just hit the submit button and check the console. You'll see the something similar to the output above.
https://plnkr.co/edit/DAJoPHnrG8e1YvWq7wPv?p=info

### Workaround
Returning it on a object prevents the resolution to the put value
```javascript
...
 const node = gun.get('list');
return { node };
...
```

**Comment by fuchidahiro** [comment]
In my experience gun.get(path) returns a reference to the node, but to actually receive the node you would need to use .once((val,key)=>{result = val}) where result is just a temporary var to which you write the result.

**Comment by amark** [comment]
@509dave16 also note that this is invalid:

```
async function onSubmit(event) {    
  // ...
  const node = await getNodeAsync(key);
  // ...
  event.preventDefault()
}
```

event.preventDefault() needs to be at the top because DOM bubbles are sync not async.

Although probably not related to the issue.

**Comment by amark** [comment]
@509dave16 sorry, I don't use ES6 much, so I don't understand what you/code means around what behavior should be what between promises, gun references, async, etc. 

So for instance, if you get a node regularly, you should get the gun ref: (I think you know/understand all this already)

```
var ref = gun.get('foo').get('bar');
console.log(ref); // this is not the data, or a promise
```

However,

```
var promise = gun.get('foo').get('bar').then();
console.log(await promise); // data
```

You seem to be saying that `gun.get('foo')` is returning ???what??? from async functions? `.once()` returns a gun ref, not a promise or the data itself.

By default in GUN, all chaining API is suppose to return a gun reference. The only exception is that `.then()` downgrades a gun reference into a promise.
