### ISSUE TITLE
Aw Snap in Chrome

### ISSUE THREAD

**Issue by mitra42** [amark/gun#581]
Running Gun in the browser (Chrome) for my test setup, while debugging I'm seeing Google report "Aw, Snap!" at which point its disabled the page (no debugging possible)
See: https://support.google.com/chrome/answer/95669?visit_id=1-636670279781588090-3819038554&p=e_awsnap&rd=1

I've seen this before with webrtc, where Chrome would kill a page that used too much resources. 

I don't (yet) know how to consistently repeat this, and will post more if I can. 

Note - at the point this happens, my code isn't doing anything, I was actually at a breakpoint in the console trying some minor things, so I'm pretty sure any resource usage is by whatever Gun is doing in the background.

**Comment by mitra42** [comment]
Note - Gun was only using local storage, no peers were specified.

**Comment by amark** [comment]
Hmm, the only times I've encountered something like this is while I'm doing distributed load/correctness testing with our [PANIC](https://github.com/gundb/panic-server) tool. I haven't ever seen it with 0 peers.

Do you have your code regularly pushed to GitHub or something, that I can peek & replicate which plugins / commands are being called?

**Comment by mitra42** [comment]
I havent seen this in a while, maybe close it unless I can repeat ?

**Comment by amark** [comment]
@mitra42 thanks! Let me know.
