### ISSUE TITLE
nodeJS once behaves different from browser once

### ISSUE THREAD

**Issue by mitra42** [amark/gun#586]
See attached 
[gun_https2.js.txt](https://github.com/amark/gun/files/2199330/gun_https2.js.txt)
STR:
```
Rename attachment as gun_https2.js
$node ./gun_https2.js
```
Then on separate screen (and using different values for xx each time)
```
$node
>process.env.GUN_ENV = "false";
>var Gun=require('gun')
>var g = new Gun({peers: ['http://localhost:4246/gun'],localStorage: false})
>g.get("FOOxx").get("BARxx").once(data=>console.log("RCVD:", data))
//RCVD: undefined
```
In browser, navigate to [https://gun.eco/docs]
Open Javascript console
>g.get("FOOxx").get("BARxx").once(data=>console.log("RCVD:", data))
//RCVD: GUN: This is a test result

**Comment by mitra42** [comment]
Any progress on this and other issues with .once  ?

[related dweb-transports issue](https://github.com/internetarchive/dweb-transports/issues/7)

**Comment by amark** [comment]
@mitra42 SUPER LONG STORY but I think we finally nailed it today, publishing a fix soon.

The story:

https://github.com/amark/gun/wiki/@$$

This was definitely affecting things anywhere in a Heisenbug manner, including `.once` so this will certainly improve the situation, however goldfish thinks there still might be another bug/issue with `.once` but either way, fixing this Heisenbug will make any remaining issues easier to replicate. Heisenbug was basically impossible, but we did it!!!

**Comment by mitra42** [comment]
Does that fix catch the test above (which at least when I posted it was replicable).

**Comment by Dletta** [comment]
@amark I run the same setup as described above. (with the exception of using a local html file due to Firefox Security "features") What exactly was different? I see the same behaviour on the node js server whether it comes in from browser or not... (Am I missing something @mitra42 ?)

**Comment by amark** [comment]
@Dletta on my machine it is clearly a timing issue, as when I re-run the test multiple times, it sometimes is `undefined` sometimes isn't. Will be looking into it...

**Comment by amark** [comment]
@mitra42 I found out that it has to do with NodeJS storage adapter assuming it is authoritative, while Browser storage engine assumes it is not authoritative. I'm not entirely confident what the behavior should be, thoughts?

A) NodeJS peer asks itself (local disk) for data, it isn't found, replies `undefined`, meanwhile other NodeJS peer is replying via network with actual data.

Either I have to increase the default timeout that debounces on "not found" responses, but there is technically no limit on how long it should "wait", and if that number is high, then it'll significantly slow performance down other places as well.

I'd appreciate any opinionated thoughts on this subject.

**Comment by mitra42** [comment]
I'm not sure what the right solution is. I'm unclear of the exact flow here, but obviously if the peer looks in its own storage and doesnt find something, then responding (authoritatively) to the caller is clearly wrong.  I don't know what he "right" answer is, but the answer that the value isn't defined is clearly wrong when it hasnt even asked the peers its directly connected to. 

I acknowledge its not an easy answer, IPFS's answer (wait forever) is also clearly wrong. I'd (probably) be happy if the application could pose a timeout, or maybe even a TTL to control how many peer-to-peer steps it would query before saying undefined.

**Comment by amark** [comment]
@mitra42 hmm, what about a this algorithm for now:

while acks++ < peers.length 
  wait
else
  timeout <default debounce>

?

You might get more than 1 response from or via a peer, but whatever. This should be a close enough approximation that is an OK assumption until better thoughts?

**Comment by mitra42** [comment]
That could work - at least better than now - but I'm wondering if there is a better way, I had some ideas but probably needs a chat.  I'm available now if you wanted to chat (didn't expect you still to be working now).

**Comment by amark** [comment]
No, just transferred kids to sleep and checking stuff before bed since I didn't get to do any coding this week (bleh, all business stuff). But @go1dfish & @mmalmi been making requests since early last week and now you :) so I feel the heat!!! and gotta snap into code groove... hopefully tomorrow will be quiet to focus and at least roll with this idea and publish. If you think of anything better by then, let me know ++ shoot me times so we can schedule a call somewhere between our day/night diff. Cya!

**Comment by mitra42** [comment]
Understood - lets go for first thing my time 3pm PT (8am NSW).

There appear to be three cases, and partly the idea for a call was to see if one of them doesn't exist.
a) where we expect the node to be fully shared in which case a request for the data should be authorative
b) where we don't expect the node to be fully shared in which case we might have to ask how deep we want the recursion to go, i.e. we ask node A, B, C. A asks P,Q,R before replying, how many levels deep do you go (avoiding loops etc), I'm not sure how Gun works so don't know how to meter/ask that, but it seems similar to some of the algorithms that traceroute/ping use 
c) where the node is lazy, and you need to wait for node Z to reply, but node Z should be able to indicate somehow that its the authoritative answer for foo/bar/*

I might be completely missing how Gun works, but these are the kinds of ways I've seen this solved before.  What I *do* know is that you have to be able to ask a distributed database for an answer and it has to be able to give a reasonably likely to be correct answer, otherwise you need a very different way of relating to it and almost any kind of application that is query/response/act can't work with Gun?

**Comment by amark** [comment]
@mitra42 thank you for the feedback, these are really good points to consider for further options that can should be configurable.

For now, to just go with the most minimal non-committal code, this `.once` issue is now fixed (and fixes several SEA issues as a result) in latest NPM `0.9.99994` using the boring approach.
