### ISSUE TITLE
goldfish's Invalid Graph

### ISSUE THREAD

**Issue by amark** [amark/gun#588]
@go1dfish how did you get this graph? It is definitely  malformed (invalid). If you could give me a line number so I know what generated it and can fix it, that would be great:

```
{
  "@": "iaXAvvDRg",
  "put": {
    "~@go1dfish": {
      "_": {
        "#": "~@go1dfish",
        ">": {
          "~JG43ynRxqjy1-AemyMUoz14UqKM6cnh7zSPy_EAPgts": {
            "RCZ5dY7iRaIW_B7cDBlBsDNKwn2QCtbbA1uQ6iL8ENw": 1530068047117
          },
          "~945DV7EctKsOEp_6Oi-ixR68ws1mweeeJue7ajp9vUY": {
            "lx3kHFiRkFeQSRujoW1k3DnTJ4k6uG1fURHA1jWzozQ": 1531518314920
          },
          "~PtN6fQwktm3C4XYNErZur97WOVmST5vMi0GQR5dIQro": {
            "Lq6miC63X3Q2QQA9yAZFYGwf8nf-Rz-DkpeLfZ-F3Kc": 1528983048604
          },
          "~N8dqh5zxJiCwyJ6ROTOOXeaENDpnzEW-vA-9rRofZfw": {
            "7ijqWm1Q0UxFtYbUg3NPjcE5IM-MY3cESiPZeNzEuFE": 1530067385529
          }
        }
      },
      "~N8dqh5zxJiCwyJ6ROTOOXeaENDpnzEW-vA-9rRofZfw": {
        "7ijqWm1Q0UxFtYbUg3NPjcE5IM-MY3cESiPZeNzEuFE": {
          "#": "~N8dqh5zxJiCwyJ6ROTOOXeaENDpnzEW-vA-9rRofZfw.7ijqWm1Q0UxFtYbUg3NPjcE5IM-MY3cESiPZeNzEuFE"
        }
      },
      "~945DV7EctKsOEp_6Oi-ixR68ws1mweeeJue7ajp9vUY": {
        "lx3kHFiRkFeQSRujoW1k3DnTJ4k6uG1fURHA1jWzozQ": {
          "#": "~945DV7EctKsOEp_6Oi-ixR68ws1mweeeJue7ajp9vUY.lx3kHFiRkFeQSRujoW1k3DnTJ4k6uG1fURHA1jWzozQ"
        }
      },
      "~PtN6fQwktm3C4XYNErZur97WOVmST5vMi0GQR5dIQro": {
        "Lq6miC63X3Q2QQA9yAZFYGwf8nf-Rz-DkpeLfZ-F3Kc": {
          "#": "~PtN6fQwktm3C4XYNErZur97WOVmST5vMi0GQR5dIQro.Lq6miC63X3Q2QQA9yAZFYGwf8nf-Rz-DkpeLfZ-F3Kc"
        }
      },
      "~JG43ynRxqjy1-AemyMUoz14UqKM6cnh7zSPy_EAPgts": {
        "RCZ5dY7iRaIW_B7cDBlBsDNKwn2QCtbbA1uQ6iL8ENw": {
          "#": "~JG43ynRxqjy1-AemyMUoz14UqKM6cnh7zSPy_EAPgts.RCZ5dY7iRaIW_B7cDBlBsDNKwn2QCtbbA1uQ6iL8ENw"
        }
      }
    }
  },
  "err": null,
  "#": "uabgCgfU1"
}
```

Note: Announcing new RAD & SEA fixes in just a minute in the gitter (...hopefully I can do it before I lose internet access later today)... IDK if SEA fix will fix your login problem but hopefully it'll help... seemed like the thing I fixed MIGHT be related (to your login, not this malformed graph).

**Comment by amark** [comment]
Proper graph looks like this:

```
msg.put = {
  'soul1': {'_':{'#': 'soul1', '>': {key1: 2345, key2: 9876}},
    key1: 'hello world',
    key2: {'#': 'pointerToAnothersSoul'}
  }
}
```

(there of course can be soul1, soul2, soul3, etc... on the graph on the message. The `>` vectors are just random example numbers).

Spot the differences (don't have time to explain myself till I get back.... basically... `>` has double-nested data, that si invalid, all properties/keys on `>` should be vector/state/numbers/timestamps, not objects. Also the "pointers" on the data are also double-nested `{'~squigglyKey1': {'blahblah': {'#': 'pointerToOtherSoul'}}}` the "blahblah" shouldn't exist, if you look back to the `>` thing you'll see a similar thing is happening, an extra 'blahblah' is on it when it should just be `key2: vector`)

I'm 99% sure my code would never generate this malformed graph - so I'm guessing one of the NAB peers is trying to do custom wire logic/adapter and generating a bad graph? (If you can confirm that is NOT the case, then it might suggest it is my code... SEA is beta, but I'm pretty sure I'd have seen "invalid graph" in my tests by now, so I don't think it is my code, but hey :) I'm proven wrong a lot! Just want to eliminate the obvious if it is a custom wire adapter on one of the other NAB peers that is messing it up.)

g2g!!!!

**Comment by amark** [comment]
@go1dfish oh, tagging you, just in case it is needed for notifications. I'm headed off my computer though. Bye!

**Comment by go1dfish** [comment]
Ok I think I have an idea of what's going on here then, these are probably the result of using https://github.com/hughsk/flat to flatten/unflatten data for redis.

You can close this issue.

**Comment by go1dfish** [comment]
My adapter has been updated to fix this issue and generate a message like this:

    {
      "_": {
        "#": "~@go1dfish",
        ">": {
          "~JG43ynRxqjy1-AemyMUoz14UqKM6cnh7zSPy_EAPgts.RCZ5dY7iRaIW_B7cDBlBsDNKwn2QCtbbA1uQ6iL8ENw": 1530068047117,
          "~945DV7EctKsOEp_6Oi-ixR68ws1mweeeJue7ajp9vUY.lx3kHFiRkFeQSRujoW1k3DnTJ4k6uG1fURHA1jWzozQ": 1531518314920,
          "~PtN6fQwktm3C4XYNErZur97WOVmST5vMi0GQR5dIQro.Lq6miC63X3Q2QQA9yAZFYGwf8nf-Rz-DkpeLfZ-F3Kc": 1528983048604,
          "~N8dqh5zxJiCwyJ6ROTOOXeaENDpnzEW-vA-9rRofZfw.7ijqWm1Q0UxFtYbUg3NPjcE5IM-MY3cESiPZeNzEuFE": 1530067385529
        }
      },
      "~JG43ynRxqjy1-AemyMUoz14UqKM6cnh7zSPy_EAPgts.RCZ5dY7iRaIW_B7cDBlBsDNKwn2QCtbbA1uQ6iL8ENw": {
        "#": "~JG43ynRxqjy1-AemyMUoz14UqKM6cnh7zSPy_EAPgts.RCZ5dY7iRaIW_B7cDBlBsDNKwn2QCtbbA1uQ6iL8ENw"
      },
      "~945DV7EctKsOEp_6Oi-ixR68ws1mweeeJue7ajp9vUY.lx3kHFiRkFeQSRujoW1k3DnTJ4k6uG1fURHA1jWzozQ": {
        "#": "~945DV7EctKsOEp_6Oi-ixR68ws1mweeeJue7ajp9vUY.lx3kHFiRkFeQSRujoW1k3DnTJ4k6uG1fURHA1jWzozQ"
      },
      "~PtN6fQwktm3C4XYNErZur97WOVmST5vMi0GQR5dIQro.Lq6miC63X3Q2QQA9yAZFYGwf8nf-Rz-DkpeLfZ-F3Kc": {
        "#": "~PtN6fQwktm3C4XYNErZur97WOVmST5vMi0GQR5dIQro.Lq6miC63X3Q2QQA9yAZFYGwf8nf-Rz-DkpeLfZ-F3Kc"
      },
      "~N8dqh5zxJiCwyJ6ROTOOXeaENDpnzEW-vA-9rRofZfw.7ijqWm1Q0UxFtYbUg3NPjcE5IM-MY3cESiPZeNzEuFE": {
        "#": "~N8dqh5zxJiCwyJ6ROTOOXeaENDpnzEW-vA-9rRofZfw.7ijqWm1Q0UxFtYbUg3NPjcE5IM-MY3cESiPZeNzEuFE"
      }
    }


I can now log into all of my accounts *except* this one.  A couple of these are created with the same password, one was created by someone else; and one may have been created by me or someone else not sure.

**Comment by amark** [comment]
@go1dfish I'm glad we were able to recover `go2dfish` sorry `go1dfish` still unknown. :/

You said things got corrected and that I could close this issue? Gonna close it now. Please re-open if need be.

(hey, is it possible `go1dfish` one is using the OLD AES format, before I wrote that account Migrate tool? Maybe you could run the migrate tool against it?)
