### ISSUE TITLE
Is it possible one directional data flow in gun server

### ISSUE THREAD

**Issue by Ajmal1990** [amark/gun#589]
I have try to distribute the data in following way with 3 nodes (Server nodes)

> Node 1 ===> Node 2 <===> Node 3

ie, I want a data flow like when a change in Node 1 happens it will distribute to the Node 2 and Node 3. When a change in Node 2 happens it will only distribute to the Node 3. When a change in Node 3 happens it will distribute to the Node 2 only.

For that  I have configured the peer like 

- Node 1 have peer Node 2
- Node 2 have peer Node 3
- Node 3 have peer Node 2 

I transferred the data from Node 1, It will successfully transferred to Node 2 and Node 3. _But when I change in Node 2 or Node 3 it will transferred to Node 1 also_, even I have not  added the Node 1 to the peer list of Node 2.

**My question is: Is this the expected behavior?  Is it possible to achieve the one directional data flow using Gun?**

**Comment by amark** [comment]
On vacation with 1% internet...

Yes, on super peer have an input adapter that rejects updates from peers you don't trust, pseudo code similar to what you want :

https://github.com/zrrrzzt/bullet-catcher

**Comment by amark** [comment]
@ArminTaheri @Ajmal1990 were you able to get it working?

Could we also please move this to http://stackoverflow.com/questions/tagged/gun (?) GitHub issues are intended for bug reports - and I haven't heard anything on this in a while, so I'm gonna close.

**Comment by ArminTaheri** [comment]
Hello, I'm totally cool with closing the issue, this was exactly what I was looking for. Thanks again!
