### ISSUE TITLE
Integrate WebRTC

### ISSUE THREAD

**Issue by metasean** [amark/gun#59]

**Comment by RangerMauve** [comment]
Potentially we could look at [webrtc-swarm](https://github.com/mafintosh/webrtc-swarm) for inspiration on how to add this. Or maybe even use it for establishing the initial p2p connections

**Comment by amark** [comment]
@PsychoLlama has been working on learning WebRTC to add it to gun. Jesse, you should check out what ^ @RangerMauve just mentioned.

**Comment by PsychoLlama** [comment]
Thanks for the reference @RangerMauve! I'll check out...

**Comment by RangerMauve** [comment]
I use WebRTC regularly for my job so if you have any questions feel free to ping me on the Gitter chat.

**Comment by PsychoLlama** [comment]
@RangerMauve there's a lot out there to learn. I might take you up on that :)

**Comment by metasean** [comment]
Due to changes between 0.2.x and 0.3.0 this has been temporarily put on hold.

**Comment by PsychoLlama** [comment]
Currently under active development. You can find it [here](https://github.com/PsychoLlama/gun-rtc). So far, it's automatically connecting RTC peers with and without ICE trickle, but the get/put drivers haven't been hooked up yet. There is also usability and configuration work to be done.

**Comment by amark** [comment]
WebRTC isn't finished yet, but all issues relating to it should be moved to ^ its corresponding repos, not gun core. So that way each adapter can track its own bugs. So gonna close here. Thanks!

**Comment by iBobik** [comment]
Any news on this? Repo from @PsychoLlama seems abbandoned. Did somebody else tried it with newer version or gun?

**Comment by amark** [comment]
All WebRTC libraries we've used are inconsistent, fail frequently, and don't work very well.

However, somebody recently showed us EasyRTC (https://github.com/priologic/easyrtc) which so far I've had good/reliable experience with.

Here is an example transport adapter, very small, only ~100LOC: https://github.com/amark/gun/blob/master/src/adapters/websocket.js

@iBobik we'd love it if you could help contribute a WebRTC adapter!
