### ISSUE TITLE
How to use in-memory only on node-js server side?

### ISSUE THREAD

**Issue by PhilAndrew** [amark/gun#593]
Hi, I wish to use in memory only with no persistence to disk on the nodejs server side, how can this be done? Thanks, Philip

**Comment by fuchidahiro** [comment]
@PhilAndrew 
when you do var gun = GUN({radisk:false}); you should only run in-memory. If you still see a file generated, also add 'file:false' to the same option.

**Comment by PhilAndrew** [comment]
Yes your correct thanks a lot!
