### ISSUE TITLE
Gun server for Android

### ISSUE THREAD

**Issue by JoshuaHD** [amark/gun#594]
Has someone managed to install a Gun server on android?

**Comment by fuchidahiro** [comment]
@JoshuaHD Just pasting a chat message from @amark Oct 17, 2017

> Mark Nadal
[In repsone to AurelRoci_twitter] (1) gun browser peers will "act" similar to servers, so even running normal gun on your android/ios device will be like a server. (2) I have gotten 2M ops/sec out of an android phone (IDK about battery), note: this is cached reads, not end-to-end reads... we've done about 2K end-to-end sync tests but that was on a laptop not a phone. (3) To have your phone act as a "proper" server you'd need to do some fancy things to get its IP address and stuff which I don't know how to do (but might be easier if the phone is a WiFi hotspot???), or best case be using WebRTC but unfortunately that still requires a bootstrapping server. (4) Yes, GUN is designed to be able to do this BUT existing technology may prevent this or make it difficult (aka, firewalls, WebRTC, IP addresses, WiFi, Bluetooth, etc.)

**Comment by amark** [comment]
@JoshuaHD I think the closest is https://gun.eco/docs/React-Native , but I have no clue/experience how to get GUN running natively on Android as a "server".

Theoretically, if you can get NodeJS running on Android, running GUN should then be easy. Here are a couple quick googles:

 - https://medium.freecodecamp.org/building-a-node-js-application-on-android-part-1-termux-vim-and-node-js-dfa90c28958f

 - https://stackoverflow.com/questions/36632649/running-node-js-on-android

If you are able to get that working, let us know, then we can provide any remaining help debugging issues specific to GUN + Android NodeJS "server".

And glad to see you here in the community :) :) :) you should definitely join the super friendly chatroom ( https://gitter.im/amark/gun )!

Gonna close, as not a bug. Although it would be appreciated if you/somebody could copy&paste this Q and A to http://stackoverflow.com/questions/tagged/gun ! Thanks.
