### ISSUE TITLE
How do i sync a whole database for offline use?

### ISSUE THREAD

**Issue by JoshuaHD** [amark/gun#595]
To force a sync of the whole database on App start, what would i need to to. I know that gun.get().open() resolves the whole graph of a given key but how would so that the whole database gets synced for offline use?

**Comment by amark** [comment]
@JoshuaHD sorry for the long/delay - was busy during a conference when this was posted.

Could you super pretty please Copy&Paste your question & my answer to http://stackoverflow.com/questions/tagged/gun ? We try to keep GitHub issues for bug reports, and SO for Q&A.

There is a (**currently not**-implemented) wire spec command for this:

```javascript
gun._.on('out', {
    get: {'#':{'*':''}},
    '#': gun._.ask(function(msg){
	  console.log("reply", msg);
    })
})
```

You'll have to wait for storage adapters to implement this. There is partial support for it in GUN core for in-memory data (you may need to wait until the next release of GUN which has a bug fix for it).

You may want to know, though...

In the Browser (with the localStorage adapter), it queues up all un-ACKed data in `gap/gun` and resends it upon next page refresh to a connected superpeer. So if you are browser-only (using localStorage adapter) you could theoretically use this temporarily as your "all my offline data".

@JoshuaHD does this help?

Closing - please please please move it to StackOverflow! Super appreciated.
