### ISSUE TITLE
Bad link on https://gun.eco/think.html

### ISSUE THREAD

**Issue by ericmand** [amark/gun#609]
The "Getting Started" link in the footer of https://gun.eco/think.html is broken. I'd send a PR but I don't think that page is OS. Do you want feedback on gun.eco pages here?

**Comment by amark** [comment]
@ericmand thanks!

PR appreciated! Site is here: https://github.com/gundb/gun-site/blob/master/think.html

Oh... shoot, already fixed it. But yes, THANK you for offering to do a PR. Website feedback/issues should be on ^^^ that repo.

You good at being a web admin? Wanna help contribute redoing the sites?
