### ISSUE TITLE
A list of created users and its data?

### ISSUE THREAD

**Issue by zilveer** [amark/gun#621]
Hello,
In a centralized server we have database which user data which we can query and get the data we are searching for.

Is it possible to so the same with GUN ?
If so how should the user data be created so I can search in the database ?

Thanks for any advice.
Regards

**Comment by amark** [comment]
@zilveer this is a good starting point: https://gun.eco/docs/Auth (also check out /Todo-Dapp ).

GUN is a library/tool, so if you want to query ALL your users, just save/index them to a list like

```
var user = gun.user();
user.create(alias, pass, function(ack){
  if(ack.err){ return }
  gun.get('users').get(ack.pub).put(user);
});
```

Now you can search `gun.get('users').map().once(cb)`!

**Comment by saqing** [comment]
users this field, each user has the right to read and write, will cause this field to be unreliable？

**Comment by Dletta** [comment]
@saqing Each user can use write to their own graph, which is read-only for other users.
It's therefore reliable.

**Comment by zilveer** [comment]
@amark how secure is it when you write reliable ?
I mean is a user able to modify or manipulate any data ?

let's say that I want a website wherw I create an exchange, where users are able to deposit money to that account, in this case the user has deposited 100usd. Is the user able to manipulate the amount of money so it shows 1000usd instead or any other amount ?

Thanks for your reply
