### ISSUE TITLE
GUN based framework?

### ISSUE THREAD

**Issue by zilveer** [amark/gun#622]
Hi,
I really like GUN and have recently discovered it.

Is there any framework created in GUN for setting up a website with front end and backend?

Thanks for any advice.
Regards

**Comment by amark** [comment]
https://gun.eco/docs/Todo-Dapp walks you through how to create a dApp, which includes sub-tutorials on launching "superpeers" (one type of backend) and others. No framework, really. Is what you are looking for different than this?
