### ISSUE TITLE
Checkable updates

### ISSUE THREAD

**Issue by trenta3** [amark/gun#624]
Allow to have user-defined javascript functions that check updates validity.

Something like: for each thing that is put under this graph, the function has to accept the update.
If it rejects it, the update is discarded.

I don't know if this is already doable, but it could allow a great variety of use cases (and have as subcases authentication, ACL and schema verifications): it could ensure that the GUN state is always an application-valid state.

**Comment by Dletta** [comment]
@trenta3 There is a hook in gun to let you validate data and add a callback function (which is you javascript function). I don't remember the hook, at this time, but @amark could add an explanation in a bit.

**Comment by trenta3** [comment]
Yes, I suspected there was something similar, but I couldn't find it in the
documentation nor in other issues, so I asked it.
Will wait for @amark expanation, thank you.

**Comment by Dletta** [comment]
I forgot about this one, this should give you all you need.
https://github.com/zrrrzzt/bullet-catcher

**Comment by trenta3** [comment]
Thank you, exactly what I was looking for.
Is there a page listing the various plugins for gun with some description?

>

**Comment by Dletta** [comment]
https://github.com/amark/gun/wiki/Modules @trenta3
