### ISSUE TITLE
How SEA store pub/private ? is it safe ?

### ISSUE THREAD

**Issue by jackynguyen93** [amark/gun#628]
I see that SEA can use username/password to login. And then after login we can have a pair key to use to protect your private data. But is it safe that no one can get your private key. Because if you use username/password to login, that means you not own your private key (like a bitcoin wallet), so your private key may store somewhere in gundb, and it may be stolen by hacker. 
Please help me to answer these question. Sorry if I have some misunderstand or lack of knowledge and also my bad English explain :D

**Comment by cryptoquick** [comment]
I believe it's pair of keys generated by a PBKDF (password-based key derivation function), so it's basically an encrypted private key, likely stored in the database somewhere. I'm new to gun also, and this was a question of mine also, but that approach would make the most sense to me in this context.

**Comment by amark** [comment]
@jackynguyen93 @cryptoquick almost! Have to be careful about technicalities in crypto :( the keys are **associated** with the PBKDF2 not generated from it.

Yes, this approach is cryptographically safe. You may not want to store your Bitcoin in it though, but it is a great approach for social media accounts. If you want to learn more:

 - Check out our [Cartoon Cryptography](https://gun.eco/docs/Cartoon-Cryptography) 1 minute animated explainers!
 - Check out `user.create` in the [docs](https://gun.eco/docs/User).

I hope this helps!

Could you please copy&paste the ^ above into StackOverflow tagged gun? I keep GitHub issues for bug reports, but this is a great Q and would be more accessible for others if put on SO! Super thanks in advance for doing this. Closing!

@cryptoquick and WELCOME TO THE COMMUNITY!!!! :) :) :) How'd you hear about GUN? Sharp eyes, you have, on knowing how to apply PBKDF2! Good work. :)
