### ISSUE TITLE
Example: Data pending (auto-save indicator)

### ISSUE THREAD

**Issue by metasean** [amark/gun#63]
Data has been saved to the local peer but not acknowledged by any peers (e.g. local machine is not connected to network).  

Include an example gui/ui notifying end user of unsent status.

**Comment by amark** [comment]
```
$('.pending').text('saving...');
gun.get('foo').put(data, function(ack){
  if(ack.err){ return $('.pending').text("Error! " + ack.err) }
  $('.pending').text('saved!');
})
```

closing :D as this isn't a gun core issue.
