### ISSUE TITLE
Gun.node.is(node) returns false

### ISSUE THREAD

**Issue by Dletta** [amark/gun#631]
Gun Version 0.9.99997
```
var test = gun.get('test').put({name:'test'});
Gun.node.is(test); /// returns false
```

Expected to be true.

**Comment by 4b4me** [comment]
here are my code.
topdown(element){  
    this.convertToGraph(element);  
  if(element.childElementCount > 0) {  
        var children = element.children;  
  for (let child of children) {  
            if (child.tagName !== undefined) {  
                this.topdown(child);  
              }  
        }  
    }  
}
convertToGraph(element){
    if(element.id) { 
        key = element.id; 
        let  object = gun.get('root').get('scene').get(key); // creation a node
        object.get('id').put(element.id); 
        for (let attribute of element.getAttributeNames()) {
            object.get(attribute).put(element.getAttribute(attribute)); 
        } // well done
        if(Gun.node.is(object)){            
            gun.get('root').get('scene').get('objects').set(object); // fail!
        } else {
            console.log('object is not a node');
        } 
    }
}
My objective is converting html elements to gun nodes and saving it.
I call convertToGraph() in topdown() recursively.
As a result of some tests, set() works after finishing topdown() perfectly. But I need it in traversing html elements !!!
Why did gun said my node is not a node before finishing ?

**Comment by amark** [comment]
@4b4me looks like `object = gun.get...` and `Gun.node.is(object)`, in this case `object` is a Gun reference (the API) not a type of data (node/graph), so it would be `Gun.is(object)` while `Gun.node.is(data)`. Or are you getting "cannot link undefined / not a node!" or something like that?

@Dletta also. :)

**Comment by Dletta** [comment]
That should solve @4b4me's issue. Please confirm and let me know, so I can close the issue.

**Comment by Dletta** [comment]
Only point there is to shorten your typing of paths and to programmatically calling paths. Original issue seems solved, so I will close it, but of course always open for additional questions in gitter chat
