### ISSUE TITLE
auth() not returning data

### ISSUE THREAD

**Issue by glensimister** [amark/gun#637]
Hi Mark

I'm not sure if i missed something but I was following your youtube video about "Creating and Signing into User Accounts with GUN", and auth() doesn't seem to be returning an object. Please see the comments in the code below...

```
$('.create-user').on("click", function () {
        var name = $('.user-name').val();
        var password = $('.password').val();
        user.create(name, password, function (result) {
            console.log(result.pub); //this displays the pub key
        })
    });

    $('.user-login').on("click", function () {
        var name = $('.user-name').val();
        var password = $('.password').val();
        user.auth(name, password, function (result) {
            console.log(result.pub); //this displays undefined
        })
    });
```
Any ideas what i have done wrong? Thanks.

**Comment by glensimister** [comment]
result.sea.pub seemed to do the job. Cheers Mark  ;)

**Comment by romcok** [comment]
I'm not mark, only saw your issue. Just exploring the sea :D

**Comment by glensimister** [comment]
ah right. Thanks  ;)

**Comment by amark** [comment]
@romcok thanks for helping out with this, super appreciate it! Last month was swamped.

@glensimister I think I released a SEA update after this that hopefully also fixed it (or maybe caused the bug!?) either way @romcok is right `user.is.pub` is best one to use.

See you both on the https://gitter.im/amark/gun and thanks for helping each other out, great Open Source spirit!!! Closing :)
