### ISSUE TITLE
Getting ordered list of child nodes

### ISSUE THREAD

**Issue by karlitos** [amark/gun#644]
I am a little bit confused how/if I can get any ordered results. I noticed Gun does not support Arrays as values and __gun.set__ only ensures, that no duplicate entries will be added.

My application absolutely relies on correct order of _children_ connected to a node.

Basically I can provide an index to every node determining its position, but this will make any insert/reorder operation fairly complicated, resulting in updating of all indexes of all connected nodes.

I can also use linked list, but then I wonder how will I get the the information, that a node with certain data was inserted on position XY.

**Comment by amark** [comment]
@karlitos WELCOME TO THE COMMUNITY!!!!! :) :) :)

You are exactly right with your observations - there are about 3 different types of Arrays, like you listed, and there is no way for GUN to guess your intentions unless you are explicit about it.

I recommend either:

 - A) Using a linked list, as you suggest. When you update links, GUN will sync and do conflict resolution on it like it does any other data in the graph. If 2 people update an existing link at the same time, only 1 will win - which I presume is the behavior you want. If not, don't use a linked list.

 - B) An atomic array (strongly ordered, overwrites the whole thing each time, always loaded/saved in whole), which is as silly easy as `JSON.stringify(array)` before saving to GUN. Obviously JSON loses the ability to do graph data though, so this would not work well if the items in your Array are sub-objects or other nodes.

There are a few other data structures, but they all have tradeoffs  - that is unfortunately the nature of Distributed Systems, and decentralization only exaggerates that. Maybe you have a cool algorithm/data-structure that could solve this?

Even if you aren't an academic, if you have an idea, you should write it out! Could result in huge progress in several industries - academics, math, CS, blockchain, distributed systems, databases (in general, and also GUN specifically), etc. ! Would love to hear/see it.

As a result, this isn't a bug - more something that belongs in a wiki, I'll make it editable so you can add a page. Gonna close here. Also check out the chat room!
