### ISSUE TITLE
how to get the gun server

### ISSUE THREAD

**Issue by mccoysc** [amark/gun#645]
new gun(serverAddress);

how can i get a serverAddress?
does gun supply a public address?

**Comment by amark** [comment]
@mccoysc there are several relay peers in the community, run by D.Tube, Notabug.io, Internet Archive, and others.

**However**, you probably need to ask their permission to use them first. We have a **test** peer at `https://gunjs.herokuapp.com/gun`but we delete/wipe the data on it regularly. It is very easy for you to click the "One Click Deploy" button in the README deploy section if you want to run your own private network.

**GOOD NEWS** though, we'll be launching an automatic P2P peering system, called AXE, which will do exactly what you want - it'll work like `new Gun(AXE)` or something like that, and automatically discover and connect to other peers - even using WebRTC and stuff!! This is upcoming though, in the meanwhile I suggest you run your own peer via Heroku.

**Comment by mccoysc** [comment]
@amark how can run my own server?
i try to run the gun in node.js by gun.serve(req,res) but not work at all.
