### ISSUE TITLE
RDF modeling support?

### ISSUE THREAD

**Issue by maximveksler** [amark/gun#656]
Hi,

This ([also](https://github.com/CosmicMind/Graph/issues/158)) seems truly great.

Have you considered (and if you have I would love to hear you thoughts on this) buying into the semantic web eco system? (https://github.com/semantalytics/awesome-semantic-web)

**Comment by Dletta** [comment]
You can easily implement a triple-store a la rdf on top of gun. But Gun is a library, not an out-of-the-box every feature support.

See an example of a triple store here: https://github.com/Dletta/visualGraph/blob/e76ee9e0d5b69a3a376202497b588e6c71172456/abstraction.js#L34

**Comment by amark** [comment]
@maximveksler welcome to the community!!!!!! :) :) :)

Thanks @Dletta for being so on top of it, you are great/awesome.

@maximveksler was his answer useful?

We try to keep Issues for bug reports, would you mind reposting this ( + the answer) to StackOverflow tagged `gun`? Or if you need live help, the chatroom is super friendly. Gonna close this though, as it isn't a bug. I look forward to seeing it and questions like it populating on StackOverflow!
