### ISSUE TITLE
Bye

### ISSUE THREAD

**Issue by JamieRez** [amark/gun#662]
I have included the bye.js file in both my server and client.

At the moment, including `gun.on('bye', (peer) => {console.log(peer)}` on the server will indeed fire, meaning that gun does recognize when a user closes the application.

Not much can be done with this, as I'm not sure how I would change specific data, such as setting a user to be offline. The [documentation](https://gun.eco/docs/API#bye) does not seem to be up to date. 

Something like `gun.get('marknadal').get('status').bye().put("I'm offline.");` will not update or do anything when a user disconnects. 

I've been trying to debug the issue, but my limited knowledge in this realm is limiting me. [This](https://github.com/amark/gun/blob/master/lib/bye.js) is the bye.js file that needs updating.

**Comment by JamieRez** [comment]
I think I see what you're saying here. Though unfortunately I can't seem to get any of the peer's bye events to fire when another peer leaves. 

```
//client(peer) side
gun.on('bye', (peer) => {
  console.log(peer);
})
```

This will not log if another peer drops from the application. Funnily enough though, it will log if I manually stop the gun server. I guess it counts the server as another peer. 

Appreciate your help on this issue though!

**Comment by bugs181** [comment]
I'll look into this when I get a bit more free time. Yes, the server is just another peer. We like to call them super-peers, as they generally have access to more bandwidth and better uptime for stability. Other than that, they are treated no differently than any other peer on the network.

**Comment by bugs181** [comment]
After a bit more research, it appears that `bye()` handles this as exactly as I described.
Here's a note from the wiki:

> bye() is in experimental alpha, please report any problems or bugs you have with it. Note again that it does not fire immediately, and it does not get run from the browser. It makes the data change on the server when that browser tab disconnects.

**Comment by JamieRez** [comment]
Thanks for the information on servers being known as super peers, that's a fun concept.

In terms of your last post though, this is actually the exact kind of thing I would like to happen, though it seems the other peers are not completing the update when the specific peer exits out. 

I'm guessing there's a bug or something with the bye.js file that should make this work like it says in the documentation and wiki.

**Comment by amark** [comment]
haven't gotten to read thread yet, but saw gitter chat on this...

@JamieRez if you'd be willing to console.log experiment... https://github.com/amark/gun/blob/master/gun.js#L2187-L2197 should be starting path to see what is up, code there looks like it should call mesh.bye which should directly call 'bye' ctx.on event.

**Comment by JamieRez** [comment]
Think I solved the issue that was happening. Check out https://github.com/amark/gun/pull/666
