### ISSUE TITLE
Officially entering into the TimeGraph bounty for Gun

### ISSUE THREAD

**Issue by bugs181** [amark/gun#671]
I hereby announce that I am officially entering into the TimeGraph bounty. If anyone else is currently working on this, good luck to you all!

**Comment by amark** [comment]
You almost had this done back in February, but then you seemed to need to prioritize other things?

I wound up adding https://gun.eco/docs/RAD#lex a couple months ago, which is not the same thing, but might let people cheat without having to have a full timegraph.

Either way, this has been marked/tagged long enough in multiple places that I'm not worried about conflicts with others, so I'm gonna close.
