### ISSUE TITLE
'sort' as key in object throws error upon retrieval from radata

### ISSUE THREAD

**Issue by ThinkingJoules** [amark/gun#680]
Here is my test code:
```
let paramsObj = {alias: false, sort: false, vis: false, archive: false, deleted: false, props: false}
let id = Gun.text.random(24)
let soul = 'thing/' + id
gun.get(soul + '/config').put(paramsObj)
gun.get('things').get(soul).put(gun.get(soul + '/config'))

//then run
gun.get('things').map().on(Gun.log)
```
and the error I keep getting:
```
/home/dev/mwsc-erp/node_modules/gun/lib/store.js:50
            tmp = val.lastIndexOf('>');
                      ^

TypeError: val.lastIndexOf is not a function
    at each (/home/dev/mwsc-erp/node_modules/gun/lib/store.js:50:14)
    at /home/dev/mwsc-erp/node_modules/gun/lib/store.js:45:16
    at Function.Radisk.r.read (/home/dev/mwsc-erp/node_modules/gun/lib/radisk.js:193:14)
    at r (/home/dev/mwsc-erp/node_modules/gun/lib/radisk.js:52:14)
    at Object.next (/home/dev/mwsc-erp/node_modules/gun/lib/store.js:42:3)
    at Object.onto [as on] (/home/dev/mwsc-erp/node_modules/gun/gun.js:203:41)
    at Function.Gun.on.get (/home/dev/mwsc-erp/node_modules/gun/gun.js:845:10)
    at Object.root (/home/dev/mwsc-erp/node_modules/gun/gun.js:712:14)
    at Object.next (/home/dev/mwsc-erp/node_modules/gun/nts.js:18:20)
    at Object.security [as next] (/home/dev/mwsc-erp/node_modules/gun/sea.js:1117:23)
    at Object.onto [as on] (/home/dev/mwsc-erp/node_modules/gun/gun.js:203:41)
    at Function.Mesh.mesh.hear (/home/dev/mwsc-erp/node_modules/gun/gun.js:1985:10)
    at Function.Mesh.mesh.hear (/home/dev/mwsc-erp/node_modules/gun/gun.js:1993:12)
    at WebSocket.<anonymous> (/home/dev/mwsc-erp/node_modules/gun/lib/wire.js:75:14)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-simple@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-simple@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2019-01-08T19_39_49_636Z-debug.log
```
If you change the key of 'sort' to anything else the error goes away. Like:
```
let paramsObj = {alias: false, sorts: false, vis: false, archive: false, deleted: false, props: false}
```
Other notes:
-Tried both .map .get. If you grab the prop `gun.get(soul + '/config').get('sort').on(Gun.log)` no error is thrown. But `gun.get(soul + '/config').on(Gun.log)` will break.
-Tested the value of sort with both `false` and `'string'` error was the same, did not try other value types.

@Dletta Notes:
[Gitter January 8, 2019 1:22 PM](https://gitter.im/amark/gun?at=5c35068557c6883f9b833965) "I think rad is called with '125121551s51s2s.sort' and what it returns is an odd val"
[Gitter January 8, 2019 1:41 PM](https://gitter.im/amark/gun?at=5c350b0257c6883f9b835605) "somehow it does return from radisk, but then returns something that is not a node and tries to 'decode' to make sure it got the right thing, but when it is looking for the pointer '>' via lastIndexOf it realizes we are not dealing with a string, and therefore does not have the function"

Test environment:
Linux 18.04 VM on Chrome Version 70.0.3538.77 (Official Build) (64-bit)
Gun in browser: 
```
let opt = {}
opt.peers = ["http://localhost:8080/gun"]
opt.localStorage = false
this.gun = Gun(opt);
```
Gun on server:
`var gun = Gun({web: server, radisk: true});`

**Comment by milankubin** [comment]
I'm getting the same error when I try do do lots of sequential puts (i.e. in the hundreds - thousands), it will stop at around a 1000-2000 records. If I rerun the importer script, without taking account the successfully put objects - meaning, reprocess them - it will go over them, and then put an additional batch before it crashes again. All the hunches point to a bottleneck somewhere: when keys and indexes are populated it doesn't crash, just when we add new data really fast, we are running into this.

**Comment by ThinkingJoules** [comment]
@amark Did this 'sort' as a key in rad get resolved? I have avoided using this key in any of my gun objects since this issue. Not sure if you had a test for this when you worked on radisk last. If so this can be closed.

**Comment by amark** [comment]
@ThinkingJoules I certainly fixed/updated RAD code to handle this, tho don't have a test but it should be fixed. I'm gonna go ahead and close (thanks for the reminder, I don't like how issues go stale/old over time), but if you have time to re-run one of your projects and it still breaks please re-open.
