### ISSUE TITLE
Feature request: remove peer

### ISSUE THREAD

**Issue by mmalmi** [amark/gun#691]
Peers can be added with gun.opt({peers:[url]}), but it would be useful to be able to remove them also.

**Comment by amark** [comment]
@mmalmi @bugs181 @bkniffler @scttmthsn @privatemonkey @corporatepiyush @projectoblio @franky47 this should now work in latest with `gun.on('bye', "URLofPeer")` :D.

And WOAH, how come I have not met/chatted with 90% of the people who liked this thread? You all need to **majorly** join the community chat ( https://gitter.im/amark/gun ) so I can say hi to you! :)
