### ISSUE TITLE
IPFS integration

### ISSUE THREAD

**Issue by Folleah** [amark/gun#694]
Hi guys, how can I use GUN over IPFS?
Are there any specific reasons besides lack of time for which you are not integrating with IPFS?

**Comment by steve-vincent** [comment]
IPFS for what?
you can use ipfs.io or other gateways to access IPFS files over the web

**Comment by amark** [comment]
@Folleah GUN over IPFS? Probably not, but you could probably do IPFS over GUN. Or use IPFS as a storage layer instead of disk/S3/localStorage/IndexedDB - I think @mmalmi might have a prototype of one, but we'd love it if you could contrib!
