### ISSUE TITLE
nested put (more than 2 levels) does not work with server

### ISSUE THREAD

**Issue by steve-vincent** [amark/gun#698]
Put does not work with a server, if more than 2 levels deep.

Below, three level put (e.g. .get(a).get(b).get(c).put ) works without server, but just hangs no response with a server.
When you go to two levels, it works either way.

```
<!DOCTYPE html>
<meta charset="utf-8" />
<html>
<script src="https://cdn.jsdelivr.net/npm/gun/gun.js"></script>
<script type="text/javascript">

function getRandom(){
  return ("x" + Math.round(Math.random()*10000));
}

var gun = Gun(); // <--A: ALWAYS WORKS
//var gun = Gun(['https://<your server>/gun']); // <--B: PROBLEMS START W/ SERVER

//path & data
var PATH0 = "level0";
var PATH1 = "level1";
var PATH2 = getRandom();
var testobj = {"name":getRandom()};

//put
//gun.get(PATH0).get(PATH1).put(testobj, function(ack){ // <--WORKS A & B
gun.get(PATH0).get(PATH1).get(PATH2).put(testobj, function(ack){ // <-- DOES NOT WORK B
  console.log("put(ack):", ack);
});

//listen
//gun.get(PATH0).get(PATH1).on(function(data, key){ // <--WORKS A & B
gun.get(PATH0).get(PATH1).get(PATH2).on(function(data, key){ // <-- DOES NOT WORK B
  console.log('on:',key,data);
});


</script>
</html>
```

**Comment by amark** [comment]
Thank you, hopefully this will let me replicate.

@finwo in #687 been working on I think same issue.

I'm won't be available to make fix for a while, have to finish some high priority projects, but I'm sure this will hit me in the gut for those as well that'll need to fix.

**Comment by steve-vincent** [comment]
I worked around this for now by replacing the CDN with older version.

<script src="https://cdn.jsdelivr.net/npm/gun@0.9.9998/gun.min.js"></script>


Not sure that's the best version... just picked an old one randomly, and it worked (on that issue).
It seems the newer versions being delivered broke something about nested puts.

**Comment by amark** [comment]
@steve-vincent thanks!

As I & @finwo predicted, this / #687 affected me during my demo :P but I did get the demo done by working around it. I plan to focus on fixing this / deep-put of @finwo 's issue this next week. :)

**Comment by amark** [comment]
@steve-vincent @finwo this **MIGHT** be fixed on latest `...99` that I published on Sunday. When I ran the tests then, it was now working. Altho, I ran tests again today and either I messed something up again, or it is still broken. So leaving this open unless you confirm it is fixed.

**Comment by steve-vincent** [comment]
Cool thanks Mark, I should be able to test and confirm tonight.

Nice work on gun BTW..  its what the self-governed web needs, and love the name

**Comment by steve-vincent** [comment]
Yes - works now... multiple nested levels deep.
Closing thank you @amark.
