### ISSUE TITLE
How to fetch and render the file in browser which I am getting from another gun server?

### ISSUE THREAD

**Issue by amitmoralwar** [amark/gun#705]
How to fetch files from gun db and render them in browser?

I set two gun servers and I want to send files and videos from one gun server to another. I used gun.opt() to connect with another gun server, then I used gun.put({file:'test.epub.base64'}); method to send file to another gun server. I am getting file to another gun server but I don't know how to fetch it from local storage and render it in browser. Can anybody help me out with this?

gun.opt('http://localhost:8081/gun');

gun.put({file:'test.epub.base64'});

**Comment by amark** [comment]
@amitmoralwar WELCOME TO THE COMMUNITY!!!!!!! How'd you hear about GUN?

Sounds like you are building something really cool!

I previously gave a decently detailed overview on this at StackOverflow, hopefully it can help give more context:

https://stackoverflow.com/questions/53789295/how-to-store-image-video-file-using-gundb/53799051

As far as how to display the base64 image itself, that is beyond the scope of GUN - I usually do this with jQuery `.css({backgroundImage: 'url(' + base64 + ')'})` or `$('img').attr('src', base64)`.

Definitely jump on the chatroom (https://gitter.im/amark/gun) people are super friendly there and you'll get faster replies than :) here.

CHeers! Closing.
