### ISSUE TITLE
gun.js at client side

### ISSUE THREAD

**Issue by sachinsawant71** [amark/gun#706]
I have very basic question. This is regarding accessing Gun.js DB at client side. As per the documentation, I can connect to the DB by using the constructor - Gun('http://yourdomain.com/gun'). So anybody who knows the DB url can connect to the database.

I have a web application. I want only authorized users should access the Gun DB.  How do I achieve it?

**Comment by amark** [comment]
Welcome @sachinsawant71 !!!! :) I encourage you to use the chatroom ( https://gitter.im/amark/gun ) for these types of questions, as you'll get faster replies! The community is very active and friendly.

Use SEA (Security, Encryption, Authorization) to authorize users.

The best starting point is to follow this tutorial which shows how to use it:

https://gun.eco/docs/Todo-Dapp

It is important you watch these 1 minute animated cartoon explainers about how SEA works:

https://gun.eco/docs/Cartoon-Cryptography

If you want more advanced details on what algorithms/curves are used in the cryptography, check out the SEA docs:

https://gun.eco/docs/SEA

To see a demo of what can be done, check out:

https://www.youtube.com/watch?v=ZiELAFqNSLQ

https://www.youtube.com/watch?v=xFR8cx7jB1c
