### ISSUE TITLE
Reference to rindexedDB graphql-gun

### ISSUE THREAD

**Issue by Sonacse12** [amark/gun#707]
I installed graphql-gun using 

    npm install graphql-gun

in my typescript project and I could get the typescript definitions by using 

    const graphqlGun = require('graphql-gun');
    const Gun = require('gun');

Creating 1000+ nodes led me to the following error:

> "QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'gun/' exceeded the quota. Consider using GUN's IndexedDB plugin for RAD for more storage space, temporary example at https://github.com/amark/gun/blob/master/test/tmp/indexedDB.html ."

To fix this, I tried to use rindexdb, but I couldn't find type definitions for the same. What could be a possible way to do this?

**Comment by amark** [comment]
@Sonacse12 apologies this took so long, but we finally have proper docs up on how to use RAD's IndexedDB plugin with GUN:

https://gun.eco/docs/RAD#install

I don't really know what to do about Type definitions, that sounds like a TypeScript (?) thing, and probably gonna have to be supported through some community-contributed definition - if this was the main reason you opened the issue, I ask you follow this up with the community at https://gitter.im/amark/gun , as I'm :P not smart enough for this one! Thanks!
