### ISSUE TITLE
JS.ORG subdomain

### ISSUE THREAD

**Issue by indus** [amark/gun#708]
It seems like you are no longer using the gun.js.org subdomain besides a redirect. That is against the requirements of the service. Would you mind to actually use the subdomain or otherwise hand it back to the service.
A possible solution is some landing page as described here https://github.com/js-org/js.org/pull/2729

**Comment by Dletta** [comment]
@amark is gone for 2 weeks. He will respond when he is back.

**Comment by amark** [comment]
@indus just got back...

Sorry about that!

Thank you for allowing a workaround for popular projects, like with the landing page.

I'd like to opt for that.

How soon does it need to be done?

(...anybody willing to set it up? will give commit access)

**Comment by indus** [comment]
> How soon does it need to be done?
There is no fixed deadline - but it would be nice if it could be done within a couple of weeks or months...

**Comment by amark** [comment]
Anybody know any good designers for hire to make pretty graphics for this?

**Comment by amark** [comment]
@indus finally got around to this **THANK YOU**

proud to present, the NEW http://gun.js.org/ website!!! :D :D :D
