### ISSUE TITLE
err and success messages

### ISSUE THREAD

**Issue by metasean** [amark/gun#71]
According to the `put` section on https://github.com/amark/gun/wiki/JS-API, "As long as there is no err then things should be ok, ok may not be defined."  This is a bit disturbing, I'm too newb to fully articulate why.  Is it possible to always define an 'ok'?

**Comment by PsychoLlama** [comment]
It's possible that we could do validation on the callback arguments, and if there isn't an error, yet the `ok` parameter is undefined, we could patch the parameter and give it a value of `{ ok: true }` to match spec.
That shouldn't adversely affect the existing behavior, and should make things more intuitive and consistent for the end developer.
Example:
```javascript
if (!error && success === undefined) {
  success = { ok: true }
}
callback(error, success)
```

**Comment by metasean** [comment]
The gun team has decided  that errors *must* be acknowledged and success *may* be acknowledged.  The callback *must* be respected regardless.

**Comment by amark** [comment]
docs have been updated around this for the latest API, therefore closing.
