### ISSUE TITLE
Use gun to synchronize sql database

### ISSUE THREAD

**Issue by ShareTheWorld** [amark/gun#712]
I want to use gun to implement a sql database synchronization function, so I use gun to synchronize data, use sql database to process business,

But I have a problem:
First, I made a mapping

Gun("root").get("database").get("user").map().on(function(data,key){
 .... //data like `{"name":"hongtao","age":"23","sex":"Male"}
 .... / / Insert data into the user table
});

The problem is that every time I start, I call the on method, which will iterate over all the data that already exists. If the amount of data exceeds 100,000, this can be very slow, and each table will run this way.
Because it is a distributed application, these nodes will run on the phone, and this is accompanied by a lot of restart operations.
Can I just listen for notifications of data changes? or have better suggestions? thanks

best wishes

**Comment by merarischroeder** [comment]
I think this kind of "issue" would work better in StackOverflow.

**Comment by amark** [comment]
@merarischroeder good idea.

@ShareTheWorld great question!

Could one of you move this to StackOverflow? Gist of an answer is if your query intends to read old data, it should read old data - if you want it to read "new" data then you should create in your data a tag or a table (or some other graph index, like timegraph) that queries "today" or similar (you see notabug.io does this), this makes your data more powerful and expressive (versus just filtering a table like you do now, that will be slow in all/any databases). Does that make sense?

In the meanwhile, gonna close here, as this is not a bug report.
