### ISSUE TITLE
WebSocket network error: The operation couldn’t be completed. (OSStatus error -9807.)

### ISSUE THREAD

**Issue by huhsame** [amark/gun#718]
After testing with http and local, **I added my certification for https.**
just changing http to https makes some error.

desktop : work fine.(chrome, safari)

but mobile devices has some problems.
android : little bit problem.
**ios : cant connect websocket**

Especially, I got this error only on ios.
[Error] WebSocket network error: The operation couldn’t be completed. (OSStatus error -9807.) (x4)

![image](https://user-images.githubusercontent.com/9151382/54016866-a3910b80-41c7-11e9-9283-44c44e38a9b5.png)

It seems to be related with certification or gundb.
As I mentioned, Everything is work fine with http .

my certification is issued by Let's Encrypt with SHA-256 with RSA Encryption

**Comment by huhsame** [comment]
Here is my server code.

```

var debug = require('debug')('aframe-gundb:server');
var fs = require('fs');
var app = require('../app');
var https = require('https');

const options = {
  key: fs.readFileSync('./keys/privkey.pem'),
  cert: fs.readFileSync('./keys/fullchain.pem')
};

var Gun = require('gun');

var server = https.createServer(options, app);
var gun = Gun({web: server});
server.listen( 3001 );
```

**Comment by bugs181** [comment]
Thanks for the server code, it's much appreciated. However more importantly would be the client code, to see how the connection is set up.

**Comment by bugs181** [comment]
For your constructor, it may need a preceding forward slash. Like this:
```
const gun = Gun( window.location.href + '/gun')
```

**Comment by huhsame** [comment]
No. 
it got this error.
[Error] WebSocket connection to 'wss://192.168.1.62:3001//gun' failed: Unexpected response code: 400 (x4)

**Comment by bugs181** [comment]
I'm wondering if this is a bug in Gun, which uses the `ws` library. I'm curious if you could change this to `wss`. In the Gun constructor of your setup, could you try adding `Gun({ wss: require("wss") }`

**Comment by huhsame** [comment]
After adding websocket option you said, 
there are more errors including original one. 

![image](https://user-images.githubusercontent.com/9151382/54018584-6bd89280-41cc-11e9-8531-ef89a95e525d.png)

**Comment by bugs181** [comment]
Apologies, looks like this is something in the Gun library itself (or some other issue I'm missing). We will have to wait for someone else to offer help.

**Comment by Dletta** [comment]
Quick added info:
@huhsame 's Error in Mac is belows

  | Security 							SecureTransport.h | errSSLXCertChainInvalid | -9807 | Invalid certificate chain.
-- | -- | -- | -- | --

**Comment by amark** [comment]
Thanks @Dletta @bugs181 for helping reply to people on issues. You guys are life savers.

Hmmm.

Maybe another idea is try to run a standalone websocket server (no GUN) and see if connecting still has problems? If it doesn't, then we know it's a problem with how GUN hands off the certificate (I don't have any special code tho that does this).

And @huhsame WELCOME TO THE COMMUNITY!!!! :D :)

**Comment by amark** [comment]
@huhsame after passing `require('wss')` to the NodeJS GUN WebSocket param, it looks like it is NOT inheriting `require('ws')`'s `.Server(options)` API. Which seems like a problem with `wss`.

Is there another possibility the issue is the `//` in `'wss://192.168.1.62:3001//gun'` in Browser? what happens if `'wss://192.168.1.62:3001/gun'` (?)

@huhsame given your EPIC demos I just noticed on Twitter (you never tagged me! :O I only accidentally stumbled across them and retweeted today) I assume you got this working?

Gonna assume I can close (also, cause I know notabug.io , Internet Archive, and others have secure websockets working, and I have some local PANIC tests that use self-signed HTTPS working [tho tablets don't let self-signed certs, here https://github.com/amark/gun/blob/master/test/https/test.js#L8-L12 ]) so I know secure websockets themselves with GUN is not broken, tho clearly something odd is going on with `-9807` ? any new input on that ?) if you have new info on how you got around it, could you update docs or leave a follow up comment here (or re-open)?

**Comment by wllcpp** [comment]
I have some issue like this and have you fix this issue?

**Comment by JemalJiquri** [comment]
hi can your help 
![image00005](https://user-images.githubusercontent.com/48554008/83174011-cab85d80-a12a-11ea-9c59-40cdb5257929.jpeg)
![image00006](https://user-images.githubusercontent.com/48554008/83174015-cbe98a80-a12a-11ea-8e1e-b32d80398383.jpeg)
![image00007](https://user-images.githubusercontent.com/48554008/83174017-cc822100-a12a-11ea-9894-370730eb49b1.jpeg)
![image00008](https://user-images.githubusercontent.com/48554008/83174019-cc822100-a12a-11ea-812f-83e70e97e3f7.jpeg)
![image00009](https://user-images.githubusercontent.com/48554008/83174021-cd1ab780-a12a-11ea-95f5-bb8833117091.jpeg)
![image00010](https://user-images.githubusercontent.com/48554008/83174022-cd1ab780-a12a-11ea-8c36-0a743c4629b6.jpeg)
![image00011](https://user-images.githubusercontent.com/48554008/83174024-cd1ab780-a12a-11ea-8df8-2b15d6f925ad.jpeg)
![image00012](https://user-images.githubusercontent.com/48554008/83174027-cdb34e00-a12a-11ea-93dd-7434c0d66436.jpeg)

**Comment by mertdeveci5** [comment]
Hey guys, anyone still having a similar error? 
`WebSocket connection to 'ws://localhost:8765/gun' failed: `
I get this in my console. I wonder if this is about something else as the same error keeps repeating after several seconds with a different ws source link. Anyone got the solution? Would really appreciate it
