### ISSUE TITLE
Typescript guide for gun

### ISSUE THREAD

**Issue by Jack-Works** [amark/gun#720]
## Install
> yarn add @types/gun
or
> npm install @types/gun

## Define your app state interface

Now let's say we have a gun app that syncs an input text between nodes.

```typescript
interface AppState {
    sync_input: { text1: string; text2: string; }
}
const gun = new Gun<AppState>('https://example.com/gun')
```

Now `gun` has type `GunInstance<AppState>` and it is definitely typed!

```typescript
gun.get('sync_input') // now it has type GunInstance<AppState["sync_input"]>
.put() // this field only accept { text1: string, text2: string; }
```
For more example: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33100/files#diff-a04b085b151b79955666308959e91eaa

Most of the APIs in Gun are typed like examples above. Just use them as normal. But here are some exceptions.

### Sets
Set is special. If you want to use it, type it like this.
```typescript
interface State {
    users: string[]
}
```
Use Array to represent a set. Then you can `.set("x")`

For any type that not an Array, `.set()` will be typed as `.set(value: never)` to prevent you call it accidentally.

### `back(level: number)`
Apparently, this cannot be typed. It will return a `GunInstance<?>`. Avoid using it in Typescript. Always get gun node from `root` so you can get typed.

### `path?(path: string | string[])`
Same as `back`. Can't be typed. Avoid using it.

### All the addons
Like `promise()`, `then()` etc. Typed as `?`. You should make sure you have already imported the file need yourself.

When you use addons, use it like `then!()`. Add a `!` after the method name to let typescript know you want to ignore the `?`.. Add a `!` after the method name to let typescript know you want to ignore the `?`.

## Gun.SEA

Not typed yet. I'll do it later.

**Comment by amark** [comment]
@Jack-Works wow!!! This is so cool :D :D :D :) many are gonna love it.

Do you want to add this to a page like https://github.com/amark/gun/wiki/Typescript or https://github.com/amark/gun/wiki/Types (?) so it gets more visibility?

**Comment by Jack-Works** [comment]
Done https://github.com/amark/gun/wiki/Typescript-Guide
