### ISSUE TITLE
indexedDB and Local storage still being used when options are off

### ISSUE THREAD

**Issue by QVDev** [amark/gun#724]
`var opt = {
    radisk : false,
    localStorage : false,
};`

`var gunDB = Gun('https://gunjs.herokuapp.com/gun', opt);`

**Comment by Dletta** [comment]
Although resolved for your case, it seems when initiating Gun(ipString, opt) it does not initiate correctly.
We had to change it to include the peers as an array of peerStrings into opt to make it work.

**Comment by amark** [comment]
@Dletta thanks. 

Yeah, so was this just calling opts wrong?

Gonna close. Please re-open if it is something else.
