### ISSUE TITLE
How to prevent one rogue user from deleting entire database?

### ISSUE THREAD

**Issue by projectoblio** [amark/gun#726]
I thought I'd find this in the FAQ but didn't...

If I have 100 users all chatting in a chat room, and 1 rogue user doesn't like what's going on, what's to stop him from doing:

`gun().get("chat").put(null)`

This is not my exact situation, and I know he wouldn't be able to delete the `user` object, but I was wondering if there was any `easy` way to do the type of security found in the user object. Like, can users "put" chat messages there, and then can they be the only ones to remove it?

On a similar note, does the host of the server have an easy way to purge excess data that's been there too long? 

These are all questions i thought i read somewhere at some point in the docs, but I can't find them now.

Is that basically what this library is for? https://github.com/zrrrzzt/bullet-catcher
Is there any way to catch these requests on a gun-key basis? As opposed to a user-key basis?

**Comment by projectoblio** [comment]
I think there should be a way to ensure upper level structures can't make changes that modify or remove user-written structures at its lower levels.

**Comment by westlane** [comment]
Agree with @projectoblio that this would be extremely useful as a safeguard. This might need to be a server or peer-specific option as developer needs vary.

A common scenario for our decentralized use case is the creation of a node with a unique key, nested within a top-level namespace. We have encountered numerous times where an innocent peer, not even a rogue, mistakenly clears out a large amount of data for all users with a seemingly innocuous `.put(null)` command. 

For example, let's imagine that we store data for every country in the world. We might have a top level node "world" that can be mapped:

`gun().get("world").map()`

Inside our world we have a number of countries, and inside each one a list of cities:

`gun().get("world").get("italy").map()`

So two peers go off on their own, each disconnected from the internet. They create a number of countries and start to fill up data about the cities within. Each has a very nice graph filled with meaningful world data. One peer happily adds dozens of cities to "france" and builds a valuable database. 

Meanwhile, somewhere across town and offline, another peer starts to create a new "france" node, but then realizes that this country will not be needed at this time. The peer tries to clean up the database by issuing:

`gun().get("world").get("france").put(null)`


Especially when the two peers are offline and may not have accurate clocks, there seem to be several ways in which the `null` command might be given priority in [conflict resolution / merging](https://gun.eco/docs/Conflict-Resolution-with-Guns) (assuming my understanding of GunDB eventual consistency is accurate).

When the two peers reconnect to another instance, perhaps hosted in the cloud, the data for "france" could automatically be removed from all peers. I believe the raw data is technically still stored but now detached from the expected namespace and key. In practice, this makes it very easy to accidentally lose some valuable data. Obviously it is possibly to write client code to avoid or discourage this behavior. But an ability to prioritize and hedge towards the preservation of higher-level structures would, in my view, further GunDB's goal of simplicity and care-free use.

**Comment by Dletta** [comment]
One way that is mentioned in the FAQ is to have a user set up that is the main graph. This user may in the map or chat example become the 'Observer User' who is notified upon chats and writes messages to his own user graph. All clients that 'read' data pull from his graph. Every write goes to an intermediary place that the 'Observer' watches for each user. Whenever new data comes through a conflict resolution can run on the server (safeguard) before writing the new data to the 'Observer's Graph'. 

This is a federated approach, where many people could run their own observer, but data is all saved on the observer (a common) user graph.

The decentral approach would be rules that apply on all peers, such as 'validated that a user is signed in before allowing writes' or 'only users with a certain reputation (found in other users graph) can post' etc.

Decentral systems are hard to design as you know, data is everywhere and at different times. The only way to keep it consistent is if all agree to use the same rules. (same validation code, schema etc)

**Comment by nival999** [comment]
Ahh okay. So when a user posts a chat message to his or her graph, a server receives an `on` notification and cross-posts it to its own (authenticated) graph. You could have multiple servers all running this `on` cross-posting function. 

Is this what you just said or does this only double the data size and there's a better way?

Thanks
