### ISSUE TITLE
Can you solve this "Gun Get" puzzle for a nested object??

### ISSUE THREAD

**Issue by projectoblio** [amark/gun#727]
Can you, using any of the available plugins or an external one from those listed, get an object with the keys contained in "obj"? Requirement: must use async/await.
```
var Gun = require('gun');
	var SEA = require('gun/sea');
	require('gun/lib/unset.js');
	require('gun/lib/open.js')
	require('gun/lib/load.js')	
	require('gun/lib/then.js');
var gun = Gun()
async function test(){
		var obj = {"property":"value","depth":{"is":"more_than_one"}};
		gun.get("key").put(obj);
		console.log("Put this away! : ",obj);
		var obj2 = await gun.get("key").then();
		console.log("Got this value",obj2);
}
test();
```

Will you get the full dict contain in obj? Or, will your result be this: 

```
Got this value { _: { '#': 'key', '>': [Object] },
  depth: { '#': 'jtm3cjyqGvlGqFS2TIrN' },
  property: 'value' }
```

Can you get a result where the `depth` key contains the value `{"is":"more_than_one"}`?

**Comment by omarzion** [comment]
Insanity but...

```
var Gun = require("gun");
var SEA = require("gun/sea");
require("gun/lib/unset.js");
require("gun/lib/open.js");
require("gun/lib/load.js");
require("gun/lib/then.js");
var gun = Gun();
async function test() {
  var obj = { property: "value", depth: { is: "more_than_one" } };
  gun.get("key").put(obj);
  console.log("Put this away! : ", obj);
  var obj2 = await gun
    .get("key")
    .then()
    .then(async v => {
      let soul = Gun.node.soul(v);
      let keys = Object.keys(v).filter(k => k !== "_");
      let all = keys.map(key =>
        gun
          .get(soul)
          .get(key)
          .then()
      );

      let results = await Promise.all(all);
      return keys.reduce((result, key, i) => {
        result[key] = results[i];
        return result;
      }, {});
    });
  console.log("Got this value", obj2);
}
test();
```

Returns:
```
Got this value { depth:
   { _: { '#': 'jtm3zq9iSCH5OWncpQuk', '>': [Object] },
     is: 'more_than_one' },
  property: 'value' }
```
Here is the sandbox
https://codesandbox.io/s/5k71k3xrmp?fontsize=14

**Comment by projectoblio** [comment]
Thanks dawg. I tried to wrap that function into a `chain` like the others but I couldn't figure it out. In the end i think i went with what the other nice gitter man suggested 

	async function retrieve(gunNode){
		return new Promise((resolve,reject)=>{
			gunNode.open(function(value){
				console.log("Got this obj4",value);
				resolve(value);
			});
		});
	}
       gun.retrieve=retrieve;
   async function test(){
		var obj = {"property":"value","depth":{"is":"more_than_one"}};
		gun.get("key").put(obj);
		console.log("Put this away! : ",obj);
		var obj2 = await gun.retrieve(gun.get("key"));
		console.log("Got this value",obj2);
}
test();

**Comment by projectoblio** [comment]
Holy shit i thought i went crazy. It turns out that `gun` was updated on npm two days ago and this no longer works.

`0.9.9999991` working

`0.2019.323` not working

@amark y u torture me

**Comment by amark** [comment]
@omarzion THANKS SO MUCH for jumping into the community and helping <3 <3 <3

@projectoblio do you know what broke? Because `0.2019.323` has some critical updates - I had to bump the middle number away from `9` to date `2019` because while the API should be the same, old data won't work. Is it that your old data is gone? You should probably use `^0.A.B` package.json notation so you don't get messed up on upgrades like this. :/ Sorry!

Wanted to double check... does wrapping `.load(cb` in a Promise not work?
I see @omarzion you include it, but don't use it, and manually recurse to find sub-data yourself (this is what `.load` should do automatically for you).

**Comment by projectoblio** [comment]
Wrapping with a promise does not work anymore with the update, here i have provided a test script:

```
async function retrieve(gunNode){
	return new Promise((resolve,reject)=>{
		gunNode.load(function(data){
			resolve(data);
		});
	});
}
async function test(){
		var obj = {"property":"value","depth":{"is":"more_than_one"}};
		gun.get("key").put(obj);
		console.log("Put this away! : ",obj);
		var obj2 = await gun.get("key").then();
		console.log("Got this value with then",obj2);
		var obj3 = await gun.get("key").load().then();
		console.log("Got this value with .load().then()",obj4);
		var obj4 = await gun.get("key").load();
		console.log("Got this value with .load()",obj4);
		var obj5 = await retrieve(gun.get("key"));
		console.log("Got this value with promise wrap",obj5);
}
test();
```
will print:
