### ISSUE TITLE
objects not persisting to indexedDB

### ISSUE THREAD

**Issue by minskmaz** [amark/gun#730]
Just learning gunjs. Really cool project folks. Is there a canonical way to ensure that idb is utilized ? When I "put" the examples (alice, bob, carl & dave) in the store some events seem to bind but the console then reports  {err: "Error: No ACK received yet.", lack: true} about 10 seconds later with nothing in the idb.

```javascript
async function initGUN() {
    const levelup = require('levelup')
    const leveldown = require('level-js')
    const encode = require('encoding-down')
    // Initialize Level
    const url = 'http://localhost:8765/gun';
    const levelDB = levelup(encode(leveldown('my-big-db'), { valueEncoding: 'json' }))
    // Initialize Gun
    window.gun = Gun(url, {
        level: levelDB,
        localStorage: false,
    })
}

async function initGUN() { 
    localStorage.clear();
    const url = 'http://localhost:8765/gun';
    const opt = { radisk : true };
    opt.store = RindexedDB(opt);
    window.gun = Gun(url, opt)
}

```

**Comment by minskmaz** [comment]
Seems I got something working as objects are now flowing into indexedDB but now webpack  complains that it "Can't resolve 'fs'" 

Module not found: Error: Can't resolve 'fs' in '/home/minskmaz/projects/statesync/node_modules/gun/lib'
 @ ./node_modules/gun/lib/rfs.js 7:10-23
 @ ./node_modules/gun/lib/store.js
 @ ./src/index.js

**Comment by negue** [comment]
@minskmaz add this to your package.json

```
  "browser": {
    "fs": false
  }
```

**Comment by amark** [comment]
@minskmaz @negue would it help if this was in gun's package.json at all?? I'm a total idiot when it comes to packaging junk. So please send me a PR if this will help it!

Thanks so much for helping each other. YOU ROCK!
