### ISSUE TITLE
Is there a stable storage API for browser and node i should be using?

### ISSUE THREAD

**Issue by nival999** [amark/gun#731]
Is there a stable storage API for browser and node i should be using?

If i do this:

1. Start nodejs. Put something. Wait for  ACK.
2. Start browser. perform a get request on something.

It fails. Says the data  is `undefined`. Keep refreshing browser, still undefined

BUT, if I 
3. Leave the browser open,
4. Restart the nodejs process, 
5. Wait for it to sync
6. Refresh the page, 

The data DOES appear.

So, why does this happen? to make us crazy, yes

**Comment by nival999** [comment]
behavior is replicable with {localStorage:true, radisk:false}

**Comment by amark** [comment]
waaaaaaah?

@nival999 and you are saying this is true regardless of whether you are using RAD?

Or are you saying it is ONLY true if not using RAD?

**Comment by nival999** [comment]
Yes, it happens when getting from `user` objects (possibly more) on the Gun 2019 and 0.9999987 release

Any advice for debugging would be useful

**Comment by nival999** [comment]
It happens both times. When accessing the `user` object. Sometimes restarting the nodejs process doesn't help.

Can you please help me debug this with something already in the codebase @amark? Like by providing me with a way to do any of the following:

1. A way to force a `get` request to sync with a remote peer instead of the local gun
2. A way to view the graphs currently available in the gun instance (like gun.once(function(data){[[graph(data]]]});
3. A way to log the graphs currentl available in the gun instance (like gun.once(function(data){[[console.log(data]]]});

**Comment by nival999** [comment]
The problem still happens with user.create and user.auth. This makes me think it is a network issue or storage issue

**Comment by nival999** [comment]
I have figured out it was my fault. Here are some things i learned:

1. The username and password `user.create` will create a SEA pair at the user's root. be careful not to return the auth callback
2. Other user's can't always read the user's root, it's best to add a new public graph node to the user node for people to read
