### ISSUE TITLE
How to know when browser peer has finished syncing?

### ISSUE THREAD

**Issue by nival999** [amark/gun#732]
I'm trying to query a data on the remote node.js server from the browser

It is really inconsistent on fresh sessions (i.e. closing private/incognito windows and re-opening them). It seems the data doesn't load the first time a user visits the page and even on subsequent refreshes unless the server is also refreshed

It could be an issue where the small amount of data i have in gun hasn't been uploaded yet. how can i check this to know if the browser has synced the keys yet?

**Comment by amark** [comment]
@nival999 do you have heavy objects, out of curiosity?

Without a schema, `.once` has to "guess" when data is done, I'm unfortunately not sure there is any good way to fix this except by using a schema.

Or are you saying this is an issue with writing data?

**Comment by amark** [comment]
For now, the answer to this is by using a schema.

If I misunderstood the question, please re-open.
