### ISSUE TITLE
Data disappears on heroku deploy

### ISSUE THREAD

**Issue by steve-vincent** [amark/gun#740]
I used the 'deploy to heroku' on gun homepage, which seems to work fine for a bit... but doesn't persist data. After a day or two, any "notes" or "thoughts" written on the demo app ( <yourapp>.herokuapp.com/gun) are cleared.

Has anyone else seen this? Is it an issue with heroku or gun? 
Is there a more reliable platform to deploy a hosted gun server?

**Comment by amark** [comment]
Unless you add the S3 environment variables to Heroku, Heroku runs in-memory only. So it is usual for it to reset after pushing. 

However, your browser should also have a copy of the days, and resync it. Did you ever delete / reset your browser data?

**Comment by steve-vincent** [comment]
I see, thanks. Sounds like heroku issue then.
Heroku docs said free version would hold data. Imust have misinterpreted... or I dont understand if/how gun uses that.

So if I install gun server on a hosted server instance (vps or docker), then data should persist on server... will try that.
