### ISSUE TITLE
Versions after and including 0.2019.420 break login for some peers

### ISSUE THREAD

**Issue by go1dfish** [amark/gun#742]
Using node 10.14.2

    const Gun = require("gun");
    const gun = Gun({ radisk: false, localStorage: false, peers: ["https://notabug.io/gun"] });
    gun.user().auth("testuser2", "password", ack => console.log("ack", ack));

This code successfully logs in prior to .420, breaks afterwards.

Adding a setTimeout of 100ms or so around the call to auth avoid this, but it's undesirable and seems flaky as a workaround.

**Comment by go1dfish** [comment]
This is also affecting the browser and I've had to wrap my auto-login code in a setTimeout

**Comment by amark** [comment]
@go1dfish now fixed in 0.2019.426 :D
