### ISSUE TITLE
Add some logic before gundb synchronization

### ISSUE THREAD

**Issue by Youfosk** [amark/gun#747]
I want to add some logic before the gundb synchronization( Check something like user alias, public key and ...), Is there any document about this( in sea and gun)?

**Comment by amark** [comment]
You probably need to implement a wire adapter.

SEA itself is a wire adapter that acts like a "firewall" before passing data `in` to gun.

https://github.com/zrrrzzt/bullet-catcher is a simple example of doing a token check before passing `in` to gun.

Note: writing wire adapters is pretty low level, and does not have any of the conveniences of GUN's chaining API. You have to understand how the wire spec works, if you really want to dig into this, check out: https://gun.eco/docs/Porting-GUN

It might be easier to just do your logic **before** saving data like:

```
saveData(chain, data){
  data = data; // do logic here;
  chain.put(data);
}
```

But that may not be powerful or low level enough.

Quite a few people now on the https://gitter.im/amark/gun are getting better and better acquainted with the wire spec, so we'll be able to pick up the conversation there. :)

Closing! Feel free to re-open if anything else. :)
