### ISSUE TITLE
Using just the networking layer?

### ISSUE THREAD

**Issue by LiHe93** [amark/gun#749]
Sorry if a bit noob-ish.
Is it possible to use only the networking portion of gun to enable communication between browsers and non-browser clients?
I need the clients to send/recieve information from each other very low latency (atleast 20 times per second) and i dont need the data to be persistant or reliable, and all the peers/clients know about each other. I think it would be more efficient to skip writing it to the db and subscribing to changes etc.

For context:
I'm trying to port an old tcp/ip game with server/client architecture to browsers using emscripten.

Thanks a bunch!

**Comment by amark** [comment]
@LiHe93 not at all! :)

`gun._.on('out', {body: msgHere})`

Then you'll want to listen:

```
Gun.on('opt', function(root){
  this.to.next(root);
  if(root.once){ return }
  root.on('in', function(msg){
    this.to.next(msg);
    if(msg.body){ /* your logic here */ }
  });
});
```

Or something kinda like that.

Probably will get faster replies in the https://gitter.im/amark/gun :)

Also! We all want to see the game and any demos you have of it!!!! Show us!!!
