### ISSUE TITLE
Using time-streaming DB  within Gun? 

### ISSUE THREAD

**Issue by Tedko** [amark/gun#751]
There's probably better way to implement the time-streaming storage for Gun. @jack-works will explain in details.

**Comment by amark** [comment]
`.set` already uses time-sorted generated UUIDs. :)

```
gun.get('myTimeStream').set({foo: 'bar'})`

Combine that with latest https://gun.eco/docs/RAD#lex feature

And you can get some pretty cool features, like infinity scrolling! :)

**Comment by Jack-Works** [comment]
@Tedko maybe the new feature can resolve this problem? So I'm not posting details before I check the doc

**Comment by Tedko** [comment]
@jack-works Sure. I just checked the doc of #lex and I don’t think this solve the problem we may encounter. Will let you double check this.

**Comment by amark** [comment]
oh interesting, could you explain how the use case is different then (?)

One of the more important lower-level goals of GUN is that it is emergent/composable to build anything else (tho whether I have easy/framework/etc. for that feature is a separate matter), but just trying to keep possibilities open.
