### ISSUE TITLE
once() subscribes to updates.

### ISSUE THREAD

**Issue by huhsame** [amark/gun#752]
Hello, I have a question about `.once()`.
as mentioned in the document, `.once()` gets current data **without subscribing to updates**.
However, In my project, it is alive for subscribing.

Please check my code.
```
function initAScene(){
    sceneG.get('children').map().once( init );
}

function add(){
	sceneG.get('children').set( objG );
}
```
`initAScene()` is called only one time to initialize the scene at the first time. 
After that, whenever I `add()` to sceneG, the callback of the `.once()` in the `initAScene()` is called even 10 minutes and more later! 

I want it to stop subscribing updates after initializing.

gun version is 0.2019.515.

**Comment by amark** [comment]
@huhsame yes, I think I know what is going on.

The API docs are very long / large, so it might be pretty easy to miss this section in https://gun.eco/docs/API#map about chaining maps with onces:

`map().once()` gets each item in the table once, including new items as they arrive!

`once().map().once()` gets the table once, then gets each item in the table once. This is probably what you want.

`once().map().on()` is get table once, but realtime updates to each item.

` map().on()` is realtime updates to the table, realtime updates to each item.

Do you think this is it? Let me know if this fixes it `once().map().once`, if it does not, please re-open.

I'm a fan of your work, BTW! Would love to see more demos!!! :D :D

**Comment by huhsame** [comment]
I missed this part. thanks.

I saw your tweet! thanks for your awesome gun. 
I also hope to show you next demo  :D
