### ISSUE TITLE
[Question] Get sub nodes from root nodes

### ISSUE THREAD

**Issue by Jack-Works** [amark/gun#753]
Let's say we have a gun instance like this.

```ts
const gun = new GUN<{
    nodeA: { [key: string]: number }, // means gun.get('nodeA').get(anyString).put(anyNumber) 
    nodeB: { [key: string]: string }, // means gun.get('nodeB').get(anyString).put(anyString2) 
}>()// 
```

Question:
- Can I get all object stored in `.get('nodeA')`?
- Can I get all object stored in the gun without knowing there is a node called "nodeA" or "nodeB"?

(I'm asking if the node is enumerable in the non-root node or the root node. I want to keep my root node secret (if anyone else doesnot know the node called "nodeA").)

**Comment by Jack-Works** [comment]
@amark

**Comment by amark** [comment]
I assume you mean data node, not peer node.

`gun.get('a').on(cb)` will get everything 1 layer deep.

Extensions like `lib/open` and `lib/load` will recursively do this for you

`gun.get('a').open(cb)` will get all layers deep.

Historically `Gun().on(cb)` or `Gun().map()` has not worked, however this may change in the future.

Previously, there was no way to query/ask for data if you did not know at least 1 exact match.

But if you are using RAD, we've recently introduced [Lexical](https://gun.eco/docs/RAD#lex) lookups.

This would potentially let other peers discover "hidden" data nodes.

Unfortunately, as always, it is probably better to use cryptography for security instead.

:( I also was playing around with the idea of "non-discoverable security by obscurity" data nodes, but even if I reverted to the older version, there is always danger of the data being leaked/exposed and then it is game over. :(

Even with the new version, some types of data might work with "discoverable anonymized data by obscurity", even if somebody were to scan over the data and see it they wouldn't know what it is for. This should already be data that is considered public, but anonymized correlations. Please take this with extreme caution, I do NOT recommend it, but I wanted to at least mention it as *a* concept, not whether it is a good one.

**Comment by Jack-Works** [comment]
Yeah, we are deciding using "discoverable anonymized data", we want to do a sha512 hash on the key by ourself to keep the key anonymized. Does it built-in in gun?

**Comment by amark** [comment]
@Jack-Works 

`await SEA.work('a', 'b', null, {name: "SHA-256"});`

Options named after WebCrypto options.
