### ISSUE TITLE
undefined returned when using put as returning a promise

### ISSUE THREAD

**Issue by sirpy** [amark/gun#758]
here's a demo of a bug in ".then" it happens when hammering with concurrent puts.
https://codesandbox.io/s/gundbputundefinedthenerror-gnvpk
It happened to me when load testing our server. if you treat put(...) as "promise" either by doing await or adding .then() then put() sometimes returns undefined. and you get exception "cannot call then of undefined".
puts callbacks are returned ok. The demo prints the errors, summarize how many undefined and also counts the callbacks.

**Comment by sirpy** [comment]
@amark 
can you comment on this?

**Comment by sirpy** [comment]
@amark you are right, i've actually implemented in the past putAck (ie a put that returns a promise) in order to solve it but I forgot:)

**Comment by amark** [comment]
@sirpy thanks, I super appreciate that.

You should share your `putAck` module with @Dletta @jacobpdq and the rest of the community, as they'd find it valuable!

**Comment by jacobpdq** [comment]
Yeah definitely... I was... awaiting it

**Comment by amark** [comment]
ROFL

**Comment by Dletta** [comment]
Here my code for an put that returns a Promise that either:
- Resolves and returns an object containing a gunRef of the item you put in and the ack of the item you put in
- Rejects and returns ack.err if error occured

```
Gun.chain.ackPut = async function (item) {
  var gun = this;
  gun.put(item, function(ack) {
    if(ack.err){rej(ack.err)}
    res({reference:gun, ack:ack})
  })
}
```

**Comment by sirpy** [comment]
@Dletta you forgot the new Promise in your snippet
@jacobpdq 
Here are our gun extensions it includes
.putAck
.secretAck
.decrypt -> opposite of secretAck

https://github.com/GoodDollar/GoodDAPP/blob/master/src/lib/gundb/gundb-extend.js
