### ISSUE TITLE
`.once(` not waiting for all peers to ack before triggering timeout debounce

### ISSUE THREAD

**Issue by mitra42** [amark/gun#762]
See https://github.com/internetarchive/dweb-archive/issues/106 

On research on call today with @amark , there appears to be an issue where .once is returning with undefined prematurely when accessing via the hijacker (in https://github.com/internetarchive/dweb-transport ) 
Interim solution is to add `{wait: 2000}` to all calls using .once though the downside is that any calls to gun that fail will delay the UI by up to 2seconds. 

@amark said he'll look into why that has happened as appears to be a regression.

**Comment by amark** [comment]
@mitra42 should be fixed now in latest commit, will go out in the next NPM publish. Closing! :)

Note: (the opposite of this issue) Configuring GUN to have 0 peers & 0 storage may timeout, but I think that happened before anyways, and is an edge case I'm not going to prioritize for a looong time.

**Comment by mitra42** [comment]
Thanks - I'll take a look when I get a chance and see if its working again. 

I'm not sure what that edge case problem was ?
