### ISSUE TITLE
Express.js Breaks GUN 0.2019.711 with RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by TensorTom** [amark/gun#769]
Has some update happened? I installed my fork of superPeer on a new host and got an error.

https://github.com/TensorTom/superPeer/blob/master/combo.js

```
node_modules/gun/gun.js:69
		Type.obj = {is: function(o){ return o? (o instanceof Object && o.constructor === Object) || Object.prototype.toString.call(o).match(/^\[object (\w+)\]$/)[1] === 'Object' : false }}
		                                                                                                                              ^

RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at is (/home/user/bin/webrtc/superPeer/node_modules/gun/gun.js:69:129)
    at map (/home/user/bin/webrtc/superPeer/node_modules/gun/gun.js:123:16)
    at Object.Type.obj.empty (/home/user/bin/webrtc/user/node_modules/gun/gun.js:106:12)
    at Object.each (/home/user/bin/webrtc/superPeer/node_modules/gun/gun.js:844:48)
    at map (/home/user/bin/webrtc/superPeer/node_modules/gun/gun.js:131:19)
    at Function.each (/home/user/bin/webrtc/superPeer/node_modules/gun/gun.js:845:6)
    at map (/home/user/bin/webrtc/superPeer/node_modules/gun/gun.js:142:18)
    at IncomingMessage.each (/home/user/bin/webrtc/superPeer/node_modules/gun/gun.js:845:6)
    at map (/home/user/bin/webrtc/superPeer/node_modules/gun/gun.js:131:19)
```

**Comment by TensorTom** [comment]
I had to revert to the previous version in order to run my superPeer.

**Comment by amark** [comment]
@TensorTom what parameters/options do you pass `Gun(`? This'll help me out in debugging, thanks!

**Comment by TensorTom** [comment]
@amark you can see in the link I provided https://github.com/TensorTom/superPeer/blob/master/combo.js

**Comment by amark** [comment]
@TensorTom does this happen immediately on start/boot, or only triggered when something else happens?

**Comment by amark** [comment]
@TensorTom I cannot get it to crash.

How do I replicate?

**Comment by TensorTom** [comment]
it happens immediately. just load up 2 letsencrypt cert files you should have in your `/etc/letsencrypt/live/yoursite.com/`

you need `cert.pem` and `privkey.pem` in your `superNode/cert` directory. I doubt you need to do all that to reproduce but if you want to run `combo.js`, that's how you do it.

**Comment by amark** [comment]
@TensorTom I updated the `cert` with the ones you privately sent me.

Ran combo.js

still no crashing! :/

**Comment by amark** [comment]
`npm update` needed

**Comment by amark** [comment]
@go1dfish @TensorTom 

Express.js apparently has a circular object my options infinitely iterate over.

I need to postpone this till after dWeb Camp since that is 1 day away and I still gotta install everything.

But **obviously** people gonna be using Express with GUN, so this is a must-need fix.

**Comment by sirpy** [comment]
@amark any chance getting this fixed soon?

**Comment by amark** [comment]
@sirpy @TensorTom @go1dfish should be fixed in latest NPM published.
