### ISSUE TITLE
Data storage serialization

### ISSUE THREAD

**Issue by metasean** [amark/gun#78]
Between commit #4212bc29d1 and #6a34359f02 ([diff](https://github.com/amark/gun/compare/4212bc29d1f464c29b77fc65303b276203b2e85f...6a34359f021038634b81bd38e59ada05a1809166)) the data serialization was changed.  For anyone with server data in the previous format, gun appears to break after this point; there is no old data, there is no new data, there is no informative console.log output, there is no informative terminal output, there is simply nothing!  

*Patch:*
Manually delete the server's existing data file (e.g. data.json).  This will allow gun to create a new data file in the new format.

**Comment by amark** [comment]
"Fixed" with https://github.com/amark/gun/wiki/Migration-Guide ! Closing.
