### ISSUE TITLE
Possibly calling wrong Shim in SEA.js

### ISSUE THREAD

**Issue by Dletta** [amark/gun#781]
This could explain sometime nodejs process not working.
In the pair generation function on line: https://github.com/amark/gun/blob/e5589d435c9c138113f834ec329eaa3c9708ac0a/sea.js#L306

```javascript
var ecdhSubtle = shim.ossl || shim.subtle;
      // First: ECDSA keys for signing/verifying...
      var sa = await shim.subtle.generateKey(S.ecdsa.pair, true, [ 'sign', 'verify' ]) 
                        //<--- shim.subtle should be replaced with ecdhSubtle
                       // to choose either ossl or subtle platform depending
      .then(async (keys) => {
        // privateKey scope doesn't leak out from here!
        //const { d: priv } = await shim.subtle.exportKey('jwk', keys.privateKey)
        var key = {};
        key.priv = (await shim.subtle.exportKey('jwk', keys.privateKey)).d;
             // too
        var pub = await shim.subtle.exportKey('jwk', keys.publicKey);
            // too
        //const pub = Buff.from([ x, y ].join(':')).toString('base64') // old
        key.pub = pub.x+'.'+pub.y; // new
        // x and y are already base64
        // pub is UTF8 but filename/URL safe (https://www.ietf.org/rfc/rfc3986.txt)
        // but split on a non-base64 letter.
        return key;
      })
```

**Comment by amark** [comment]
@Dletta are you aware of an example of NodeJS not working when ossl/text-encoding IS installed?

You'll notice a few lines down `ecdhSubtle` is used. However, in my refactor trying to make things work about half year ago, I converged everything to OSSL and got rid of `@trust/webcrypto` , so at this point, both `shim.ossl` and `shim.subtle` point to OSSL in NodeJS.

So this should be correct, unless you're finding a replicable crash/bug? (Obviously it crashes if ossl/text-encoding not installed, so ignoring those).

**Comment by Dletta** [comment]
Thanks, I was not aware of that. I just saw the mismatch in variable and since that happens to me a lot, I projected unto your code as a typo. I did not have another known issue to link this to.

**Comment by amark** [comment]
@Dletta you are right in that it is a typo in the sense that it is in the process of me refactoring... I tried not changing code that wasn't breaking tests :P and then publish ASAP rather than trying to "clean things up" for fear it would break more things - this can always be done later or via PRs.
