### ISSUE TITLE
NOENT: no such file or directory errors

### ISSUE THREAD

**Issue by sirpy** [amark/gun#786]
I get lots of this errors when running tests
```
   { '@': 'd5l5w0e7s2v',
      err:
       { Error: ENOENT: no such file or directory, open 'test/test.json--detectOpenHandles'
         errno: -2,
         code: 'ENOENT',
         syscall: 'open',
         path: 'test/test.json--detectOpenHandles' },
      ok: undefined,
      '#': 'Onq8EuNST' }
```

As you can see there is something strange in the file name, --detectOpenHandles this is one of jest arguments.
I've found in the code that in lib/stats.js you create a file and append to it argv[2] so this must be the place.

**Comment by amark** [comment]
@sirpy thanks for catching this.

I've deleted the code `argv[2]` that does this to fix.

This will go out in the next version.

👍 👍 👍 thanks for debugging it for me! Made this super easy!
