### ISSUE TITLE
Gun warning during install upgrade

### ISSUE THREAD

**Issue by mitra42** [amark/gun#788]
Gun's install currently outputs a warning "text-encoding@0.7.0" is no longer maintained. 

Not a big deal - till you combine it with all the other warnings from other packages :-)

**Comment by amark** [comment]
@mitra42 thanks! I think the package is actually "finished" and thus why it was archived by the author.

It correctly does the job and has half million downloads every week according to https://www.npmjs.com/package/text-encoding .

If you know of another package that is better and/or replaces it, please let me know.

Else wise, it is a pretty critical polyfill/shim for NodeJS to support Cryptography stuff. It does 1 thing, and does it well, and has been bug free for all our use cases.

Closing, unless you can recommend other better more stable (and simple/dependency-free) packages to replace it. Sucks to have the log tho :( don't know what to do without it though, thanks for the note about it, just gonna have to keep with it.
