### ISSUE TITLE
.then() does not work correctly with set

### ISSUE THREAD

**Issue by Jack-Works** [amark/gun#794]
![image](https://user-images.githubusercontent.com/5390719/62996340-f4074600-be96-11e9-9e13-196fa644a9a2.png)

**Comment by Jack-Works** [comment]
It only returns the first value

**Comment by Dletta** [comment]
Hi @Jack-Works 
You can try this code:
```
Gun.chain.list = async function (limit) {
var gun = this;
var array = [];
gun.map().once((data, key)=>{
 array.push(new Promise((res, rej)=>{
   res({data:data, key:key})
 })
 )
})
await sleep(limit);
return Promise.all(array)
}

function sleep (time) {
  return (new Promise((res, rej)=>{
    setTimeout(res, time);
  }))
}
```
Just be careful as this will resolve the promise after the limit is reached, however the map will continue in the background

**Comment by Dletta** [comment]
@amark You can close this issue, as it's not a gun error. 

@Jack-Works Promises only resolve one time, so you need to use above code to return multiple promises via Promise.all (it returns an array of results)

**Comment by Jack-Works** [comment]
> @amark You can close this issue, as it's not a gun error.
> 
> @Jack-Works Promises only resolve one time, so you need to use above code to return multiple promises via Promise.all (it returns an array of results)

I think gun should resolve all items in the set and resolve an array

**Comment by Dletta** [comment]
My code can do this for you, however Promises are not built in this way. If you just use 'normal' .then it will only ever resolve with the first item.

**Comment by Jack-Works** [comment]
If you say this is the correct behavior, then the semantic of `then` function is strange.

It should be a helper that makes things "promisify" and it does on `get` but not sharing the same semantic with `set`. If using `then` on non-set items return `Promise<item>`, there is no reason `then` on set return the first item of the set instead of `Promise<item[ ]>`

**Comment by amark** [comment]
@Jack-Works @Dletta more than happy to pull any changes to `then` to make it behave however people would normally expect. :)

**Comment by Dletta** [comment]
@Jack-Works 
Let me explain what I mean.

.then doesn't support .map at this time. However, I am offering the code above to allow you to return an array from a map via a promise.

.then just returns a promise for one value as below
```javascript
Gun.chain.then = function() {
	var gun = this; //when using .map, the first item of the set will trigger the then
  return (new Promise((res, rej)=>{ // as soon as this promise is returned the first item will resolve it
// promises can only be resolved once, so even if .map calls this again, the promise is already resolved and therefore you do not get more than the first item
    gun.once(function (data, key) {
      res(data, key); 
    })
  }))
};
```

So currently it's the correct behavior in the sense that it does what the code and javascript intends to it to do.

This code below will upgrade .then to behave correctly for both sets and singular data
```javascript
/* Combined promise for once and map
   @param limit = integer defaults to 100 ms
   */
   Gun.chain.then = async function (limit) {
     var gun = this, cat = gun._;
     if(!limit){limit = 100}
     if(cat.subs){
      var array = [];
      gun.map().once((data, key)=>{
       array.push(new Promise((res, rej)=>{
           res({data:data, key:key})
         })
       )
      })
      await sleep(limit); // if we do not sleep we return the promise before .once has fired once
      return Promise.all(array)
     } else {
       return (new Promise((res, rej)=>{
         gun.once(function (data, key) {
          res(data, key); //call resolve when data is returned
         })
       }))
     }

     var chain = gun.chain();
     return chain;
   }

   function sleep (time) {
     return (new Promise((res, rej)=>{
       setTimeout(res, time);
     }))
   }
```

However, the .map does continue to call .once even after we return the array (which is returned after the limit is reached) and if you are trying to retrieve more than 60thou records, at the moment it can create a huge cpu load.

**Comment by amark** [comment]
@Dletta thanks a ton for solving this!!! :)
