### ISSUE TITLE
Gun.SEA.secret() issue when launched several times

### ISSUE THREAD

**Issue by JPBlain** [amark/gun#795]
I faced an issue when trying to use Gun.SEA.secret() function several times in a row with different parameters. It ends up producing the wrong shared secret as in the example below.

Lets assume I have an array of 4 public keys. If running the following code, the results are wrong with one of the computed shared secrets being repeated 4 times.
```
      array.forEach(async (pub)=>{
        let shared = await Gun.SEA.secret(pub,pair);
        console.log(pub,">",shared);
      })
```

```
_rf2SL4-7BEfQurCvD3zUlpW7xLq7cmC... > xsL4HOyPQcF195ahBeFzXbQzPUlietdK285bHU0l11s
0KfLsOPkM3aHHEhzjJiEfEfE4pZFed4K... > xsL4HOyPQcF195ahBeFzXbQzPUlietdK285bHU0l11s
F_GrJVdLW0xZRvSmEzbdcr6M2v5UEhpQ... > xsL4HOyPQcF195ahBeFzXbQzPUlietdK285bHU0l11s
DQ9W5iuGe21HcLCycXlAXhB7fWRTYKWY... > xsL4HOyPQcF195ahBeFzXbQzPUlietdK285bHU0l11s
```
When making sure each Gun.SEA.secret() call is first completed before launching the next one, the results are right.
```
      for (let pub of array) {
        let shared = await Gun.SEA.secret(pub,pair);
        console.log(pub,">",shared);
      }
```
```
_rf2SL4-7BEfQurCvD3zUlpW7xLq7cmC... > xsL4HOyPQcF195ahBeFzXbQzPUlietdK285bHU0l11s
0KfLsOPkM3aHHEhzjJiEfEfE4pZFed4K... > HRW5Fg5OnG9Mw6ZluG47CJFdhWK7DHySKBzYx3obIZY
F_GrJVdLW0xZRvSmEzbdcr6M2v5UEhpQ... > MBlFmkRqEYTTlkHsO6LfL0ciMx5Ai5fQw7WVMvfNWnI
DQ9W5iuGe21HcLCycXlAXhB7fWRTYKWY... > Ln2srlrPczCVGIZgvbkY1NTUQfitzQUM0Qvplps6qfU
```
I guess it must have something to do with the use of Object.assign() in the function.

The horrible workaround I found is to wrap Gun.SEA.secret() to make sure it is entered once at a time and delay execution otherwise. Any other advice ?

**Comment by amark** [comment]
@JPBlain thanks for this report, certainly needs to get fixed!

If you / anybody else could contribute directly that'd be amazing, I'm trying to fix RAD/GUN storage stuff (finally figured out the debug!).

The `Object.assign` as you see is here https://github.com/amark/gun/blob/master/sea/secret.js#L16 , I write all ES5 code, so I don't actually understand what is going on with this code and would appreciate anyone who could refactor it to something that makes it easier for me to maintain. Tho I'm also thankful for the contribution to SEA that made this work in the first place, really put us far ahead.

@JPBlain how'd you hear about SEA? What are you working on building? :)

**Comment by sirpy** [comment]
@JPBlain @amark 
it does seem that the object.assign modifies S.ecdh which is shared,
i don't know if not changing it will ruin the logic of the rest of the process
i've made a little fork that simply reverse the assign values os S.ecdh isn't modified but the resulting props variable will be the same.
https://github.com/GoodDollar/gun/tree/SEA-concurrent-possible-fix

@JPBlain can you test my branch?

**Comment by amark** [comment]
@sirpy YOU ARE INCREDIBLE!!!!! :D :D :D <3 <3

@JPBlain could you confirm and then we can pull @sirpy 's fix!?

**Comment by JPBlain** [comment]
@sirpy : This is great ! The fix solves the issue with no side effects at this stage according to my tests tonight. Thanks a lot !

@amark : I am in the process of adapting an ionic PWA that I developed earlier this year to support an international law moot court competition. I want to remove the need for the centralized firestore database. 

Sorry for my late answers, I just came back from (almost tech-free) vacation. :-)

**Comment by amark** [comment]
👏 👏 👏 @sirpy 👏 👏 👏 🎉 !!! :D

Closing :D :D

@JPBlain, nice! I did debate years ago, was interested in doing moot court at some point, but never got around to it.

Important Q: Are you having any problems with SEA in the Ionic PWA? People doing React *Native* apps have had issues with Apple blocking WebCrypto, even though WebCrypto (which SEA uses) is available in browser.
