### ISSUE TITLE
Auto Reconnect

### ISSUE THREAD

**Issue by amark** [amark/gun#80]

**Comment by amark** [comment]
It only attempts to reconnect when you write data, but in my use case lately I've found that I want/need it to auto reconnect period, or else I have to manually refresh the chat app or other examples to see the latest data if I happen to disconnect. This is annoying.

Also, the JSONP fallback is not fully implemented yet, and needs to be - but that should be another issue.

**Comment by metasean** [comment]
Auto-reconnect  has been added  for Web Sockets.

**Comment by amark** [comment]
We're closing this issue, but JSONP fallback is still open - see #41 .

**Comment by amark** [comment]
I believe Jesse added this recently. Closing!
