### ISSUE TITLE
creating a user fails with localStorage=false 

### ISSUE THREAD

**Issue by ubiqui** [amark/gun#806]
Hi, 

if localStorage=false creating a user results in :'User is already being created or authenticated!'.
To replicate place the attached file in examples and serve ...

Cheers,
[createUserIssue.zip](https://github.com/amark/gun/files/3559895/createUserIssue.zip)

Ubiqui

**Comment by Dletta** [comment]
@ubiqui looks like you are connecting to a peer and when you create a user the user is saved on the peer (and since you include rindexeddb also in browser)
If a user and password combination exists, user.create returns an error that the user already exists, this is not an error, rather an expected behavior
User.auth is what you should use when the user exist
This will log you in

**Comment by ubiqui** [comment]
@Dletta ... ok, but if I clear the the browsers data => clean start => this still happens.

Is that also intended?

Thnx

**Comment by Dletta** [comment]
If you are connecting to a peer it’s likely that peer has data that you are not deleting and he will stream it back to you.

Also, if you use rindexeddb, localStorage.clear() will not erase or clear the data

**Comment by ubiqui** [comment]
I cleared the Applicationdata in the browser: Application => ClearStorage. Also I tried it with a unique alias which has not existed before and still it happens. If you do a fresh gun checkout and insert the provided file to the examples folder you can replicate the issue. Maybe change the alias to some really unique string to be on the safe side.

**Comment by Dletta** [comment]
Seems like a real bug then

**Comment by ubiqui** [comment]
now works in version 0.2019.910

**Comment by amark** [comment]
yaaaaayyyyyy!!!

**Comment by amark** [comment]
@ubiqui thanks for reporting this. And please do jump into the the community chat ( https://gitter.im/amark/gun ) tons of super friendly helpful people there!
