### ISSUE TITLE
Replace GIFs in readme.md with APNG files

### ISSUE THREAD

**Issue by ryazo** [amark/gun#807]
https://en.wikipedia.org/wiki/APNG

APNG has a modest level of compression, so it would save user bandwidth.

**Comment by amark** [comment]
This would be great, do you know any online converters? Would <3 <3 <3 if you could submit this as a PR request, I'll pull!

**Comment by amark** [comment]
would super appreciate this as a PR @ryazo . Gonna close till then, to keep issues focused on bugs.
