### ISSUE TITLE
private.html example doesn't update data

### ISSUE THREAD

**Issue by olivier-nerot** [amark/gun#808]
The https://github.com/amark/gun/blob/master/examples/basic/private.html is almost working with two windows (signup, signin, search by public key are ok), but data modified on first user's window are not updated on the second window (on Chrome 75.0.3770.100, with gun@0.2019.726 running)

The `find.get('profile').on(function(data, key, at, ev){...}` is well called when profile is edited on the first window, but in `Gun.node.is(data, async function(v, k){...}` on line 129, the async function is never called, whereas data looks fine :

```data: Object
born: {ct: "COGmnqYhIqua0qkU8ydfhiufsk5fkQ==", iv: "7A0/eAXKjtXG13iYx9IQ", s: "VS+0gHYKmo/B"}
edu: {ct: "iBA/sdBgNjUmVjnSElRHT4SRL//GZmse", iv: "GFaK/31WHo5E5dHrXfkI", s: "STtA/+52G+R2"}
name: {ct: "Rl+J32EoE/I18PgMcZrP87QsZD4t", iv: "L17pRNBNOhECzIPuobL4", s: "2a7ip8Kh+zh+"}
skills: {ct: "AaMSFs6lIGuUSOaDiGZd7vQRwqWKgMQ=", iv: "DFT2yK/yTI8xasnyHaW0", s: "q0JG4rx8Awm0"}
_: {#: "jzl9rf8001asUzWCBGUvGqI~hDGi1MCdTe0vFsfIBV8Gk42Evb…voEY.TD85zmEpUs1_1wfPd_QHa0KytFoCNoP7sM9MAqQpIOM.", >: {…}}
__proto__: Object
```

As the example is one year old, and has a few warnings (user.pair is deprecated for example), I wonder how to make this example work, or if any change must be done, dealing with `gun.node.is` call.

**Comment by amark** [comment]
@olivier-nerot thanks for the heads up - and WELCOME TO THE COMMUNITY!!!!

I think this is related to https://github.com/amark/gun/issues/783 , could we merge with it?

I think SEA's adapter is trying to mistakeningly parse SEA's encrypted data, when it should only be parsing verification data.

Unfortunately, I'm piled up with bug fixes for RAD (our storage engine), so I either need you to help recruit somebody from the chat room ( https://gitter.im/amark/gun ) to help with this, or wait until I can get back to SEA.

**Comment by scenaristeur** [comment]
hi, shouldn't be this example update d ? https://github.com/amark/gun/blob/210a5834c648b69eb6a4d155fd0bbae9e76a6073/examples/basic/private.html#L96
