### ISSUE TITLE
Trouble connecting to Gun when server is spun up inside of Electron

### ISSUE THREAD

**Issue by mboperator** [amark/gun#815]
## Context
I'm building a decentralized story telling desktop application using Electron.
The Electron app is comprised of a server and a client.

The client is a React app.
The server is a node server running Express with Gun middleware.

Package Versions
```
"express": "~4.16.1"
"gun": "^0.2019.726"
"electron": "4.0.8"
"node": "12.10.0"
```

## The Problem
When running the server outside of Electron in dev mode, everything works fine:
<img width="742" alt="Screen Shot 2019-09-14 at 10 54 42 AM" src="https://user-images.githubusercontent.com/1007233/64913476-c3186c00-d6f5-11e9-96a9-f065b7d84a72.png">

My Electron app is unable to hit the `Gun` websocket endpoint when the server is run from within Electron:
<img width="615" alt="Screen Shot 2019-09-14 at 1 45 02 PM" src="https://user-images.githubusercontent.com/1007233/64913485-e9d6a280-d6f5-11e9-86b7-31fcd1980880.png">
The server is able to start properly inside of Electron. `http://localhost:7000` shows my `hello world page`.

## Relevant Code Snippet
This is the Electron server:
<img width="563" alt="Screen Shot 2019-09-14 at 1 42 31 PM" src="https://user-images.githubusercontent.com/1007233/64913465-877da200-d6f5-11e9-9531-9900b0307b6d.png">

This is how I'm spinning up my express server inside of Electron:
<img width="664" alt="Screen Shot 2019-09-14 at 1 41 32 PM" src="https://user-images.githubusercontent.com/1007233/64913460-72087800-d6f5-11e9-8640-e9789f4f6da4.png">

## Things I've Tried:
- Running with different Node versions (8, 12). No dice.
- In `production`, the client app's origin changes from `localhost` to `file` so I tried adding `cors`. No dice.
- I was getting build errors from SEA + `node-webcrypto-openssl` so I switched gun to use `@peculiar/webcrypto`. Still not working.

If anyone has any example of an Express server running Gun inside of Electron that would be a huge help.

Thanks in advanced!

**Comment by mboperator** [comment]
Fixed my own issue.
The return value of `server.listen` needs to be passed into the `Gun` constructor.

<img width="662" alt="Screen Shot 2019-09-14 at 2 32 07 PM" src="https://user-images.githubusercontent.com/1007233/64913835-76845f00-d6fc-11e9-8324-db067c888e6c.png">

**Comment by amark** [comment]
Sorry about that! Glad you got it working.
