### ISSUE TITLE
Shutting down a gun node.

### ISSUE THREAD

**Issue by smari** [amark/gun#817]
Hi! 

I can't seem to find any function to close all connections and "quit". It's understandable that for most intents and purposes this isn't needed, but I'm writing a CLI tool for querying/updating/managing assets in gun, and there is a reasonable expectation that such programs eventually terminate. Is there some functionality for this that I am missing, and if not, can it be added?

Thanks!

**Comment by amark** [comment]
@smari good point! Probably a couple options:

 - (1) if you are not connecting any peers TO your peer, then you probably do not need to run the web/http/websocket server (as in, do not `Gun({web: server` skip that), this is probably what is keeping the process active/open.

 - (2) If that doesn't work, a harsh approach would be to just call `process.exit()` after you know your data has succeeded/ACKed saved.

@smari and WELCOME TO THE COMMUNITY!!!!!!!!!!! definitely jump on the https://gitter.im/amark/gun as well, super friendly people there - would love to hear you tell us more about the CLI tool! Especially as I've been trying to make RAD (the storage engine) more stable, have things been working fine?

**Comment by smari** [comment]
Thanks for a super fast reply and the warm welcomes. Option 2 was pretty obvious (if a little dirty) in retrospect ─ nice one.

The CLI tool is partially for exploratory purposes, as I'm new to Gun, and partially a bit of tooling for a project that will probably rely on Gun if things work out. I'll share if/when I have something share-worthy. :-)

**Comment by smari** [comment]
(Closing the issue, but as a side note: for CLI-purposes, it'd be convenient to be able to reduce the verbosity of the underlying library)

**Comment by amark** [comment]
@smari agreed. Do note there are some hiccups for CLI-like use cases because of RAD (the storage engine). So if you encounter any trouble please let me know on https://gitter.im/amark/gun because my goal is to make the experience as easy/seamless as possible. Sorry about `.exit(` for now, will revise that in future.
