### ISSUE TITLE
Broken gun.bye() functionality on the server

### ISSUE THREAD

**Issue by TheBolliwood** [amark/gun#820]
I wanted to use gun.bye() [as documented](file:///C:/Users/Bolle/Downloads/API%20-%20GUN%20documentation.htm#-a-name-bye-a-gun-bye-).
With `require('gun/lib/bye');` I also included the functionality on the server.

But at the following line, I get the error `TypeError: peer.bye is not a function`:

https://github.com/amark/gun/blob/14f6ba098addb10acb0969b09fdbba942d010d59/gun.js#L2151

I don't know which function peer.bye() should be but in the context I'm using it, peer.bye always is an array (which includes the content which should be put on bye).
You can see it in the following lines:
https://github.com/amark/gun/blob/14f6ba098addb10acb0969b09fdbba942d010d59/lib/bye.js#L10
https://github.com/amark/gun/blob/14f6ba098addb10acb0969b09fdbba942d010d59/lib/bye.js#L16-L21

I fixed it temporarily by replacing the line with `(tmp = peer.wire) && tmp.close && tmp.close(); `.
I'd create a pull request, but as I said, I don't know what peer.bye() should be.

**Comment by amark** [comment]
@TheBolliwood oooooooh! Thanks for pointing this out.

I recently refactored and `peer.bye()` is an API for GUN's internal peer handling system.

However, that conflicted with the `lib/bye` code, so the `peer.bye` in that module need to get renamed.

I've hastily done this and committed a new version to GitHub master (not published on NPM). IT IS NOT TESTED. Could you try it out and see if it works?

**Comment by amark** [comment]
Also, @TheBolliwood WELCOME TO THE COMMUNITY!!!!!!!!!!!!!!!!! :) :) :) 

I think I saw you on the community chat the other day? https://gitter.im/amark/gun make sure to join, super super super friendly and helpful people there!

I'm gonna pre-emptively close this. If the new version does not work though, please please please reopen/tag me here again. Thanks!!!

**Comment by TheBolliwood** [comment]
@amark Thanks for your reply!
I just tested the version and it's not working.
It seems like `mesh.hear['bye']` from the following line is never invoked.
https://github.com/amark/gun/blob/93cd24caa72a6c018e50439267b4cd90f2ba5195/lib/bye.js#L7
(I just put a `console.log` there and saw nothing)

**Comment by JamieRez** [comment]
@TheBolliwood 

Allow me to join in. My .bye() was also not working and throwing the same issues.

> I wanted to use gun.bye() as documented.
> With `require('gun/lib/bye');` I also included the functionality on the server.
> 
> But at the following line, I get the error `TypeError: peer.bye is not a function`:
> 
> https://github.com/amark/gun/blob/14f6ba098addb10acb0969b09fdbba942d010d59/gun.js#L2151
> 

I changed this line in my code to
```
typeof peer.bye == 'function' ? peer.bye() : (tmp = peer.wire) && tmp.close && tmp.close();
```

And this seems to do the trick. Not sure if this is a quick hack or a fix, but here you go. I will create a pull request for @amark

**Comment by TheBolliwood** [comment]
@JamieRez I think it's just an hack because after an array is assigned to `peer.bye` by `lib/bye`, this value would be overwritten by some function. Like @amark said:

> I recently refactored and `peer.bye()` is an API for GUN's internal peer handling system.

I don't know where in the code the `bye` property of `peer` is assigned with a function, but when it is, the functionality of `lib/bye` is lost.
With your fix you just won't get an error in this case. It changes nothing on this fact.
