### ISSUE TITLE
TODO APP not working @0.2019.711 ~ 0.2019.930

### ISSUE THREAD

**Issue by thetalazuli** [amark/gun#835]
hi amark, 
im tested todo example.

`
// todo APP not working @ gun@0.2019.711~0.2019.930 on Goocle Chrome v 65
user.create($('#alias').val(), $('#pass').val(),function(obj){
  console.dir(obj)  // not called
})
`
// gun.js
`
eve.ack = (eve.ack||0)+1;
if(!to && u === data && eve.ack <= (opt.acks || Object.keys(at.root.opt.peers).length)){ return }  // it is. 
`
// new todoApp
`
var gun = Gun({
  acks:12,
  peers:['https://192.168.11.8:8765/gun']
})
`
// new gun.js
`
if(!to && u === data && eve.ack > at.root.opt.acks){ return }
`

**Comment by amark** [comment]
@thetalazuli I just tested this and it is still working. I can't confirm/replicate your issue on https://gun.eco/docs/Todo-Dapp ?

Can you provide more details?

**Comment by thetalazuli** [comment]
im so sorry.
