### ISSUE TITLE
Saving a deep object under a user node seems to lose public key at some depth

### ISSUE THREAD

**Issue by trokster** [amark/gun#850]
Example for an authenticated usr:

usr.get("testauthed").get("arumf").set({"this": "is", "an": {"obj2": "again2"}})

will generate an unsigned node.

**Comment by amark** [comment]
Thank you @trokster , will need to look into this.

**Comment by rogowski** [comment]
Related to: https://github.com/amark/gun/issues/616 ??

Change https://github.com/amark/gun/blob/master/gun.js#L1794
 `item = gun.back(-1).get(soul = soul || Gun.node.soul(item) || gun.back('opt.uuid')()).put(item);`
to 
`item = gun.back(-1).get(soul = soul || Gun.node.soul(item) || gun.back('opt.uuid')()).put(item, null, {via: gun});`

@amark How much impact does that have?

**Comment by rogowski** [comment]
@trokster. I wrote a test with the code snippet you sent and now it's passing.
I will close this issue now but it can open if it happens again. Thanks for reporting.
