### ISSUE TITLE
Hooks into sync process

### ISSUE THREAD

**Issue by RangerMauve** [amark/gun#86]
It'd be nice if there were hooks in the synchronization process so that there was a way to customize which data will get synchronized to other nodes or not based on user defined logic.

**Comment by amark** [comment]
+1

@metasean what version tag do you think this should be targeted for?

**Comment by metasean** [comment]
This should definitely be a part of our prioritization/sharding feature set (#46) which we currently have slated for v0.5.  That's far enough in the future, that we can't make any guarantees.  However, prioritization/sharding is a definitely an important feature set, so it will get done as soon as we can reasonably do so.

**Comment by thoka** [comment]
Does an overview about planed hooks exist ?

**Comment by amark** [comment]
We've switched from a "hook" system into an event system. Here is a sneakpeak! Great question @thoka (how have you been? What have you been up to?)

```
Gun.on('put', function(at, ev){
  // write an adapter to localStorage or whatever.
});
```
```
Gun.on('get', function(at, ev){
  // write an adapter to localStorage or whatever
});
```

Both of these events are how `v0.4.x` and `v0.5.x` drivers (like localStorage, WebSockets, file.js/data.json) are implemented. It is quite clean.

In addition to that, every part of the chain (`gun = Gun().get('foo').path('bar')`) has IO events:

```
gun.on('in', function(at, ev){
  // tamper with input stream
});
```
```
gun.on('out', function(at, ev){
  // tamper with output stream
});
```

These will allow you to do quite a few powerful customizations/tweaks, etc. In fact, most of the core is built using these events.

**Comment by amark** [comment]
This is basically done now. Although quick important note, the event/hook system needs to manually call "next" in all of them and the `ev`ent is now the 'this' context, here is an example for one of them:

```
Gun.on('get', function(at){
  var ev =  this;
  ev.to.next(at);
});
```

But it works now! Closing!
