### ISSUE TITLE
Internal timeouts occur during basic tests

### ISSUE THREAD

**Issue by pszabop** [amark/gun#861]
I'm writing some tests to show how the API works and I'm finding a simple test of `then()` on a `put` results in a resolved Promise, but there is an internal timeout that delays completion of the test as well as resulting in the following message on the console:  `Error: No ACK received yet.`

Version:  0.2019.1228

Test code:

```
'use strict'
const tape = require('tape')
const _test = require('tape-promise').default // <---- notice 'default'
const test = _test(tape) // decorate tape
const Gun = require('gun/gun');
const Sea = require('gun/sea');

// this works but gets `Error: No ACK received yet.` 
// and test doesn't complete until some Gun timeout is satisfied
const GunThen = require('gun/lib/then.js')
const GunPromise = require('gun/lib/promise.js')
test('create a key value pair using promises v2', async function (t) {
  const gun = Gun();
  const value = 'value';

  const result = await gun.get('key').put({property: value }).then();
  //console.log(result);
  t.equal(result.property, value, 'result  was what we put in');

  const result2 = await gun.get('key').then();
  //console.log(result2);
  t.equal(result2.property, value, 'result2  was what we put in');

})

```
Just to show this isn't promises, the following code also spits out timeout errors:

```
test('create a user using callbacks', function (t) {
  const gun = Gun();
  const cb = function(ack) {
    console.log(ack);
    t.equal(ack.ok, 0, 'ack ok is equal to zero');
    t.ok(ack.pub, 'ack has a public key');
    setTimeout(function () {
      t.end();
    }, 20)
  }

  gun.user().create('paul@example.com', 'password', cb)

})

```

and a get put get example using callbacks that's directly analogous to the first example:

```
test('create a key value pair using callbacks', async function (t) {
  const gun = Gun();
  const value = 'value';

  gun.get('key').put({property: value }).once(result => {
    t.equal(result.property, value, 'result  was what we put in');
    gun.get('key').once(result2 => {
      t.equal(result2.property, value, 'result2  was what we put in');
      setTimeout(function () {
        t.end();
      }, 20)
    });
  });
});

```

**Comment by amark** [comment]
@pszabop hmm, `no ack, lack` often times means the storage engine isn't hooked up?

I see you're adding `require('gun/gun')` which only includes core (which has Browser localStorage in it) but not NodeJS storage (like RAD). Try `require('gun')` and see if that fixes stuff?

**Comment by pszabop** [comment]
@amark some documentation has `require('gun/gun')` and some has `require('gun')`, it was hard to tell.  I see that it is clarified in your `README.md` though.

So now when I `require('gun')`, my test completes but never exits.   Is there a `gun.hangup()` or something that I should be calling??  

Here's what the npm package `leaked-handles` says:

```
no of handles 3

tcp stream {
  fd: 17,
  readable: false,
  writable: true,
  address: {},
  serverAddr: null
}

tcp stream {
  fd: 19,
  readable: false,
  writable: true,
  address: {},
  serverAddr: null
}

unknown handle Socket {
  _events: [Object: null prototype] {
    listening: [Function],
    message: [Function]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
  type: 'udp4',
  [Symbol(asyncId)]: 22,
  [Symbol(state symbol)]: {
    handle: UDP {
      lookup: [Function: bound lookup4],
      onmessage: [Function: onMessage],
      [Symbol(owner)]: [Circular]
    },
    receiving: true,
    bindState: 2,
    connectState: 0,
    queue: undefined,
    reuseAddr: true,
    ipv6Only: undefined,
    recvBufferSize: undefined,
    sendBufferSize: undefined
  }
}

```

**Comment by amark** [comment]
For future reference, I usually just `process.exit()` in my tests.

Over chat, sounds like @pszabop knows some nice `http-shutdown` module to turn off stuff.

`Gun({multicast: false` turns off the UDP.

(maybe that way you won't need to copy/replace the list in `lib/server.js` that activates all the extraneous NodeJS features).

This mean we can close now (?)

**Comment by amark** [comment]
also please always update docs anytime, can be edited here: https://github.com/amark/gun/wiki more people who contribute the better!

**Comment by pszabop** [comment]
I was able to completely shut down gun with about a 10 second delay by adding `).unref()` to all the `setInterval()` calls in the Gun code base.   As long as your interval timers are not critical for a clean exit, `).unref()` works just fine.  All `).unref()` does is not block nodejs's exit code from continuing if outstanding timer handlers exist. 

I also passed in my own `http` servers in the constructor and used the `http-shutdown` module to monkey patch those servers so that they also exit cleanly.

In the end, I wasn't able to find the 10 second delay, so I just added this as my final test and am using the `http-shutdown` module so that there are no intra-test dependencies.

Here's my wrapper for Gun's constructor:
```
gundb.init = function(opts) {
  if (!opts) {
    opts = {};
  }
  if (!opts.file) {
    mkdirp.sync('testdb');  // gundb doesn't do this correctly, it errors out with a mkdir message
    opts.file = 'testdb/' + random.string(16) + '.json';
  }

  // always create a server even if it doesn't listen
  // to handle shutdown issues that we have to monkey-patch
  this.server = require('http').createServer();
  this.server = require('http-shutdown')(this.server);
  if (opts.port)  {
    this.server.listen(opts.port);
  }

  this.gun = Gun({peers: opts.peers, multicast: false, file: opts.file, web: this.server});
  return this.gun;
}

```

And here's the tape test I add to the end of all my test files
```
// gundb doesn't unref its internal timers and also multicast
// so force the process to exit.
test('force test to end', async function(t) {
  t.ok(true, 'forcing test to end with process.exit');
  t.end();
  process.exit();
});
```
