### ISSUE TITLE
There is no serve

### ISSUE THREAD

**Issue by linonetwo** [amark/gun#862]
```
const Gun = require('gun')

console.warn(`serve`, JSON.stringify(Gun.serve, null, '  '));
```

logs `serve undefined`

or 

```
import * as Gun from 'gun';
import Gun from 'gun/gun';
import { serve } from 'gun';
```

all don't have `serve`, which requires in server examples.

**Comment by rogowski** [comment]
Hi @linonetwo. 

`Gun.serve` is a function that GUN uses to serve static files. Why you want to JSON.stringify it?

Can you explain better what you need?

```
var Gun = require('gun')
> Gun.serve
[Function: serve]
```

**Comment by linonetwo** [comment]
Oh, sorry, that is a snippet I used to log things, maybe that made it undefined.
