### ISSUE TITLE
Typescript : is not assignable to parameter of type 'never'

### ISSUE THREAD

**Issue by morganzysman** [amark/gun#870]
Hi everyone,

I'm trying to set up gun in a ts environment. I have installed gun and types/gun.

The setup seems to be working, but i have a TS warning: What should I be doing to avoid this ?

Regards,

Morgan
![Screenshot 2020-01-07 at 14 26 10](https://user-images.githubusercontent.com/5576762/71898541-e316e400-3159-11ea-957a-ea2b7248b50b.png)

**Comment by bluelovers** [comment]
https://github.com/amark/gun/pull/898
