### ISSUE TITLE
'ok' is undefined in axe.js

### ISSUE THREAD

**Issue by sirpy** [amark/gun#877]
if '_' is empty in incoming msg it will cause the server to crash since the ok variable is undefined

**Comment by amark** [comment]
👍 thanks @sirpy just fixed this in my local commits, should go out in next release.

**Comment by sirpy** [comment]
@amark we can close this right?

**Comment by amark** [comment]
@sirpy thanks to you, yes! All the SEA changes are in NPM now too. :) THANKS TO YOU!!!! :D :D :D :D <3 <3 <3 <3
