### ISSUE TITLE
Style guide or beautifier config

### ISSUE THREAD

**Issue by RangerMauve** [amark/gun#88]
Currently it seems that this project is following some sort of compact style for the code base. The rules for it don't seem entirely clear. I would suggest adding some sort of style guide or a config for either [js-beautify](https://github.com/beautify-web/js-beautify) or [ESLint](http://eslint.org/) so that it'd be easier for people to contribute and to keep a consistent style across all the code.

**Comment by amark** [comment]
I'll probably let the community come to a consensus on this if they want, but my strong personal preference is having no style enforcement. I'm trying to keep gun core (literally just gun.js file) as being "my" style (which is generally compact, follows some general rules but has obvious exceptions to them in certain places where I feel it aesthetically looks better to break) and then everything else (modules, hooks, extensions, etc.) can be the style of whatever the respective author is (they don't have to adhere to mine).

However, if people do want to agree on a style then so be it. Would love to hear from everybody else. Just count me (and gun.js, or plugins that I write an maintain) out.

**Comment by amark** [comment]
haven't seen any further discussion on this so I'm closing. :)
