### ISSUE TITLE
Gun.put() not saving anything if running in NodeJS and AXE is enabled

### ISSUE THREAD

**Issue by rysiekpl** [amark/gun#891]
Seems like `Gun.put()` is not saving anything when run in NodeJS with AXE enabled. Test case: https://github.com/rysiekpl/gun-nodejs-bugs

You can run the testcase by cloning the repo and running:

```
docker-compose up -d && docker-compose exec gun bats /opt/gun-nodejs-bugs/tests/001-put-axe.bats
```

*Possibly related to #426.*

**Comment by amark** [comment]
Thank you, @rysiekpl !

**Comment by rysiekpl** [comment]
It's now also possible to test on different NodeJS version by building the image with a `NODEVER` build arg defined. For example:

```
docker-compose build --build-arg NODEVER=10
```

...will build the image using `node:10` docekr image as base, thus using NodeJS 10.x for testing.

**Comment by rysiekpl** [comment]
Any news on this?

**Comment by rysiekpl** [comment]
This seems fixed (same results for Node v. 10, 12, 14):

```
$ docker-compose up -d && docker-compose exec gun bats /opt/gun-nodejs-bugs/tests/001-put-axe.bats
gun-nodejs-bugs_gun_1 is up-to-date
 ✓ put() without AXE
 ✓ put() with AXE

2 tests, 0 failures
```

**Comment by dikshantrajput** [comment]
It's not fixed yet. I am having issue while putting. .put() in node is not working
