### ISSUE TITLE
https://gun.eco/docs/ pages are blank

### ISSUE THREAD

**Issue by ptsefton** [amark/gun#911]
The home page at https://gun.eco/ works but if I click either of the two buttons I get ... nothing (on chrome on a mac and on Android).

**Comment by amark** [comment]
Thank you, checking on this now. I know netlify recently emailed me about their redirects system. Thank you thank you thank you @ptsefton

**Comment by amark** [comment]
I think I fixed it.

Ugh, so frustrating, it must have been down all day. 

Thank you an INFINITE amount for reporting this.
