### ISSUE TITLE
How can I change LocalStorage for IndexedDB ?

### ISSUE THREAD

**Issue by Jusmaar** [amark/gun#915]
Hi everyone, I would like to change the storage by default in the browser, this is possible? :/ 

I tried it this way but it doesn't work for me: 

import Gun from 'gun/gun';
const gun : any = new Gun({localStorage: false});

**Comment by rogowski** [comment]
Hi Jusmaar!
Take a look at https://github.com/amark/gun/blob/master/test/rad/browser.html

**Comment by Jusmaar** [comment]
Hi rogowski, do you know how other libraries could be imported in this way -> import Gun from 'gun/gun' ?, because I'm trying to make an application with Vue :(

**Comment by rogowski** [comment]
Sorry, but I'm don't have any experience with Vue.
Have you tried create a gun bundle with all you want?
I found this https://github.com/sjones6/vue-gun

**Comment by amark** [comment]
@rogowski <3 <3 <3 for helping

@Jusmaar what error is being thrown when `import Gun from gun/gun` (?) cause this was working in the past, but seems stuff changed that broke it?

**Comment by amark** [comment]
oh also this! https://gun.eco/docs/RAD#install

Closing. If ^ doesn't work (it should), please re-open!!
