### ISSUE TITLE
Dangerous replace in peer url

### ISSUE THREAD

**Issue by jussiry** [amark/gun#918]
'http' gets replace with 'ws' in peer URL where ever it is, which might cause errors in some case.

https://github.com/amark/gun/blob/master/gun.js#L2395

Would be safer to use regexp to only replace it from the beginning of url:

```var url = peer.url.replace(/^http/, 'ws');```

**Comment by revolunet** [comment]
i guess a little pull request would be helpful :)

**Comment by revolunet** [comment]
https://github.com/amark/gun/pull/939
