### ISSUE TITLE
Geohash based proximity queries

### ISSUE THREAD

**Issue by andrewluetgers** [amark/gun#94]
This implementation uses Redis as a backend, I wonder about the viability of something like this with Gun. I really like how you can distribute and offload the hash computation to clients.
https://github.com/arjunmehta/node-geo-proximity

**Comment by amark** [comment]
@andrewluetgers yes yes yes! @metasean and I were just talking about this the other day. Starred that repo. In terms of my priorities my plate is pretty full but I would like to see this and this library looks pretty good.

**Comment by metasean** [comment]
Moved to https://github.com/gundb/gun-extensions/issues/11
