### ISSUE TITLE
Uncaught ReferenceError: sat is not defined

### ISSUE THREAD

**Issue by mnts** [amark/gun#948]
So I get this error, here is simple example of how magic happened: 

var alice = {name: "Alice"};
alice.boss = {name: "Fluffy", slave: alice};
gun.get('profile').put(alice);
Gun {_: {…}}
npm_bundle.js:1 Uncaught ReferenceError: sat is not defined
    at npm_bundle.js:1
    at Gun.chain.back (npm_bundle.js:1)
    at soul (npm_bundle.js:1)
    at Object.go [as use] (npm_bundle.js:1)
    at Object.use (npm_bundle.js:1)
    at Object.input [as next] (npm_bundle.js:1)
    at Object.onto [as on] (npm_bundle.js:1)
    at Object.ack [as next] (npm_bundle.js:1)
    at Object.onto [as on] (npm_bundle.js:1)
    at Object.ask (npm_bundle.js:1)
    at Object.universe [as next] (npm_bundle.js:1)
    at Object.onto [as on] (npm_bundle.js:1)
    at Function.Mesh.mesh.hear (npm_bundle.js:1)
    at WebSocket.wire.onmessage (npm_bundle.js:1)

**Comment by amark** [comment]
@mnts oh fudgestickles. Thanks for reporting, this is an easy typo I can fix, tho can't till late this week. Rollback to a version *several* old in meanwhile?

**Comment by mnts** [comment]
no big rush for me.. Just reported for the future, not to worry

**Comment by amark** [comment]
@mnts I can't replicate (in browser or nodejs), is this happening on latest? (from few days ago)

**Comment by amark** [comment]
... found it. Have fix. Only effects "built" system, not any CDN/etc. ones.

**Comment by omarzion** [comment]
this issue is still occurring on 0.2020.520 has this fix been released on npm yet?

**Comment by amark** [comment]
uggh, this should have gone out but my edit was in a different branch not the one that got published, committing to master now (it'll be pushed later), apologies.

**Comment by lindseymysse** [comment]
As of August 28, 2020 I am getting this error using the npm package manager. Stepping down to version  "gun": "0.2020.430" fixes the bug.

**Comment by DeFUCC** [comment]
2020.520 is still the latest on npm and the problem is still there. Only downgrading to 2019 version helps, but it's obsolete for actual usage.

**Comment by gevera** [comment]
I can confirm, same issue, following official tutorial on Svelte https://gun.eco/docs/Svelte

**Comment by stonewjr** [comment]
I has the same issue too, 
npm version use import from gun/gun
when put(payload) and payload is javascript object will cause  error ' sat undefined'

**Comment by stonewjr** [comment]
if payload is just a primitive value like int, boolen then ok

**Comment by fabianmarz** [comment]
@amark, any news about a new npm release?
