### ISSUE TITLE
[BUG] auth(keypair) saves raw data to sessionStorage.alias

### ISSUE THREAD

**Issue by mimiza** [amark/gun#956]
To reproduce the bug:
```
var pair = await sea.pair()
user.auth(pair) // succeed
sessionStorage.getItem('alias') // "[Object object]" --> BUG
user.leave()
user.auth(pair) // fails
```
This also causes recall() to stop working.
localStorage and sessionStorage can only save String, not Object. Please JSON.stringify() before saving data.

**Comment by bmatusiak** [comment]
1 thing to note here..
.leave() will destroys recall()'s data that is used to restore the session

**Comment by mimiza** [comment]
You have a good point @bmatusiak
