### ISSUE TITLE
Persistence acknowledgement levels

### ISSUE THREAD

**Issue by metasean** [amark/gun#99]
The goal is for gun to have multiple levels of _possible_ acknowledgement (e.g. when a user `put`s data, what level of persistence triggers an acknowledgement of success):
0. file.js (not designed to be used in deployment)
1. browser disk (aka LocalStorage)
2. \* server disk (related to #57)
3. \* responsible browser peer(s)' disk (save functionality is coded; acknowledgement is not coded)
4. \* responsible server peer(s)' disk
5. S3 disk
6. \* responsible peer(s)' S3 server's disk

NOTE: The [current LocalStorage code](https://github.com/amark/gun/blob/master/gun.js#L984-L1146) will only ack success for the LocalStorage level if there are no higher storage levels being used.  The LocalStorage module defers ack to _only_ the highest level storage.

Currently, only File.js, browser disk, and S3 disk are implemented with acknowledgement. Asterisks mark levels currently without storage acknowledgement.

Functionality that still needs to be coded:
- [x] server disk storage ack (related to #57)
- [ ] ack of storage to a responsible browser peer's disk
- [ ] storage to, and ack of storage to, a responsible browser server's disk
- [ ] storage to, and ack of storage to, a peer's S3 server's disk
- [ ] provide an application developer an API to select the desired ack level

For Mark's more detailed thoughts on this (somewhat dated) see - https://news.ycombinator.com/item?id=7596580

**Comment by amark** [comment]
While the use of "level" here is the general word, not the level storage engine. I still think it is worth mentioning that @PsychoLlama wrote https://github.com/PsychoLlama/gun-level BECAUSE that library actually has some tests in it which we'll be able to use and increase for issues like this.

@metasean since Jesse is doing ack tests (at least from what he said, I still gotta get Windows to `npm install level` properly, it used to. Don't know why it won't now), does that resolve this issue?

**Comment by metasean** [comment]
@amark - As there are remaining levels and you're still having Windows-related issues, I'm not closing this, but we did check off the "server disk storage ack".

**Comment by amark** [comment]
0.6+ now has the generic `ack` reply in the `.put(data, function(ack){})` it still auto-unsubscribes after the first ack but that is a 1 line change that is easy enough. Point being is the architecture is now in place that supports this quite nicely. So gonna close it as "done"!

**Comment by PierBover** [comment]
Do you use anything other than localStorage on the browser for persistence?

It's not uncommon for iOS to delete it when it's running out of space.
