### ISSUE TITLE
global leaks sat

### ISSUE THREAD

**Issue by robhicks** [amark/gun#999]
I get this in my unit tests. 

```
Error: global leak(s) detected: 'sat'
    at _.f.chain.once (https://cdnjs.cloudflare.com/ajax/libs/gun/0.2020.520/gun.min.js:1:28068)
```
The script is being loaded in an html page.

**Comment by AdaRoseCannon** [comment]
This also breaks some functionality of gun when it is imported in a ES module. i.e.

```
import "https://cdn.jsdelivr.net/npm/gun/gun.js";
import "https://cdn.jsdelivr.net/npm/gun/lib/unset.js";
```

With the error: `"Uncaught ReferenceError: assignment to undeclared variable sat"`

**Comment by talentlessguy** [comment]
Same issue with Vite:

```
assignment to undeclared variable sat
```

**Comment by amark** [comment]
@talentlessguy oh, this has been fixed for about a year or more - ?maybe it isn't in the NPM that was last published before I froze publishing? , gonna close this issue, please upgrade to latest github. :)

**Comment by talentlessguy** [comment]
@amark why is not version published on npm?
